---
knit: (function(inputFile, encoding) {userName<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/',userName,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'UTF8');htmlName<-'index';rmarkdown::render(inputFile,encoding = encoding,output_file = paste0('C:/Users/',userName,buf0[2,1],'charts/indicator/',htmlName,'.html')) })

title: Indicator
author: Asset Management Consulting Corporation<br>http://am-consulting.co.jp
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

<link  href="http://knowledgevault.saecanet.com/charts/indicator/favicon-bar-chart.ico" rel="icon">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="http://knowledgevault.saecanet.com/components/csvtotable/jquery.csvToTable.indicator.js"></script>
<link  href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet">
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>

## Contents

<script>
  $(function() {
    $('.amcc').CSVToTable('https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/csv/timeSeriesList.csv');
  });
</script>
<div class="amcc"></div>

## Profile


<b>商　号</b> アセット・マネジメント・コンサルティング株式会社

<b>会社設立の年月日</b> 2006年1月11日(平成18年1月11日)

<b>資　本　金</b> 1,000万円

<b>Webサイト</b> http://am-consulting.co.jp 

<b>代 表 取 締 役</b> 三竹 道雄(Mitake Michio)<br>

- 明治大学農学部農芸化学科卒業
- 関東学院大学工学部第二部建設工学科建築系卒業(学士入学)
- 北陸先端科学技術大学院大学知識科学研究科知識科学専攻博士前期課程修了
- 学士(農学)、学士(工学)、修士(知識科学)

***

建築物の維持管理計画策定業務(建築基準法、消防法、電気事業法、建築物における衛生的環境の確保に関する法律その他の建築関連法規に基づく法定点検および自主点検(常駐および巡回点検計画)の年間計画策定とコスト算出業務)および建築物セキュリティ設計業務(パッシブセンサー、電気錠、マグネットセンサー、パニックオープンシステム等を用いた遠隔監視システムの設計). 

***

公共道路(一般道路、高速道路)・トンネル・橋梁の電気設備(受電設備、照明設備(主として低圧ナトリウムランプ)、消防設備、換気設備(ジェットファン)および情報設備)の設計および工事費積算業務. 

- 担当地域：長野県、三重県、高知県. 

***

公共排水処理施設の設計・工事監理業務(土木(液状化対策、土工、掘削工、地盤改良工その他)、建築(排水処理施設建屋、管理棟設計)、電気設備(高圧受変電設備、配電設備、消防設備、監視制御設備、弱電設備、落雷対策その他)、機械設備(マンホールポンプ選定、水中・陸上ポンプ選定)、排水処理設備(生物膜法、浮遊生物法)、バイオマス利活用施設(コンポスト設備)等の設計統括業務)、工事費積算業務および会計検査対応. 

- 担当地域：青森県、岩手県、秋田県、福島県、群馬県、千葉県、長野県、静岡県、鳥取県、愛媛県.

***

エンジニアリングレポート作成・各種工場のインフラ設備(特別高圧受変電設備、非常用自家発電機、無停電電源装置（UPS）、定電圧定周波数装置(CVCF)、パージガス供給設備、冷温水発生設備、サーバー機器等)の耐震性能調査および改善提案報告書・アスベスト含有建材有無およびPCB含有設備有無の判定業務.

***

以上の業務に従事後、アセット・マネジメント・コンサルティング株式会社を設立.

<b>国家資格</b>

- 一級建築士(登録番号：第288254号.平成12年登録)
- 第三種電気主任技術者(第28-3433号.平成4年免状交付)

平成20年11月28日施行新建築士法に基づく管理建築士講習修了者(修了年月日：平成21年12月15日. 修了証番号：第092F-21157X号) 

<b>出生地</b>：東京都渋谷区






## Disclaimer

http://am-consulting.co.jp/disclaimer/

## Link

- 本ページへのリンクを共有:<a href="https://twitter.com/share" class="twitter-share-button" data-via="AMC2_Japan" data-size="large">Tweet</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

<script>MakeNegative();</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-3077339-5', 'auto');
  ga('send', 'pageview');

</script>
