---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y%m%d%H%M%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-knowledgeVaultURL.html')) })

output: html_fragment
---
<!--
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
-->

<!-- knowledgeVaultへのリンク-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<link  href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet">
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function() {
  $('#amcc').DataTable( {
    "order": [[ 0, "asc" ]],
    "lengthMenu":[[10, -1],[10, "All"]],
    "searching" :true,
    "paging"    :true,
    "ordering"  :true,
    "info"      :true,
    "scrollX"   :true
  } );
} );
</script>

<style>
table{white-space: nowrap;}
img.flag {max-width:20px; max-height:20px; width:auto; height:auto;}
</style>

```{r warning=F,error=F,message=F,echo=F}
library(excel.link)
fileName <-'defaultPath.csv'
username <- Sys.info()['user']
pathToFile <- paste0('C:/Users/', username,'/Desktop/pathToCSV/')
setwd(pathToFile)
buf000 <- read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8')
pathOutput <- paste0("C:/Users/", username, buf000[2,1],'csv/')
setwd(pathOutput)
fileName <- dir(pathOutput)[grep('knowledgevault',dir(pathOutput),ignore.case = T)]
tmp0 <- read.table(fileName, sep = ',', fileEncoding = 'utf8', header = T)
```

```{r warning=F,error=F,message=F,echo=F}
buf <- tmp0
buf[,grep('url',colnames(buf),ignore.case = T)] <- 
  paste0('<a href="',buf[,grep('url',colnames(buf),ignore.case = T)],'" target="_blank">Move to Data</a>')
countryCCC <- grep('country',colnames(buf),ignore.case = T)
buf <- buf[,-countryCCC]
```

***

```{r warning=F,error=F,message=F,echo=F,results='asis'}
knitr::kable(buf, row.names = F, format = "html", 
             table.attr = "id='amcc' class='display compact' width='100%' cellspacing='0'", escape = F, 
             align = c("r", "l", "c", "c"))
```

***

<!-- knowledgeVaultへのリンク-->
