```{r warning=F,error=F,message=F,echo=F,results='hide'}
library(ggplot2);library(scales)
windowsFonts(Meiryo = windowsFont("Meiryo"))
options(scipen = 100)
pngWidth <- 1000
pngHeight <- 600
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
fileName <- 
  'functionList.csv'
baseURL <- 
  'https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/'
functionList <- 
  read.csv(
    file = paste0(baseURL,'csv/',fileName),
    header = F,
    as.is = T)
for(iii in 1:nrow(functionList)){
  script <- 
    RCurl::getURL(paste0(baseURL,functionList[iii,1]),ssl.verifypeer = F)
  eval(parse(text = script))
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
userName <- Sys.info()['user']
fileName <- 'defaultPath.csv'
pathToFile <-
  paste0('C:/Users/',userName,'/Desktop/pathToCSV/')
setwd(pathToFile)
buf0 <-
  read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,
           fileEncoding = 'UTF8')
pathOutputCorporateStatistics <-
  paste0('C:/Users/',userName,buf0[2,1],'charts/indicator/AMCC-CorporateStatistics/')
```

```{r}
# https://www.e-stat.go.jp/SG1/toukeidb/GH07010101Forward.do
# [時系列データ]金融業、保険業以外の業種(原数値)
library(Nippon)
csvFile <- 'FEH_00350600_170804121934.csv'
baseURL <- 'https://github.com/am-consulting/am-consulting.github.io/raw/master/csv/csvData/TSdata/'
pathToDownloadFolder <-
  paste0("C:/Users/",Sys.info()['user'],"/Desktop/R_Data_Write/")
setwd(pathToDownloadFolder)
download.file(paste0(baseURL,csvFile),csvFile,mode = 'wb')
buf0 <- read.csv(file = csvFile,header = F,
                 stringsAsFactors = F,na.strings = '',fileEncoding = 'UTF8')
objRaw <- c(grep('統計名',buf0[,1]),nrow(buf0))
houjinToukei <- list()
dfTitle <- vector()
for(iii in seq(length(objRaw)-1)){
  tmp0 <- buf0[objRaw[iii]:(objRaw[iii+1]-1),]
  dfTitle[iii] <- zen2han(paste0(tmp0[4,2],tmp0[4,3],':',tmp0[5,3],':',tmp0[6,3]))
  tmp1 <- tmp0[!is.na(as.numeric(tmp0[,1])),]
  colnames(tmp1) <- sapply(tmp0[9,],zen2han)
  tmp1 <- apply(tmp1,2,as.numeric)
  objCol <- grep('百万円',colnames(tmp1))
  tmp1[,objCol] <- apply(tmp1[,objCol],2,function(x)as.numeric(x)*10^-2)
  colnames(tmp1)[objCol] <- gsub('百万円','億円',colnames(tmp1)[objCol])
  Date <-
    as.Date(paste0(substring(tmp1[,1],1,4),'-',as.numeric(substring(tmp1[,1],5,5))*3,'-1'))
  tmp2 <- tmp1[,-grep('na',colnames(tmp1),ignore.case = T)]
  tmp3 <- data.frame(Date,tmp2,stringsAsFactors = F,check.names = F,row.names = NULL)
  print(tail(tmp3[,1:4]))
  houjinToukei[[iii]] <- tmp3
}
dfTitle
colnames(tmp3)
```

```{r}
objCol <- 163
for(gyoushu in seq(length(houjinToukei))){
  obj0 <- na.omit(houjinToukei[[gyoushu]][,c(1,objCol)])
  obj <- obj0
  dateRange <- paste0(format(range(obj[,1]),'%Y年%m月期'),collapse = '~')
  mainTitle <- gsub('.+月期:(.+)','\\1',dfTitle[gyoushu])
  colnames(obj)[2] <- paste0(mainTitle,':',colnames(obj)[2])
  if(gyoushu==1){allData <-obj}else{allData <- merge(allData,obj,by='Date',all=T)}
  g <- ggplot(data = obj,aes(x = obj[,1],y = obj[,2]))
  g <- g + geom_line(col='blue') + geom_point(col='blue') + geom_smooth(col='red') + xlab('')
  g <- g + scale_y_continuous(name = '',breaks = scales::pretty_breaks(10),sec.axis = dup_axis())
  g <- g + ggtitle(label = paste0(colnames(obj)[2],'\n',dateRange,'\nSource:財務省'))
  g <- g + theme(plot.title = element_text(hjust = 0.5,family = "Meiryo",size = 20))
  g <- g + theme(axis.title.x = element_text(family = "Meiryo",size = 16)) 
  g <- g + theme(axis.title.y = element_text(family = "Meiryo",size = 16)) 
  g <- g + theme(axis.text.x = element_text(angle = 0,family = "Meiryo",size = 16,vjust = 0.5)) 
  g <- g + theme(axis.text.y = element_text(angle = 0,family = "Meiryo",size = 16))
#  print(g)
}
```

```{r}
buf0 <- na.omit(t(tail(allData,1)))
buf1 <- data.frame(rownames(buf0),buf0,stringsAsFactors = F,check.names = F,row.names = NULL)
colnames(buf1) <- buf1[1,]
buf2 <- buf1[-1,]
buf2[,2] <- as.numeric(buf2[,2])
colnames(buf2) <- c('Industry',format(as.Date(colnames(buf2)[2]),'%Y年%m月期'))
buf3 <- buf2[order(buf2[,2]),]
row.names(buf3) <- NULL
latestData <- buf3
```
