---
title : "Functions<br>http://am-consulting.co.jp"
output: 
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
    self_contained: false
    keep_md: no
    md_extensions: -ascii_identifiers
    includes:
       in_header: insertHeader.html
---

```{r setup, include=FALSE}
# https://stackoverflow.com/questions/43329230/r-markdown-add-tag-to-head-of-html-output/43334558#43334558
insertFile <- file("insertHeader.html")
writeLines('
<link rel="shortcut icon" href="http://knowledgevault.saecanet.com/charts/indicator/favicon-bar-chart.ico">
',
insertFile)
close(insertFile)
```

<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet">
<style>.main-container {max-width : 1000px;}</style>

```{r set-options,echo=F,cache=F}
options(scipen = 999)
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
windowsFonts(Meiryo = windowsFont("Meiryo"))
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
fileName <- 
  'functionList.csv'
baseURL <- 
  'https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/'
functionList <- 
  read.csv(file = paste0(baseURL,'csv/',fileName),header = F,as.is = T)
for(iii in 1:nrow(functionList)){
  script <- 
    RCurl::getURL(paste0(baseURL,functionList[iii,1]),ssl.verifypeer = F)
  eval(parse(text = script))
}
```

# Functions

***

```{r warning=F,error=F,message=F,echo=F,results='asis'}
cat("- Title : Functions\n")
cat(paste0("- Date : ",format(Sys.time(),'%Y-%m-%d %H:%M:%S'),'\n'))
```

***

```{r warning=F,error=F,message=F,echo=F,results='hold'}
functionS <- lsf.str()
sapply(functionS[seq(length(functionS))],get)
```

***
<script>MakeNegative();</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-3077339-5', 'auto');
  ga('send', 'pageview');

</script>
