```{r}
fileName <- 
  'functionList.csv'
baseURL <- 
  'https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/'
functionList <- 
  read.csv(
    file = paste0(baseURL,'csv/',fileName),
    header = F,
    as.is = T)
for(iii in 1:nrow(functionList)){
  script <- 
    RCurl::getURL(paste0(baseURL,functionList[iii,1]),ssl.verifypeer = F)
  eval(parse(text = script))
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
windowsFonts(Meiryo = windowsFont("Meiryo"))
options(scipen = 100)
pngWidth <- 1500
pngHeight <- 800
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
library(quantmod);library(PerformanceAnalytics);library(lubridate)
library(ggplot2);library(ggjoy);library(qgraph)
userName <- Sys.info()['user']
fileName <- 'defaultPath.csv'
pathToFile <-
  paste0('C:/Users/',userName,'/Desktop/pathToCSV/')
setwd(pathToFile)
buf0 <-
  read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,
           fileEncoding = 'UTF8')
pathOutputIndicator <- paste0('C:/Users/',userName,buf0[2,1],'charts/indicator/')
```

```{r}
sourceSite <- 2
```

```{r}
if(sourceSite==1){
periodN <- 30
fromFRED <- 
  c('Japan / U.S. Foreign Exchange Rate (DEXJPUS)',
    'U.S. / Euro Foreign Exchange Rate (DEXUSEU)',
    'Canada / U.S. Foreign Exchange Rate (DEXCAUS)',
    'U.S. / U.K. Foreign Exchange Rate (DEXUSUK)',
    'U.S. / Australia Foreign Exchange Rate (DEXUSAL)',
    'Switzerland / U.S. Foreign Exchange Rate (DEXSZUS)',
    'South Africa / U.S. Foreign Exchange Rate (DEXSFUS)',
    'U.S. / New Zealand Foreign Exchange Rate (DEXUSNZ)')
for(iii in seq(length(fromFRED))){
  buf <- fromFRED[iii]
  title <- gsub('(.+)\\((.+)\\)','\\1',buf)
  symbol <- gsub('(.+)\\((.+)\\)','\\2',buf)
  tmp0 <- getSymbols(Symbols = symbol,auto.assign = F,src = 'FRED')
  tmp1 <-
    data.frame(Date = index(tmp0),tmp0,stringsAsFactors = F,check.names = F,row.names = NULL)
  colnames(tmp1)[2] <- gsub('\\s$','',title)
  tmp1 <- na.omit(tmp1)
  if(iii==1){allFXdata0 <- tmp1}else{allFXdata0 <- merge(allFXdata0,tmp1,by='Date')}
  print(tail(tmp1))
}
allFXdata <- na.omit(allFXdata0)
colnames(allFXdata) <- 
  gsub('\\sforeign exchange rate','',colnames(allFXdata),ignore.case = T)
allFXdata$dateGroup <- as.Date(paste0(year(allFXdata$Date),'-',month(allFXdata$Date),'-1'))
}
```

```{r}
if(sourceSite!=1){
periodN <- 7
fromOANDA <- 
  c('USD/JPY','EUR/USD','GBP/USD','AUD/USD','NZD/USD',
    'EUR/GBP','EUR/AUD','GBP/AUD','EUR/CHF','GBP/CHF','USD/CHF')
for(iii in seq(length(fromOANDA))){
  tmp0 <- getSymbols(Symbols = fromOANDA[iii],auto.assign = F,src = 'oanda')
  tmp1 <-
    data.frame(Date = index(tmp0),tmp0,stringsAsFactors = F,check.names = F,row.names = NULL)
  colnames(tmp1) <- gsub('\\.','/',colnames(tmp1))
  tmp1 <- na.omit(tmp1)
  if(iii==1){allFXdata0 <- tmp1}else{allFXdata0 <- merge(allFXdata0,tmp1,by='Date')}
  print(tail(tmp1))
}
allFXdata <- na.omit(allFXdata0)
allFXdata$dateGroup <- ceiling(as.numeric(row.names(allFXdata))/periodN)
}
```

```{r}
fun_aggregateData <- function(fun = 'mean'){
  buf <- aggregate(x = allFXdata[,-1],by = list(allFXdata$dateGroup),FUN = fun)
  return(buf[,-grep('^dateGroup$',colnames(buf),ignore.case = T)])
}
fun_plotCorrelation <- function(fun = 'mean',output = 1){
  setwd(pathOutputIndicator)
  if(periodN==7){periodTxt <- paste0('By ',periodN,'days')}else{periodTxt <- 'By 1month'}
  obj <- fun_aggregateData(fun = fun)
  dateRange <- paste0(format(range(allFXdata$Date),'%Y-%m-%d'),collapse = '~')
  if(output!=0){
    png(file = paste0(fun,'-correlation-level.png'),width = pngWidth,height = pngHeight)
  }
  chart.Correlation(R = obj[,-1],
                    main = paste0(dateRange,'.Level.FUN=',fun,'.Period:',periodTxt),
                    cex.main = 2.2,cex.labels=2.5)
  if(output!=0){dev.off();}
  if(output!=0){
    png(file = paste0(fun,'-correlation-diff.png'),width = pngWidth,height = pngHeight)
  }
  chart.Correlation(R = fun_makeDiffTable(obj = obj,lag = 1)[,-1],
                    main = paste0(dateRange,'.1st Diff.FUN=',fun,'.Period:',periodTxt),
                    cex.main = 2.2,cex.labels=2.5)
  if(output!=0){dev.off();}
}
fun_plotCorrelation(fun = 'mean',output = 1)
fun_plotCorrelation(fun = 'var',output = 1)
```

```{r}
fun_undirectedGraph <- function(minimum = 0.2,vsize = 8,cex = 1,output = 0,fun = 'mean',width = 900,height = 900){
  par(family = 'Meiryo')
  setwd(pathOutputIndicator)
  if(output!=0){
    png(file = paste0('undirectedGraph-Level-',fun,'.png'),width = width,height = height)
  }
  obj <- fun_aggregateData(fun = fun)
  qgraph(cor(obj[,-1]),edge.labels = T,minimum = minimum,label.cex = cex,
         labels = colnames(obj[,-1]),vsize = vsize)
  title(main = list(paste0('Level.FUN=',fun,'.Minimum=',minimum),cex = 3),line = 2.0,family = 'Meiryo')
  if(output!=0){dev.off();}
  if(output!=0){
    png(file = paste0('undirectedGraph-1stDiff-',fun,'.png'),width = width,height = height)
  }
  objDiff <- fun_makeDiffTable(obj = obj,lag = 1)
  qgraph(cor(objDiff[,-1]),edge.labels = T,minimum = minimum,label.cex = cex,
         labels = colnames(objDiff[-1]),vsize = vsize)
  title(main = list(paste0('1st Diff.FUN=',fun,'.Minimum=',minimum),cex = 3),line = 2.0,family = 'Meiryo')
  if(output!=0){dev.off();}
}
fun_undirectedGraph(output = 1,fun = 'mean',minimum = 0.2)
fun_undirectedGraph(output = 1,fun = 'var',minimum = 0.2)
```

```{r}
fromOANDA <- 
  c('USD/JPY','EUR/JPY','GBP/JPY','AUD/JPY','NZD/JPY','CAD/JPY','CHF/JPY','TRY/JPY','ZAR/JPY',
    'EUR/USD','GBP/USD','AUD/USD','NZD/USD',
    'EUR/GBP','EUR/AUD','GBP/AUD','EUR/CHF','GBP/CHF','USD/CHF')
dateRange <- vector() 
for(iii in seq(length(fromOANDA))){
  tmp <- getSymbols(Symbols = fromOANDA[iii],auto.assign = F,src = 'oanda')
  dateRange[iii] <- paste0(range(index(tmp)),collapse = '~')
  DoD <- (tail(as.vector(tmp[,1]),-1)/head(as.vector(tmp[,1]),-1)-1)*100
  pairName <- gsub('\\.','/',colnames(tmp))
  DoDdata0 <- data.frame(DoD,pairName,stringsAsFactors = F,check.names = F,row.names = NULL)
  colnames(DoDdata0) <- c('dummy1','dummy2')
  qnt <- 
    quantile(DoDdata0[,1],probs = c(0.25,0.75),na.rm = T)
  H <- 
    1.5*IQR(DoDdata0[,1],na.rm = T)
  DoDdata1 <- 
    DoDdata0[qnt[1]-H < DoDdata0[,1] & DoDdata0[,1] < qnt[2]+H,]
  if(iii==1){
    allFXdata0 <- DoDdata0
    allFXdata1 <- DoDdata1
  }else{
    allFXdata0 <- rbind(allFXdata0,DoDdata0)
    allFXdata1 <- rbind(allFXdata1,DoDdata1)
  }
}
colnames(allFXdata0) <- colnames(allFXdata1) <- c('In comparison with the day before(%)','Pair')
allFXdata0$Pair <- factor(x = allFXdata0$Pair,levels = unique(allFXdata0$Pair))
allFXdata1$Pair <- factor(x = allFXdata1$Pair,levels = unique(allFXdata1$Pair))
```

```{r}
fun_plotJOY <- function(plotObj,titleAppend = '',joyScale = 3,joyAlpha = 0.5,output = 0,pngN = 1){
  setwd(pathOutputIndicator)
  if(output!=0){
    png(file = paste0('JoyPlot-',pngN,'.png'),width = pngWidth,height = pngHeight)
  }
  g <- ggplot(data = plotObj,aes(y = Pair,x = `In comparison with the day before(%)`,fill = Pair))
  g <- g + geom_joy(scale = joyScale,colour = 'white',alpha = joyAlpha)
  g <- g + geom_vline(xintercept = 0, col = "#ffc1c1")
  g <- g + ylab('')
  g <- g + ggtitle(paste0('Volatility of Exchange Rate(%). FX data source:OANDA\nPeriod:',
                          unique(dateRange),'\n',titleAppend))
  g <- g + theme(plot.title = element_text(hjust = 0.5,family = "Meiryo",size = 20))
  g <- g + theme(axis.title.x = element_text(family = "Meiryo",size = 18))
  g <- g + theme(axis.title.y = element_text(family = "Meiryo",size = 18))
  g <- g + theme(axis.text.x = element_text(angle = 0,family = "Meiryo",size = 16)) 
  g <- g + theme(axis.text.y = element_text(angle = 0,family = "Meiryo",size = 16))
  g <- g + theme(legend.text = element_text(size = 16))
  g <- g + theme(legend.title = element_text(size = 16))
  print(g)
  if(output!=0){dev.off();}
}
fun_plotJOY(plotObj = allFXdata0,titleAppend = 'Raw Data',output = 1,pngN = 1,joyScale = 3)
fun_plotJOY(plotObj = allFXdata1,titleAppend = 'Remove Outlier',output = 1,pngN = 2,joyScale = 3)
```
