```{r}
library(ggplot2);library(scales)
pathOutput <- paste0("C:/Users/",Sys.info()['user'],"/Desktop/R_Data_Write/")
options(scipen = 999)
windowsFonts(Meiryo = windowsFont("Meiryo"))
```

```{r}
# http://www.e-stat.go.jp/SG1/estat/List.do?bid=000001015843&cycode=0
baseURL <- 
  'https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/csv/GeneralSurveyOfSchools/'
csvFiles <- c('nen002.csv','nen004.csv','nen005.csv')
allData <- list()
sheetTitle <- vector()
for(iii in 1:3){
  buf0 <- read.csv(file = paste0(baseURL,csvFiles[iii]),header = F,fileEncoding = 'utf8',stringsAsFactors = F)
  sheetTitle[iii] <- buf0[1,1]
  colnames(buf0) <- buf0[grep('区分',buf0[,1]),]
  buf1 <- buf0[-c(1:grep('区分',buf0[,1])),]
  buf1[,-1] <- apply(buf1[,-1],2,as.numeric)
  buf1[,1] <- as.Date(buf1[,1])
  if(iii == 1){
    buf1[,-1] <- apply(buf1[,-1],2,function(x)x*10^-4)
    objCol <- c(2,4,5,7,13,14,16,17,15)
  }
  if(iii == 2){
    objCol <- c(2,4,16,13)
  }
  if(iii == 3){
    buf1[,-1] <- apply(buf1[,-1],2,function(x)round(x,1))
    objCol <- c(2,5,8,11,14,17,20,23)
  }
  for(ccc in seq(length(objCol))){
    tmp <- na.omit(buf1[,c(1,objCol[ccc])])
    tmp$school <- colnames(tmp)[2]
    colnames(tmp)[2] <- sheetTitle[iii]
    if(ccc == 1){bufDF <- tmp}else{bufDF <- rbind(bufDF,tmp)}
  }
  bufDF[,3] <-factor(bufDF[,3],levels = unique(bufDF[,3]))
  allData[[iii]] <- bufDF
  print(tail(allData[[iii]]))
}
```

```{r}
fun_plot <- function(pngN = 1){
# setwd(pathOutput)
# pngFile <- paste0('AMCC-GeneralSurveyOfSchools-',pngN,".png")
# png(file = pngFile, width = 1400, height = 900)
obj <- allData[[pngN]]
dateRange <- paste0(format(range(obj[,1]),'%Y年'),collapse = '~')
if(pngN == 1){
  g <- ggplot(data = obj,aes(x = obj[,1],y = obj[,2],fill = obj[,3]))
  g <- g + geom_bar(stat = 'identity')
  unitTxt <- '(万人)\n'
}
if(pngN != 1){
  g <- ggplot(data = obj,aes(x = obj[,1],y = obj[,2],col = obj[,3]))
  g <- g + geom_line()
  unitTxt <- '(%)\n'
}
g <- g + scale_x_date(name = '',date_breaks = '1 year',labels= date_format('%Y'))
g <- g + scale_y_continuous(name = '',breaks = scales::pretty_breaks(10),sec.axis = dup_axis())
g <- g + ggtitle(label = paste0(sheetTitle[pngN],unitTxt,dateRange,'\nSource:文部科学省'))
g <- g + theme(plot.title = element_text(hjust = 0.5,family = "Meiryo",size = 20))
g <- g + theme(axis.title.x = element_text(family = "Meiryo",size = 16))
g <- g + theme(axis.title.y = element_text(family = "Meiryo",size = 16))
g <- g + theme(axis.text.x = element_text(angle = 90,family = "Meiryo",size = 12,vjust = 0.5)) 
g <- g + theme(axis.text.y = element_text(angle = 0,family = "Meiryo",size = 16))
g <- g + theme(legend.text = element_text(angle = 0,family = "Meiryo",size = 6))
g <- g + theme(legend.position = "right",legend.direction = 'vertical')
if(pngN == 1){g <- g + scale_fill_discrete(name = '')}
if(pngN != 1){g <- g + scale_color_discrete(name = '')}
print(g)
# dev.off()
}
```

```{r}
fun_plot(pngN = 1)
fun_plot(pngN = 2)
fun_plot(pngN = 3)
```
