```{r warning=F,error=F,message=F,echo=F,results='hide'}
windowsFonts(Meiryo = windowsFont("Meiryo"))
options(scipen = 100)
library(ggplot2)
pngWidth <- 1000
pngHeight <- 600
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
userName <- Sys.info()['user']
fileName <- 'defaultPath.csv'
pathToFile <-
  paste0('C:/Users/',userName,'/Desktop/pathToCSV/')
setwd(pathToFile)
buf0 <-
  read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,
           fileEncoding = 'UTF8')
pathOutput <- paste0('C:/Users/',userName,buf0[2,1],'charts/indicator/')
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
dataSource <-
  'Organisation for Economic Co-operation and Development'
script <-
  RCurl::getURL(
    url = "https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/importOECDStatisticData.r",
    ssl.verifypeer = F)
eval(parse(text = script))
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
yyyy <- 2017
mm <- 12
sdmxURL <- paste0("http://stats.oecd.org/restsdmx/sdmx.ashx/GetData/MEI_CLI/LOLITOTR_GYSA.AUS+AUT+BEL+CAN+CHL+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+IRL+ISR+ITA+JPN+KOR+LVA+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA+EA19+G4E+G-7+NAFTA+OECDE+OECD+ONM+A5M+NMEC+BRA+CHN+IND+IDN+RUS+ZAF.M/all?startTime=1947-02&endTime=",yyyy,"-",mm)
fun_OECDStatisticData(sdmxURL = sdmxURL)
oecd01 <- allOECDData
oecd01[,-1] <- apply(oecd01[,-1],2,function(x)round(x,1))
sdmxTitle01 <- '12-month rate of change of the trend restored CLI'

sdmxURL <- paste0("http://stats.oecd.org/restsdmx/sdmx.ashx/GetData/MEI_CLI/LOLITOAA.AUS+AUT+BEL+CAN+CHL+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+IRL+ISR+ITA+JPN+KOR+LVA+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA+EA19+G4E+G-7+NAFTA+OECDE+OECD+ONM+A5M+NMEC+BRA+CHN+IND+IDN+RUS+ZAF.M/all?startTime=1947-02&endTime=",yyyy,"-",mm)
fun_OECDStatisticData(sdmxURL = sdmxURL)
oecd02 <- allOECDData
oecd02[,-1] <- apply(oecd02[,-1],2,function(x)round(x,1))
sdmxTitle02 <- 'Amplitude adjusted'
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
fun_ggplot_line <- function(plotData,pngN,pngTitle,output = 0,needZero = 0,fontSize = 15){
  if(output!=0){
    setwd(pathOutput)
    pngFile <- paste0(pngTitle,pngN,".png")
    png(file = pngFile,width = pngWidth,height = pngHeight)
  }
  if(length(unique(lubridate::day(plotData$Date)))<=5){
    dateFormat <- '%Y-%m'
  }else{
    dateFormat <- '%Y-%m-%d'
  }
  dateRange <- paste0(format(range(plotData$Date),dateFormat),collapse = '~')
  latestData <- paste0(format(tail(plotData,1)[1,1],dateFormat),':',tail(plotData,1)[1,2])
  g <- ggplot(data = plotData,aes(x = Date,y = plotData[,2]))
  g <- g + geom_line(size = 0.5,col = "black")
  g <- g + geom_point(size = 1.0,col = "black")
  g <- g + geom_smooth(method = loess,lwd = 1,col = "red")
  g <- g + scale_x_date(labels = scales::date_format(dateFormat))
  g <- g + theme(plot.title = element_text(family = "Meiryo",hjust = 0.5,size = fontSize))
  g <- g + theme(axis.title.x = element_text(family = "Meiryo",size = fontSize))
  g <- g + theme(axis.title.y = element_text(family = "Meiryo",size = fontSize))
  g <- g + theme(axis.text.x = element_text(family = "Meiryo",size = fontSize, angle = 0))
  g <- g + theme(axis.text.y = element_text(family = "Meiryo",size = fontSize, angle = 90))
  g <- g + xlab('')
  g <- g + ylab('')
  g <- g + ggtitle(paste0(colnames(plotData)[2],'\n',dateRange,
                         '\nSource:',dataSource,
                         '\nUnit Root Test p-value:',round(tseries::adf.test(plotData[,2])$p.value,3),
                         '\nLatest:',latestData))
  if(needZero!=0){g <- g + geom_hline(yintercept = 0,col = 'blue')}
  print(g)
  if(output!=0){dev.off()}
}
```

```{r warning=F,error=F,message=F,echo=F,results='asis'}
for(iii in 2:ncol(oecd01)){
  plotData <- na.omit(oecd01[,c(1,iii)])
  colnames(plotData)[2] <- paste0('Composite Leading Indicators:',colnames(plotData)[2])
  fun_ggplot_line(plotData = plotData,pngN = iii,pngTitle = 'AMCC-OECD-TS-')
}
```
