---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y%m%d%H%M%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',timeStamp,'.html')) })
title : "建築物滅失"
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 8
    fig_width: 12
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 
<style>
.main-container {
	max-width: 1000px;
	margin-left: auto;
	margin-right: auto;
}
</style>


```{r set-options, echo=F, cache=F}
options(width = 1000)
```

```{r,warning=F,error=F,message=F,echo=F}
library(dplyr)
library(lubridate)
library(psych)
library(Hmisc)
library(pastecs)
library(tseries)
library(RCurl)
```

```{r,warning=F,error=F,message=F,echo=F}
loadTMP <- 0
if(loadTMP == 0){
tmp <- read.table('clipboard', header = T, sep = '\t', stringsAsFactor = F, na.strings = c('na', '', '-', 'NA'), check.names = F)
tmp[,1] <- as.Date(tmp[,1])
dateFormat = '%Y年%m月%d日'
if (length(unique(day(tmp[, 1]))) == 1) {
  dateFormat = '%Y年%m月'
}
if (length(unique(month(tmp[, 1]))) == 1) {
  dateFormat = '%Y年'
}
}
```

```{r,warning=F,error=F,message=F,echo=F}
if(loadTMP==1){
  script <-
    getURL(
      "https://raw.githubusercontent.com/am-consulting/Rscript/master/importPERPBR.r",
      ssl.verifypeer = FALSE
    )
  eval(parse(text = script))
  tmp <- PERPBR[,c(1,3,4)]
  dataTitle <- paste0('市場第一部 - 連結総合(加重) - PER･PBR - ',paste0(format(range(tmp[,1]),'%Y年%m月'),collapse='~'))
  dataSource <- '株式会社東京証券取引所'
  tmp[,1] <- as.Date(tmp[,1])
  dateFormat = '%Y年%m月%d日'
  colnames(tmp)[1] <- 'Date'
}
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
omitType <- 1
if(loadTMP == 0){
dataTitle <-
  paste0('Baker Hughes:North America Rig Count Oil ans Gas / 北米リグカウント 石油とガス',' - ',
         format(last(tmp[, 1]), dateFormat))
dataTitle <- '建築物滅失統計調査 月次 2016年7月' 
dataSource <- 'Baker Hughes'
dataSource <- '国土交通省'
}
notes <- '複数のワードで検索する際は半角スペースで区切ってください'
notes0 <- "表中、-9999はNAを意味します"
Author <- "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
htmlID <- timeStamp
cat(paste("Title       : ", dataTitle, "\n"))
cat(paste("Data Source : ", dataSource, "\n"))
cat(paste("Author      : ", Author, "\n"))
cat(paste("作成日      : ", Sys.time(), "\n"))
cat(paste("特記        : ", notes, "\n"))
cat(paste("特記        : ", notes0, "\n"))
cat(paste("ID          : ", htmlID, "\n"))
windowsFonts(Meiryo = windowsFont("Meiryo"))
options(scipen = 999)
```

```{r,warning=F,error=F,message=F,echo=F}
if(omitType==1) {
  dataSet <- na.omit(tmp)
} else{
  dataSet <- tmp[rowSums(is.na(tmp)) != (ncol(tmp) - 1), ]
}
```

```{r,warning=F,error=F,message=F,echo=F} 
funPlotTimeSeries <- function() {
  mainTitle <-
    paste(colnames(dataSet)[obj01], '\n×\n', colnames(dataSet)[obj02])
  maxValue <- max(dataSet[, obj01], dataSet[, obj02])
  minValue <- min(dataSet[, obj01], dataSet[, obj02])
  par(mar = c(3, 5, 6, 5), family = 'Meiryo')
  plot(
    dataSet[, 1],
    dataSet[, obj01],
    type = seriesType01,
    col = lineColor[1],
    xlab = '' ,
    ylab = '' ,
    panel.first = grid(nx = NULL, ny = NULL, lty = 2, equilogs = T) ,
    xaxt = 'n',
    ylim = if (needYlim == 1) {c(minValue, maxValue)},
    main = paste(mainTitle, '\n', datePeriod, '\nSource:', dataSource),
    cex.axis = 1, cex.lab = 1, cex.main = 1, lwd = obj01lwd
  )
  if (needloess01 == 1) {
    lo <- loess(dataSet[, obj01] ~ as.numeric(dataSet[, 1]), degree = 2)
    lines(dataSet[, 1] , predict(lo) , col = lineColor[1], lwd = 2, lty = 2)
  }
  if (chartTtpe == 1) {
    lines(dataSet[, 1], dataSet[, obj02], col = lineColor[2], lwd = obj02lwd)
  } else{
    par(new = T)
    plot(
      dataSet[, 1],
      dataSet[, obj02],
      col = lineColor[2],
      type = seriesType02,
      xlab = '' ,
      ylab = '' ,
      panel.first = grid(nx = NULL, ny = NULL, lty = 2, equilogs = T) ,
      xaxt = 'n',
      yaxt = 'n',
      cex.axis = 1, cex.lab = 1, cex.main = 1, lwd = obj02lwd
    )
    axis(4, cex.axis = 1, cex.lab = 1)
    mtext(colnames(dataSet)[obj01], side = 2, line = 3.2, cex = 1)
    mtext(colnames(dataSet)[obj02], side = 4, line = 3.2, cex = 1)
  }
  if (needloess02 == 1) {
    lo <- loess(dataSet[, obj02] ~ as.numeric(dataSet[, 1]), degree = 2)
    lines(dataSet[, 1] , predict(lo) , col = lineColor[2], lwd = 2, lty = 2)
  }
  graphics::legend(
    'topleft',
    col = lineColor[-3],
    lty = 1,
    legend = c(colnames(dataSet)[obj01], colnames(dataSet)[obj02]),
    cex = 1,
    bty = 'n'
  )
  axis.Date(side = 1, at = dataSet[, 1], format = dateFormat, padj = 1, cex.axis = 1.0)
}
```

```{r,warning=F,error=F,message=F,echo=F}
funDataTable <- function(obj, orderColumn = 0, orderDirection = 'desc', width01 = '10%', caption = '') {
  DT::datatable(
    obj,
    extensions = c("Buttons", "ColReorder" , "FixedColumns", "FixedHeader"),
    options = list(paging = T, autoWidth = F, info = T, lengthChange = T, ordering = T,
      searching = T, scrollX = T, lengthMenu = list(c(10, 50, -1, 1), c(10, 50, 'All', 1)),
      orderClasses = T, order = list(list(orderColumn, orderDirection)), 
      search = list(regex = T, caseInsensitive = T), searchHighlight = T,
      columnDefs = list(list(width = width01, targets = 0)),
      dom = 'BRlfrtip', buttons = I('colvis'), colReorder = T, fixedColumns = list(leftColumns = 1), fixedHeader = T),
    rownames = F, caption = caption, class = 'display compact', escape = F, filter = 'top'
  )  
}
```

```{r,warning=F,error=F,message=F,results='asis',echo=F,fig.height=6,fig.width=10}
lineColor <- c('blue', 'red', 'black')
chartTtpe <- 1
if (chartTtpe == 1) {
  needYlim <- 1
} else{
  needYlim <- 0
}
seriesType01 <- 'l'
seriesType02 <- 'l'
obj01 <- 2
obj02 <- 3
obj01lwd <- 1
obj02lwd <- 1
needloess01 <- 1
needloess02 <- 1
dataTail <- 12 * 20000
dataSet <- tail(dataSet, dataTail)
datePeriod <- paste0(format(first(dataSet[, 1]), dateFormat), '~', format(last(dataSet[, 1]), dateFormat))
funPlotTimeSeries()
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F,fig.height=6,fig.width=10}
par(mfrow = c(1, 2), mar = c(3, 3, 3, 3), family = 'Meiryo', oma = c(0, 0, 3, 0))
for (ddd in 1:2) {
  bufN <- get(paste0('obj0', ddd))
  hist(
    dataSet[, bufN],
    col = '#ADD8E6',
    main = colnames(dataSet)[bufN],
    cex.main = 1.0
  )
}
mtext(datePeriod, side = 3,outer = T,cex = 1.2)
```
<hr>
```{r,warning=F,error=F,message=F,results='hold',echo=F}
cat(paste0(as.Date(range(dataSet[,1])),collapse = ' ~ '))
summary(dataSet[,-1])
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
psych::describe(dataSet[,-1])
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
#Hmisc::describe(dataSet[,-1])
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
pastecs::stat.desc(dataSet[,-1]) 
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
apply(dataSet[,-1],2,adf.test)
```

<hr>

```{r warning=F, error=F, message=F, results='asis', echo=F}
if(dataSource != 'Baker Hughes'){
dataSet0 <- dataSet
origcolN <- ncol(dataSet0)
dataSet0$Y  <- year(dataSet0[,1])
dataSet0$H <- ceiling(month(dataSet0[,1])/6)
dataSet0$Q <- ceiling(month(dataSet0[,1])/3)
objY <- unique(dataSet0$Y)
objH <- unique(dataSet0$H)
objQ <- unique(dataSet0$Q)
for(yyyy in objY){
  buf0 <- subset(dataSet0[,-1], dataSet0$Y == yyyy)
  buf1 <- cbind(rbind(paste0(yyyy,'(Total)'),paste0(yyyy,'(MonthlyAverage)')), 
                rbind(colSums(buf0), round(colSums(buf0)/nrow(buf0),2)))
  if(yyyy==objY[1]){summaryTable0 <- buf1}else{summaryTable0 <- rbind(summaryTable0, buf1)}
  for(HH in sort(objH)){
    buf1 <- subset(buf0, buf0$H == HH)
    if(nrow(buf1)!=0){
      buf2 <- cbind(rbind(paste0(yyyy,'H',HH,'(Total)'),paste0(yyyy,'H',HH,'(MonthlyAverage)')), 
                    rbind(colSums(buf1), round(colSums(buf1)/nrow(buf1),2)))
      summaryTable0 <- rbind(summaryTable0, buf2)
    }
  }
  for(QQ in sort(objQ)){
    buf1 <- subset(buf0, buf0$Q == QQ)
    if(nrow(buf1)!=0){
      buf2 <- cbind(rbind(paste0(yyyy,'Q',QQ,'(Total)'),paste0(yyyy,'Q',QQ,'(MonthlyAverage)')), 
                    rbind(colSums(buf1), round(colSums(buf1)/nrow(buf1),2)))
      summaryTable0 <- rbind(summaryTable0, buf2)
    }
  }
}
summaryTable <- summaryTable0[,1:origcolN]
summaryTable <- data.frame(ID = c(1:nrow(summaryTable)), summaryTable[,1], 
                           apply(summaryTable[,-1],2,as.numeric), check.names = F, stringsAsFactors = F)
colnames(summaryTable)[2]<- 'Summary'
funDataTable(obj = summaryTable, width01 = '5%', orderDirection = 'asc' )
}
```

<hr>

```{r,warning=F,error=F,message=F,results='asis',echo=F}
dataSet0 <- dataSet
dataSet0[, 1] <- format(dataSet0[, 1], dateFormat)
funDataTable(obj = dataSet0, width01 = '15%')
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
if(dataSource == 'Baker Hughes'){
dataSet0 <- dataSet
dataSet0 <- data.frame(dataSet0[-1,1,drop=F],round(diff(as.matrix(dataSet0[,-1,drop=F])),10),check.names = F)
colnames(dataSet0)[-1] <- paste0(colnames(dataSet0)[-1],'-Change From Last Data')
dataSet1 <- dataSet
dataSet1[,-1] <- apply(dataSet1[,-1,drop=F],2,function(x){round(x/max(x)*100,1)})
colnames(dataSet1)[-1] <- paste0(colnames(dataSet1)[-1],'-Ratio to Peak')
dataSet0 <- merge(dataSet, dataSet0, by = 'Date',all = T)
dataSet0 <- merge(dataSet0, dataSet1, by = 'Date',all = T)
#dataSet0[is.na(dataSet0)] <- ''
#dataframeのNAを''に置換すると、そのNAを含む列全てがcharacterに変換されてしまうので注意
dataSet0[, 1] <- format(dataSet0[, 1], dateFormat)
funDataTable(obj = dataSet0, width01 = '15%')
}
```
<hr>
```{r,warning=F,error=F,message=F,results='hide',echo=F}
knitr::kable(tail(dataSet,12),row.names = F)
```


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-3077339-5', 'auto');
  ga('send', 'pageview');

</script>