---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',format(Sys.time(),'%Y-%m-%d-%H-%M-%S'),'.html')) })
title : "景気動向"
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 8
    fig_width: 12
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 
<style>
.main-container {
	max-width: 1100px;
	margin-left: auto;
	margin-right: auto;
}
</style>

```{r,warning=F,error=F,message=F,results='hold',echo=F}
omitType <- 1
dataTitle<-'景気動向指数-先行系列 消費者態度指数×中小企業売上げ見通しDI 2016年7月'
dataSource<-'内閣府'
notes<-'複数のワードで検索する際は半角スペースで区切ってください'
notes0<-"表中、-9999はNAを意味します"
Author<-"アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
htmlID<-format(Sys.time(),'%Y-%m-%d-%H-%M-%S')
cat(paste("Title :",dataTitle,"\n"))
cat(paste("Raw Data Source :",dataSource,"\n"))
cat(paste("Author :",Author,"\n"))
cat(paste("作成日 :",Sys.time(),"\n"))
cat(paste("特記 :",notes,"\n"))
cat(paste("特記 :",notes0,"\n"))
cat(paste("ID :",htmlID,"\n"))
windowsFonts(Meiryo=windowsFont("Meiryo"))
options(scipen = 999)
```

```{r,warning=F,error=F,message=F,echo=F}
loadTMP <- 1
```

```{r,warning=F,error=F,message=F,echo=F}
library(lubridate)
library(ggplot2)
library(scales)
library(reshape)
library(dplyr)
library(RCurl)
library(rAmCharts)
library(seasonal)
library(zoo)
library(knitr)
library(car)
script <-
  getURL(
    'https://raw.githubusercontent.com/am-consulting/Rscript/master/Rscript_HighestAuthority.r',
    ssl.verifypeer = FALSE
  )
eval(parse(text = script))
highestAuthority()
```

```{r,warning=F,error=F,message=F,echo=F}
iii <- 1
highestData <- switch (iii,
                       get(titleAbb[1]),
                       get(titleAbb[2]),
                       get(titleAbb[3]),
                       get(titleAbb[4]))

FUN <- function(x) {
  highestData[which(highestData[1] <= x &
                      highestData[2] >= x, arr.ind = F), 3]
}
```

```{r,warning=F,error=F,message=F,echo=F}
if(loadTMP==1){
tmp <-
  read.table(
    'clipboard',
    header = T,
    sep = '\t',
    stringsAsFactor = F,
    na.strings = c('na', '', '-', 'NA'),
    check.names = F
  )
}
```

```{r,warning=F,error=F,message=F,echo=F}
if(loadTMP==2){
library(RCurl)
script <-
  getURL(
    "https://raw.githubusercontent.com/am-consulting/Rscript/master/importPERPBR.r",
    ssl.verifypeer = FALSE
  )
eval(parse(text = script))
tmp <- PERPBR[,c(1,3,4)]
}
```

```{r,warning=F,error=F,message=F,echo=F}
if(loadTMP==3){
library(RCurl)
script <-
  getURL(
    "https://raw.githubusercontent.com/am-consulting/Rscript/master/importBondInterestRateWithUSDJPY.r",
    ssl.verifypeer = FALSE
  )
eval(parse(text = script))
tmp0<-bondInterestRateWithUSDJPY[,c(1,2,5,16)]
tmp<-data.frame(tmp0[,1],tmp0[,2],tmp0[,3]-tmp0[,4],check.names = F)
colnames(tmp)<-c(colnames(tmp0)[1],colnames(tmp0)[2],paste0(colnames(tmp0)[3],'-',colnames(tmp0)[4]))
}
```

```{r,warning=F,error=F,message=F,echo=F}
if(omitType==1) {
dataSet <- na.omit(tmp)
}else{
dataSet <- tmp[rowSums(is.na(tmp))!=(ncol(tmp)-1),]
}
dataSet[, 1] <- as.Date(dataSet[, 1])
dataSet <-
  data.frame(dataSet, apply(dataSet[1], 1, FUN), check.names = F)
colnames(dataSet)[ncol(dataSet)] <- indextitle[iii]
dateFormat = '%Y-%m-%d'
if (length(unique(day(dataSet[, 1]))) == 1) {
  dateFormat = '%Y-%m'
}
if (length(unique(month(dataSet[, 1]))) == 1) {
  dateFormat = '%Y'
}
```

```{r,warning=F,error=F,message=F,echo=F} 
# seasonal adjust part
funSeasonal <- function() {
  tmpSA <- dataSet
  buf01 <-
    ts(data = tmpSA[, obj01],
       start = c(year(tmpSA[1, 1]), month(tmpSA[1, 1])),
       freq = 12)
  buf02 <-
    ts(data = tmpSA[, obj02],
       start = c(year(tmpSA[1, 1]), month(tmpSA[1, 1])),
       freq = 12)
  result01 <- final(seas(buf01, na.action = na.omit))
  result02 <- final(seas(buf02, na.action = na.omit))
  tmpSA[, obj01] <- as.matrix(result01)
  tmpSA[, obj02] <- as.matrix(result02)
  dataSetSA <<- tmpSA
}
# seasonal adjust part
```

```{r,warning=F,error=F,message=F,echo=F} 
funPlotTimeSeries <- function() {
mainTitle<-paste(colnames(dataSet)[obj01],'\n×\n',colnames(dataSet)[obj02])
maxValue<-max(dataSet[,obj01],dataSet[,obj02])
minValue<-min(dataSet[,obj01],dataSet[,obj02])
par(mar=c(3,5,6,5),family = 'Meiryo')
plot(
  dataSet[, 1],
  dataSet[, obj01],
  type = seriesType01,
  col = lineColor[1],
  xlab = '' ,
  ylab = '' ,
  panel.first = grid(
    nx = NULL,
    ny = NULL,
    lty = 2,
    equilogs = T
  ) ,
  xaxt = 'n',
  ylim = if(needYlim == 1){c(minValue, maxValue)},
  main = paste(mainTitle,'\n',format(first(dataSet[,1]),dateFormat),'~',format(last(dataSet[,1]),dateFormat),'\nSource:',dataSource),
  cex.axis = 1,
  cex.lab = 1,
  cex.main = 1,
  lwd = obj01lwd
  )
if(needloess01==1){
lo <- loess(dataSet[, obj01]~as.numeric(dataSet[, 1]))
lines(dataSet[, 1] , predict(lo) , col=lineColor[1], lwd=2,lty=2)
}
# SA part
if(needSA01==1) {
  lines(
    dataSetSA[, 1],
    dataSetSA[, obj01],
    col = lineColor[3],
    lwd = 1,
    lty = 1
  )
}
# SA part
if(chartTtpe==1){
lines(
  dataSet[, 1],
  dataSet[, obj02],
  col = lineColor[2],
  lwd = obj02lwd
)
}else{  
par(new=T)
plot(
  dataSet[,1],
  dataSet[,obj02],
  col=lineColor[2],
  type=seriesType02,
  xlab='' ,
  ylab='' ,
  panel.first=grid(nx=NULL,ny=NULL,lty=2,equilogs=T) ,
  xaxt='n',
  yaxt='n',
  cex.axis=1,cex.lab=1,cex.main=1,
  lwd = obj02lwd
)    
axis(4,cex.axis=1,cex.lab=1)
mtext(colnames(dataSet)[obj01],side=2,line=3.2,cex=1)
mtext(colnames(dataSet)[obj02],side=4,line=3.2,cex=1)
}
if(needloess02==1){
lo <- loess(dataSet[, obj02]~as.numeric(dataSet[, 1]))
lines(dataSet[, 1] , predict(lo) , col=lineColor[2], lwd=2,lty=2)
}
# SA part
if(needSA02==1) {
  lines(
    dataSetSA[, 1],
    dataSetSA[, obj02],
    col = lineColor[3],
    lwd = 1,
    lty = 1
  )
}
# SA part
graphics::legend('topleft',col=lineColor[-3],lty=1,legend=c(colnames(dataSet)[obj01],colnames(dataSet)[obj02]),cex=1,bty='n')
axis.Date(side=1,at=dataSet[,1],format=dateFormat,padj=1,cex.axis=1.0)  
}
```

```{r,warning=F,error=F,message=F,echo=F}
funDataTable <- function() {
  DT::datatable(
    dataSet0,
    options = list(
      search.regex = T,
      paging = T,
      autoWidth = F,
      info = T,
      lengthChange = T,
      ordering = T,
      searching = T,
      scrollX = T,
      lengthMenu = list(c(10, -1, 1), c('10', 'All', '1')),
      orderClasses = T,
      order = list(list(0, 'desc')),
      columnDefs = list(
        list(width = '10%', targets = 0)#,
#        list(width = '25%', targets = 3)
        )
      ),
    rownames = F,
    caption = paste(dataTitle,'. Source:' ,dataSource),
    class = 'display compact'
  )
}
```

```{r,warning=F,error=F,message=F,results='asis',echo=F,fig.height=6,fig.width=11}
lineColor<-c('red','blue','black')
chartTtpe<-2
if(chartTtpe==1){needYlim<-1}else{needYlim<-0}
seriesType01<-'l'
seriesType02<-'l'
obj01<-2
obj02<-3
funSeasonal()
obj01lwd<-1
obj02lwd<-1
needloess01<-1
needloess02<-1
needSA01<-0
needSA02<-0
needCCF<-0
need1stdiff<-0
dataTail<-12*20000
bufdataSet<-dataSet
dataSet<-tail(dataSet,dataTail)
funPlotTimeSeries()
dataSet<-bufdataSet
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F,fig.height=6,fig.width=11}
dateRangeS <- rangeNameS <- list()
dateRangeS[[1]] <- as.Date(c('2009/9/1', '2012/12/1'))
dateRangeS[[2]] <- c(as.Date('2013/1/1'), Sys.Date())
rangeNameS[[1]] <- '民主党政権'
rangeNameS[[2]] <- '第二次安倍政権発足以降'
################################################
for (iii in 1:length(dateRangeS)) {
  buf <-
    subset(dataSet, dateRangeS[[iii]][1] <= dataSet[, 1] &
             dataSet[, 1] <= dateRangeS[[iii]][2])
  buf$Group <- paste0(rangeNameS[[iii]],':',paste(format(buf[1,1],dateFormat),'~',format(buf[nrow(buf),1],dateFormat)))
  if (iii == 1) {
    dataSetS <- buf
  }
  dataSetS <- rbind(dataSetS, buf)
}
dataSetS <<- dataSetS
obj01S <<- 2
obj02S <<- 3
obj03S <<- 4
par(family = 'Meiryo', mar = c(5, 5, 5, 1))
scatterplot(
  dataSetS[, obj02S] ~ dataSetS[, obj01S] |
    Group,
  data = dataSetS,
  boxplots = "xy",
  xlab = colnames(dataSetS)[obj01S],
  ylab = colnames(dataSetS)[obj02S],
  smooth = F,
  reg.line = F,
  cex = 1.5,
  cex.axis = 1.2,
  cex.lab = 1.2,
  cex.main = 1.2
)
```

```{r,warning=F,error=F,message=F,echo=F} 
funPlotBoxplotAmcharts <- function(obj, bigTitle = '') {
  cat(paste0('<b>', bigTitle, '</b>'))
  amBoxplot(obj, horiz = T)
}
```
<hr>
```{r,warning=F,error=F,message=F,echo=F,include=F}
out = NULL
for (iii in 2:(ncol(dataSet) - 1)) {
  knit_expanded_1 <-
    paste0(
      "\n```{r results='asis', echo=F}\n\n",
      "dateRange<-paste0(format(first(dataSet[,1]),dateFormat),'~',format(last(dataSet[,1]),dateFormat))\n\n",
      "funPlotBoxplotAmcharts(obj = dataSet[,",
      iii,
      ",drop=F], bigTitle = paste(dataTitle,dateRange,'. Powered By https://www.amcharts.com/'))
\n\ncat('<hr>')\n\n```"
    )
  out = c(out, knit_expanded_1)
}
```
`r paste(knit(text = out), collapse = '\n')`
```{r,warning=F,error=F,message=F,results='asis',echo=F}
cat('<b>原系列 / Original</b>')
bufdataSet <- dataSet
dataSet0 <- dataSet
dataSet0[is.na(dataSet0)] <- ''
dataSet0[, 1] <- format(dataSet0[, 1], dateFormat)
funDataTable()
dataSet <- bufdataSet
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
if(need1stdiff!=0){
cat('<b>1次階差 / 1st difference</b>')
bufdataSet <- dataSet
dataSet0 <- dataSet
dataSet0 <-
  data.frame(dataSet0[-1, 1],
             diff(as.matrix(dataSet0[, -c(1, 4)]), differences = 1),
             dataSet0[-1, 4],
             check.names = F)
colnames(dataSet0) <- colnames(dataSet)
dataSet0[is.na(dataSet0)] <- ''
dataSet0[, 1] <- format(dataSet0[, 1], dateFormat)
funDataTable()
dataSet <- bufdataSet
cat('<hr>')
}
```

```{r,warning=F,error=F,message=F,results='asis',echo=F,fig.height=6,fig.width=12}
if(needCCF!=0){
par(mfrow = c(1, 2), family = 'Meiryo',oma=c(1,1,5,1))
obj01 <- 2
obj02 <- 3
ccf(dataSet[, obj01],
    dataSet[, obj02],
    main = 'Level'
)    
ccf(
  diff(dataSet[, obj01], lag = 1),
  diff(dataSet[, obj02], lag = 1),
  main = '1st Difference'
)
mtext(paste(colnames(dataSet)[obj01], '\n×\n', colnames(dataSet)[obj02]),side = 3,outer = T)
}
```