---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y%m%d%H%M%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',timeStamp,'.html')) })
title : "体力体格"
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 6
    fig_width: 10
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 
<style>
.main-container {
	max-width: 1000px;
	margin-left: auto;
	margin-right: auto;
}
</style>

```{r set-options, echo=F, cache=F}
options(width = 1000)
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
dataTitle <- '体力･運動能力調査 平成27年度 年齢別体格測定の結果 身長と体重'
dataSource <- '文部科学省'
notes <- '複数のワードで検索する際は半角スペースで区切ってください'
notes0 <- "表中、-9999はNAを意味します"
Author <- "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
htmlID <- timeStamp
cat(paste("Title :", dataTitle, "\n"))
cat(paste("Raw Data Source :", dataSource, "\n"))
cat(paste("Author :", Author, "\n"))
cat(paste("作成日 :", Sys.time(), "\n"))
cat(paste("特記 :", notes, "\n"))
cat(paste("特記 :", notes0, "\n"))
cat(paste("ID :", htmlID, "\n"))
windowsFonts(Meiryo=windowsFont("Meiryo"))
options(scipen = 999)
```

1. "標本にバイアスは無い"と想定しています。
1. "標本のバイアス有無"は確認していません。

```{r,warning=F,error=F,message=F,results='hold',echo=F}
library(RCurl)
targetURL <-
'https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/csv/%E4%BD%93%E5%8A%9B%EF%BD%A5%E9%81%8B%E5%8B%95%E8%83%BD%E5%8A%9B%E8%AA%BF%E6%9F%BB-%E5%B9%B3%E6%88%9027%E5%B9%B4%E5%BA%A6-%E5%B9%B4%E9%BD%A2%E5%88%A5%E4%BD%93%E6%A0%BC%E6%B8%AC%E5%AE%9A%E3%81%AE%E7%B5%90%E6%9E%9C-%E8%BA%AB%E9%95%B7%EF%BD%A5%E4%BD%93%E9%87%8D_%E5%87%BA%E6%89%80-%E6%96%87%E9%83%A8%E7%A7%91%E5%AD%A6%E7%9C%81.csv'
dataSet <- read.csv(text = getURL(targetURL), check.names = F, stringsAsFactors = F)
#colnames(dataSet)
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
funPlot01 <- function(dataOBJ,mainTitle='') {
  plot(
    dataOBJ[, obj[1]],
    type = 'o',
    xaxt = 'n',
    xlab = colnames(dataOBJ)[1],
    ylab = '',
    col = 'blue',
    panel.first = grid(nx = NULL, ny = NULL, lty = 2, equilogs = T),
    main = mainTitle,
    cex.axis = 1.2,
    cex.lab = 1.2,
    cex.main = 1.2,
    lwd = 1
  )
  axis(side = 1, at = seq(1, nrow(dataOBJ)), labels = dataOBJ[, 1], las = 2, cex = 1.2)
  lines(dataOBJ[, obj[2]], type = 'o', col = 'red')
  graphics::legend('topleft', col = c('blue', 'red'), lty = 1, legend = colnames(dataOBJ)[obj], cex = 1.2, bty = 'n')
}
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
par(mfrow=c(1,3),mar=c(6,3,1,1),family='Meiryo',oma=c(0,0,3,0))
# 身長
obj <- c(3, 6)
funPlot01(dataOBJ = dataSet)
# 体重
obj <- c(9, 12)
funPlot01(dataOBJ = dataSet)
# BMI
bmiM <- round(dataSet[, 9] / (dataSet[, 3] / 100) ^ 2, 1)
bmiF <- round(dataSet[, 12] / (dataSet[, 6] / 100) ^ 2, 1)
bmi <- data.frame(dataSet[, 1, drop = F], bmiM, bmiF)
colnames(bmi) <- c('年齢', 'BMI-男子', 'BMI-女子')
obj <- c(2, 3)
funPlot01(dataOBJ = bmi, mainTitle = 'BMI=体重(kg)÷身長(m)^2')
mtext(paste(dataTitle, '\nSource:', dataSource),side = 3,outer = T)
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
fun_populationMean <- function(n, mean, sd, append) {
  sampleMean <- dataSet[, mean]
  sampleSD <- dataSet[, sd]
  sampleN <- dataSet[, n]
  t <- qt(0.975, df = sampleN - 1, lower.tail = T)
  meanURange <- round(sampleMean + t * sampleSD / sqrt(sampleN), 2)
  meanLRange <- round(sampleMean - t * sampleSD / sqrt(sampleN), 2)
  pMean <- data.frame(ID=seq(1, nrow(dataSet)), dataSet[, 1], meanLRange, meanURange, dataSet[, mean], dataSet[, sd], dataSet[, n])
  colnames(pMean)[-1] <- 
    paste0(
      c('年齢', '推定母平均(CI95%,Lower)', '推定母平均(CI95%,Upper)', colnames(dataSet)[mean], colnames(dataSet)[sd],colnames(dataSet)[n]), append)
  return(pMean)
}

funDataTable <- function(obj) {
  DT::datatable(
    obj,
    options = list(
      search.regex = F,
      paging = F,
      autoWidth = F,
      info = F,
      lengthChange = F,
      ordering = T,
      searching = T,
      scrollX = F,
      orderClasses = T,
      order = list(list(0, 'asc')),
      columnDefs = list(list(width = '5%', targets = 0))
      ),
    rownames = F,
    caption = paste(dataTitle,'. Source:' ,dataSource),
    class = 'display compact',
    filter = 'bottom'
  )
}
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
buf <- data.frame(
  ID=seq(1,nrow(dataSet)), 
  dataSet[,c(1,3,9), drop= F] ,
  bmi[,2 , drop= F], 
  '身長(cm,+1σ)'=dataSet[,3] + dataSet[,4],
  '身長(cm,-1σ)'=dataSet[,3] - dataSet[,4],
  '身長(cm,+2σ)'=dataSet[,3] + dataSet[,4] * 2,
  '身長(cm,-2σ)'=dataSet[,3] - dataSet[,4] * 2,
  check.names = F)
funDataTable(obj = buf)
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
buf <- data.frame(
  ID=seq(1,nrow(dataSet)), 
  dataSet[,c(1,6,12), drop= F],
  bmi[,3 , drop= F], 
  '身長(cm,+1σ)'=dataSet[,6] + dataSet[,7],
  '身長(cm,-1σ)'=dataSet[,6] - dataSet[,7],
  '身長(cm,+2σ)'=dataSet[,6] + dataSet[,7] * 2,
  '身長(cm,-2σ)'=dataSet[,6] - dataSet[,7] * 2,  
  check.names = F)
funDataTable(obj = buf)
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
dataTable <- fun_populationMean(  n = 2,  mean = 3,  sd = 4,  append = '-男子'  )
funDataTable(obj=dataTable)
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
dataTable <- fun_populationMean(  n = 5,  mean = 6,  sd = 7,  append = '-女子'  )
funDataTable(obj=dataTable)
```
<hr>
```{r,warning=F,error=F,message=F,results='hold',echo=F}
buf<-tail(dataSet,-14)
obj <- c(2,3)
cat(paste0('男子平均身長(20歳以上,cm). Sum(',colnames(buf)[obj[1]],' × ',colnames(buf)[obj[2]],') / Sum(',colnames(buf)[obj[1]],')\n'))
sum(buf[,obj[1]]*buf[,obj[2]])/sum(buf[,obj[1]])
cat('\n\n')
obj <- c(8,9)
cat(paste0('男子平均体重(20歳以上,kg). Sum(',colnames(buf)[obj[1]],' × ',colnames(buf)[obj[2]],') / Sum(',colnames(buf)[obj[1]],')\n'))
sum(buf[,obj[1]]*buf[,obj[2]])/sum(buf[,obj[1]])
cat('\n\n')
obj <- c(5,6)
cat(paste0('女子平均身長(20歳以上,cm). Sum(',colnames(buf)[obj[1]],' × ',colnames(buf)[obj[2]],') / Sum(',colnames(buf)[obj[1]],')\n'))
sum(buf[,obj[1]]*buf[,obj[2]])/sum(buf[,obj[1]])
cat('\n\n')
obj <- c(11,12)
cat(paste0('女子平均体重(20歳以上,kg). Sum(',colnames(buf)[obj[1]],' × ',colnames(buf)[obj[2]],') / Sum(',colnames(buf)[obj[1]],')\n'))
sum(buf[,obj[1]]*buf[,obj[2]])/sum(buf[,obj[1]])
```
<hr>