---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y-%m-%d-%H-%M-%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',timeStamp,'.html')) })
title : "フィリップス曲線"
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 8
    fig_width: 12
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 
<style>
.main-container {
	max-width: 1200px;
	margin-left: auto;
	margin-right: auto;
}
</style>
```{r,warning=F,error=F,message=F,results='hold',echo=F}
dataTitle <-
  '日本のフィリップス曲線 - 完全失業率と消費者物価指数 - 民主党政権時と第二次安倍政権発足以降の比較 2016年7月分'
dataSource <- '総務省'
notes <- '複数のワードで検索する際は半角スペースで区切ってください'
notes0 <- "表中、-9999はNAを意味します"
Author <- "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
htmlID <- timeStamp
cat(paste("Title :", dataTitle, "\n"))
cat(paste("Raw Data Source :", dataSource, "\n"))
cat(paste("Author :", Author, "\n"))
cat(paste("作成日 :", Sys.time(), "\n"))
cat(paste("特記 :", notes, "\n"))
cat(paste("特記 :", notes0, "\n"))
cat(paste("ID :", htmlID, "\n"))
windowsFonts(Meiryo = windowsFont("Meiryo"))
options(scipen = 999)
```

```{r,warning=F,error=F,message=F,echo=F}
library(ggplot2)
library(RCurl)
script <-
  getURL(
    "https://raw.githubusercontent.com/am-consulting/Rscript/master/laborForceSurveyofJapan.r",
    ssl.verifypeer = FALSE
  )
eval(parse(text = script))
laborforcesurvey <- origData

script <-
  getURL(
    "https://raw.githubusercontent.com/am-consulting/Rscript/master/consumerPriceIndexofJapan.r",
    ssl.verifypeer = FALSE
  )
eval(parse(text = script))
consumerpriceindex <- origData0
```

```{r,warning=F,error=F,message=F,results='hold',echo=F,fig.height=6,fig.width=12}
dateFormat<-'%Y-%m'
mergeData <-
  na.omit(merge(laborforcesurvey[, c(1, 17)], consumerpriceindex[, c(1, 6)], by = "Date"))
dataSet<-mergeData
mainTitle <-
  paste(colnames(dataSet)[2], ' × ', colnames(dataSet)[3])
par(mfrow = c(1, 3),mar = c(5, 5, 5, 1),family = 'Meiryo',oma = c(0, 0, 2, 0))
for (iii in 1:3) {
  dataSet <- mergeData
  switch (
    iii,
    dataSet <- dataSet,
    dataSet <- subset(dataSet, as.Date('2009/9/1') <= dataSet[, 1] & dataSet[, 1] <= as.Date('2012/12/1')),
    dataSet <- subset(dataSet, as.Date('2013/1/1') <= dataSet[, 1])
  )
  tmpSub<-paste0(format(first(dataSet[, 1]), dateFormat), '~', format(last(dataSet[, 1]), dateFormat))
  switch (
    iii,
    subTitle <-tmpSub,
    subTitle <-paste0("民主党政権時:",tmpSub),
    subTitle <-paste0("第二次安倍政権以降:",tmpSub)
  )
  x <- dataSet[, 2]
  y <- dataSet[, 3]
  if(iii==1){  
    resultNLS <- summary(nls(y ~ a * x ^ b, start = list(a = 1, b = 1)))
    a <- resultNLS$coefficients[1]
    b <- resultNLS$coefficients[2]
    z <- a * x ^ b
    yMax <- ceiling(max(y, z))
    yMin <- floor(min(y, z))
    xRange <-range(x)
    yRange <-c(yMin, yMax)
  }  
  plot(
    x,
    y,
    type = 'p',
    col = 'black',
    xlab = colnames(dataSet)[2] ,
    ylab = colnames(dataSet)[3] ,
    panel.first = grid(
      nx = NULL,
      ny = NULL,
      lty = 2,
      equilogs = T
    ) ,
    ylim = if (iii == 1) {yRange},
    xlim = if (iii == 1) {xRange},
    main = subTitle,
    cex.axis = 1,
    cex.lab = 1.4,
    cex.main = 1.4,
    lwd = 1
  )
  abline(lm(y ~ x), col = "red")
  if (iii == 1) {
    par(new = T)
    curve(
      a * x ^ b,
      min(x),
      max(x),
      xlim = xRange,
      ylim = yRange,
      col = "blue"
    )
  }
}
mtext(side = 3,line = 0,outer = T,text = mainTitle,cex = 1.0)
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
cat(paste0('x : ', colnames(dataSet)[2], '\n'))
cat(paste0('y : ', colnames(dataSet)[3]))
resultNLS
```

```{r,warning=F,error=F,message=F,results='hold',echo=F,fig.height=6,fig.width=12}
obj01<-2;obj02<-3
mainTitle <-
  paste(colnames(dataSet)[obj01], ' × ', colnames(dataSet)[obj02])
par(mfrow = c(1, 3),mar = c(5, 5, 5, 1),family = 'Meiryo',oma = c(0, 0, 2, 0))
for (iii in 1:3) {
  dataSet <- mergeData
  switch (
    iii,
    dataSet <- dataSet,
    dataSet <- subset(dataSet, as.Date('2009/9/1') <= dataSet[, 1] & dataSet[, 1] <= as.Date('2012/12/1')),
    dataSet <- subset(dataSet, as.Date('2013/1/1') <= dataSet[, 1])
  )
  tmpSub<-paste0(format(first(dataSet[, 1]), dateFormat), '~', format(last(dataSet[, 1]), dateFormat))
  switch (
    iii,
    subTitle <-tmpSub,
    subTitle <-paste0("民主党政権時:",tmpSub),
    subTitle <-paste0("第二次安倍政権以降:",tmpSub)
  )
  par(mar=c(3,5,5,5),family = 'Meiryo')
  plot(
    dataSet[, 1],
    dataSet[, obj01],
    type = 'l',
    col = 'blue',
    xlab = '' ,
    ylab = '' ,
    panel.first = grid(
      nx = NULL,
      ny = NULL,
      lty = 2,
      equilogs = T
    ) ,
    xaxt = 'n',
    main = subTitle,
    cex.axis = 1,
    cex.lab = 1,
    cex.main = 1.4,
    lwd = 1
  )
  lo <- loess(dataSet[, obj01]~as.numeric(dataSet[, 1]), degree = 2)
  lines(dataSet[, 1] , predict(lo) , col='blue', lwd=2,lty=2)
  par(new=T)
  plot(
    dataSet[,1],
    dataSet[,obj02],
    col='red',
    type='l',
    xlab='' ,
    ylab='' ,
    panel.first=grid(nx=NULL,ny=NULL,lty=2,equilogs=T) ,
    xaxt='n',
    yaxt='n',
    cex.axis=1,cex.lab=1,cex.main=1,
    lwd = 1
  )    
  lo <- loess(dataSet[, obj02]~as.numeric(dataSet[, 1]), degree = 2)
  lines(dataSet[, 1] , predict(lo) , col='red', lwd=2,lty=2)
  axis(4,cex.axis=1,cex.lab=1)
  mtext(colnames(dataSet)[obj01],side=2,line=3.2,cex=1.1)
  mtext(colnames(dataSet)[obj02],side=4,line=3.2,cex=1.1)
  graphics::legend('topleft',col=c('blue','red'),lty=1,legend=c(colnames(dataSet)[obj01],colnames(dataSet)[obj02]),cex=1,bty='n')
  axis.Date(side=1,at=dataSet[,1],format=dateFormat,padj=1,cex.axis=1.0) 
}
mtext(side = 3,line = 0,outer = T,text = mainTitle,cex = 1.0)
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}  
dateRangeS <- rangeNameS <- list()
dateRangeS[[1]] <- as.Date(c('2009/9/1', '2012/12/1'))
dateRangeS[[2]] <- c(as.Date('2013/1/1'), Sys.Date())
rangeNameS[[1]] <- '民主党政権'
rangeNameS[[2]] <- '第二次安倍政権発足以降'
################################################
dataSet <- mergeData
for (iii in 1:length(dateRangeS)) {
  buf <-
    subset(dataSet, dateRangeS[[iii]][1] <= dataSet[, 1] &
        dataSet[, 1] <= dateRangeS[[iii]][2])
  buf$Group <-
    paste0(rangeNameS[[iii]], ':', paste(format(buf[1, 1], dateFormat), '~', format(buf[nrow(buf), 1], dateFormat)))
  buf$Months <- seq(1, nrow(buf))
  if (iii == 1) {
    dataSetS0 <- buf
  } else{
    dataSetS0 <- rbind(dataSetS0, buf)
  }
}
dataSetS <- dataSetS0
attach(dataSetS)
by(dataSetS[, c(2, 3)], Group, summary)
```