---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y%m%d%H%M%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',format(Sys.time(),'%Y%m%d%H%M%S'),'.html')) })

title : '国内総生産'
author: 'アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp'
output: 
  html_document:
    fig_height: 5
    fig_width: 12
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 
<style>
.main-container {
	max-width: 1200px;
	margin-left: auto;
	margin-right: auto;
}
</style>

```{r,warning=F,error=F,message=F,results='hold',echo=F}
dataTitle <- "日本の国内総生産-名目GDP、実質GDP、年率換算、GDPデフレーター"
dataTitle0 <- '2016年4-6月期. 単位:兆円'
dataSource <- "財務省"
notes <- "複数のワードで検索する際は半角スペースで区切ってください"
dataTail <- 0
Author <- "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
BXchartTitle <- '歴代内閣毎の内閣支持率(%)'
htmlID <- timeStamp
cat(paste("Title :", dataTitle, dataTitle0, "\n"))
cat(paste("Raw Data Source :", dataSource, "\n"))
cat(paste("Author :", Author, "\n"))
cat(paste("作成日 :", Sys.time(), "\n"))
cat(paste("特記 :", notes, "\n"))
cat(paste("ID :", htmlID, "\n"))
windowsFonts(Meiryo = windowsFont("Meiryo"))
options(scipen = 999)
```

```{r,warning=F,error=F,message=F,echo=F}
library(RCurl)
library(mFilter)
library(lubridate)
library(rAmCharts)
script <-
  getURL(
    "https://raw.githubusercontent.com/am-consulting/Rscript/master/importGDPofJapan.r",
    ssl.verifypeer = FALSE
  )
eval(parse(text = script))
```

```{r,warning=F,error=F,message=F,echo=F}
colnames(gdp1)[-1] <- colnames(gdp2)[-1] <- colnames(gdp3)[-1] <- colnames(gdp4)[-1] <- colnames(gdp5)[-1] <- colnameDataJ
gdp1Ratio0 <- data.frame(gdp1[, 1, drop = F],  round(gdp1[, -1] / gdp1[, 2] * 100, 2), check.names = F)
gdp2Ratio0 <- data.frame(gdp2[, 1, drop = F],  round(gdp2[, -1] / gdp2[, 2] * 100, 2), check.names = F)
gdp1Ratio <- gdp1Ratio0[,c(1,3,7,9)]
gdp1Ratio <-data.frame(gdp1Ratio,100-rowSums(gdp1Ratio[,-1]))
gdp2Ratio <- gdp2Ratio0[,c(1,3,7,9)]
gdp2Ratio <-data.frame(gdp2Ratio,100-rowSums(gdp2Ratio[,-1]))
colnames(gdp1Ratio)[5] <- colnames(gdp2Ratio)[5] <- 'その他'
```

```{r,warning=F,error=F,message=F,echo=F}
funFilter <- function() {
  tsData <- ts(tmp0[, 2] , frequency = 4 , start = c(year(tmp0[1, 1]), month(tmp0[1, 1])))
  tsDataHPfilter <- hpfilter(tsData)
  tsDataBKfilter <- bkfilter(tsData)
  tsDataCFfilter <- cffilter(tsData , root = T)
  HPTrend <- tsDataHPfilter$trend
  BKTrend <- tsDataBKfilter$trend
  CFTrend <- tsDataCFfilter$trend
  HPCycle <- tsDataHPfilter$cycle
  BKCycle <- tsDataBKfilter$cycle
  CFCycle <- tsDataCFfilter$cycle
  tmp0 <-
    data.frame(tmp0,
      HPTrend,
      BKTrend,
      CFTrend,
      HPCycle,
      BKCycle,
      CFCycle,
      check.names = F)
  colnames(tmp0)[3:8] <-
    c(
      'HP Filter Trend',
      'BK Filter Trend',
      'CF Filter Trend',
      'HP Filter Cycle',
      'BK Filter Cycle',
      'CF Filter Cycle'
    )
  dataSet0 <<- tmp0
}
```

```{r,warning=F,error=F,message=F,echo=F} 
funPlotTimeSeries01 <- function() {
  dataPeriod <-
    paste0(format(dataSet0[1, 1], '%Y-%m'), '~', format(dataSet0[nrow(dataSet0), 1], '%Y-%m'))
  mainTitle <-
    paste0(append, '\n', colnames(dataSet0)[obj01], '. ', dataPeriod)
  maxValue <- max(dataSet0[, obj01], dataSet0[, obj02])
  minValue <- min(dataSet0[, obj01], dataSet0[, obj02])
  par(mar = c(3, 5, 4, 5), family = 'Meiryo')
  plot(
    dataSet0[, 1],
    dataSet0[, obj01],
    type = 'l',
    xlab = '' ,
    ylab = '' ,
    panel.first = grid(
      nx = NULL,
      ny = NULL,
      lty = 2,
      equilogs = T
    ) ,
    xaxt = 'n',
    ylim = c(minValue, maxValue),
    main = paste(mainTitle, '\nSource:', dataSource),
    cex.axis = 1,
    cex.lab = 1,
    cex.main = 1,
    lwd = 1,
    col = lineColor[1]
  )
  lines(dataSet0[, 1], dataSet0[, obj02], col = lineColor[2], lwd = 1)
  par(new = T)
  plot(
    dataSet0[, 1],
    dataSet0[, obj03],
    col = lineColor[3],
    type = 'h',
    xlab = '' ,
    ylab = '' ,
    panel.first = grid(
      nx = NULL,
      ny = NULL,
      lty = 2,
      equilogs = T
    ) ,
    xaxt = 'n',
    yaxt = 'n',
    cex.axis = 1,
    cex.lab = 1,
    cex.main = 1,
    lwd = 1
  )
  axis(4, cex.axis = 1, cex.lab = 1)
  mtext(colnames(dataSet0)[obj01], side = 2, line = 3.2, cex = 1)
  mtext(colnames(dataSet0)[obj03], side = 4, line = 3.2, cex = 1)
  graphics::legend(
    'bottomleft',
    col = lineColor,
    lty = 1,
    legend = c(colnames(dataSet0)[obj01], colnames(dataSet0)[obj02], colnames(dataSet0)[obj03]),
    cex = 1,
    bty = 'n'
  )
  axis.Date(side = 1, at = dataSet0[, 1], format = '%Y-%m', padj = 1, cex.axis = 1.0)
}
```

```{r,warning=F,error=F,message=F,echo=F}
funDataTable <- function(obj,title='',append='') {
  obj[,1] <- format(obj[,1],'%Y-%m')
  DT::datatable(
    obj,
    options = list(
      search.regex = T,
      paging = T,
      autoWidth = F,
      info = T,
      lengthChange = T,
      ordering = T,
      searching = T,
      scrollX = T,
      lengthMenu = list(c(5,-1, 1), c(5, 'All', 1)),
      orderClasses = T,
      order = list(list(0, 'desc')),
      columnDefs = list(
        list(width = '8%', targets = 0)
        # ,
        # list(width = '8%', targets = 1)
        # ,
        # list(width = '8%', targets = ncol(obj)-1)
        )
      ),
    rownames = F,
    caption = paste0(title, append),
    class = 'display compact'
  )
}
```

```{r,warning=F,error=F,message=F,echo=F}
par(mfrow = c(1, 2))
lineColor <- c('black', 'blue', 'red')
obj01 <- 2
obj02 <- 3
obj03 <- 6
tmp0 <- gdp1[, c(1, obj01)]
append <- titleJ[1]
funFilter()
funPlotTimeSeries01()
tmp0 <- gdp2[, c(1, obj01)]
append <- titleJ[2]
funFilter()
funPlotTimeSeries01()
```
<hr>
```{r,warning=F,error=F,message=F,echo=F}
funDataTable(obj=gdp1,title = titleJ[1],append = '(単位:兆円)')
```
<hr>
```{r,warning=F,error=F,message=F,echo=F}
funDataTable(obj=gdp2,title = titleJ[2],append = '(単位:兆円)')
```
<hr>
```{r,warning=F,error=F,message=F,echo=F}
par(mfrow = c(1, 2))
tmp0 <- gdp1[, c(1, obj01)]
tmp0[, 2] <- log(tmp0[, 2])
colnames(tmp0)[2] <- paste0(colnames(tmp0)[2], '(自然対数)')
append <- titleJ[1]
funFilter()
buf0 <- dataSet0
buf0[, -1] <- apply(buf0[, -1], 2, function(x) round(x, 4))
funPlotTimeSeries01()
tmp0 <- gdp2[, c(1, obj01)]
tmp0[, 2] <- log(tmp0[, 2])
colnames(tmp0)[2] <- paste0(colnames(tmp0)[2], '(自然対数)')
append <- titleJ[2]
funFilter()
buf1 <- dataSet0
buf1[, -1] <- apply(buf1[, -1], 2, function(x) round(x, 4))
funPlotTimeSeries01()
```
<hr>
```{r,warning=F,error=F,message=F,echo=F}
funDataTable(obj=buf0,title = titleJ[1],append = '')
```
<hr>
```{r,warning=F,error=F,message=F,echo=F}
funDataTable(obj=buf1,title = titleJ[2],append = '')
```
<hr>
```{r,warning=F,error=F,message=F,echo=F} 
funPlotTimeSeries02 <- function() {
  dataPeriod <-
    paste0(format(dataSet0[1, 1], '%Y-%m'), '~', format(dataSet0[nrow(dataSet0), 1], '%Y-%m'))
  mainTitle <-
    paste0(append, '\n', colnames(dataSet0)[obj01], '. ', dataPeriod)
  par(mar = c(3, 5, 4, 5), family = 'Meiryo')
  plot(
    dataSet0[, 1],
    dataSet0[, obj01],
    type = lineType,
    xlab = colnames(dataSet0)[obj01] ,
    ylab = '' ,
    panel.first = grid(
      nx = NULL,
      ny = NULL,
      lty = 2,
      equilogs = T
    ) ,
    xaxt = 'n',
    main = paste(mainTitle, '\nSource:', dataSource),
    cex.axis = 1,
    cex.lab = 1,
    cex.main = 1.2,
    lwd = 1,
    col = dataSet0$col
  )
  axis.Date(side = 1, at = dataSet0[, 1], format = '%Y-%m', padj = 1, cex.axis = 1.0)
}
```

```{r,warning=F,error=F,message=F,echo=F}
par(mfrow = c(1, 3))
obj01 <- 2
dataSet0 <- gdp3[, c(1, obj01)]
dataSet0$col <- ifelse(dataSet0[, 2] < 0, 'red', 'blue')
append <- titleJ[3]
lineType <- 'h'
funPlotTimeSeries02()
dataSet0 <- gdp4[, c(1, obj01)]
dataSet0$col <- ifelse(dataSet0[, 2] < 0, 'red', 'blue')
append <- titleJ[4]
lineType <- 'h'
funPlotTimeSeries02()
dataSet0 <- gdp5[, c(1, obj01)]
dataSet0$col <- ifelse(dataSet0[, 2] < 0, 'red', 'blue')
append <- titleJ[5]
lineType <- 'l'
funPlotTimeSeries02()
```
<hr>
```{r,warning=F,error=F,message=F,echo=F}
funDataTable(obj = gdp3,
             title = titleJ[3],
             append = '(単位:%)')
```
<hr>
```{r,warning=F,error=F,message=F,echo=F}
funDataTable(obj = gdp4,
             title = titleJ[4],
             append = '(単位:%)')
```
<hr>
```{r,warning=F,error=F,message=F,echo=F}
funDataTable(obj = gdp5,
             title = titleJ[5],
             append = '')
```
<hr>
```{r,warning=F,error=F,message=F,echo=F}
funamBarplot <- function(obj, mainTitle = '') {
  amBarplot(
    x = colnames(obj)[1] ,
    y = colnames(obj)[2:ncol(obj)],
    data = obj,
    horiz = T,
    stack_type = '100',
    legend = T,
    labelRotation = 0,
    main = mainTitle,
    mainColor = "#68838B",
    mainSize = 15,
    creditsPosition = "top-right",
    legendPosition = "bottom"
  )
}
```

```{r,warning=F,error=F,message=F,echo=F,results='asis'}
cat(paste0(titleJ[1], '構成比(%)'))
obj <- gdp1Ratio
obj[, 1] <- format(obj[, 1], '%Y-%m')
obj <- tail(obj, 10)
mainTitle <- ''
funamBarplot(obj, mainTitle)
```
<hr>
```{r,warning=F,error=F,message=F,echo=F,results='asis'}
cat(paste0(titleJ[2], '構成比(%)'))
obj <- gdp2Ratio
obj[, 1] <- format(obj[, 1], '%Y-%m')
obj <- tail(obj, 10)
mainTitle <- ''
funamBarplot(obj, mainTitle)
```