---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y%m%d%H%M%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',timeStamp,'.html')) })
title : "証券売買"
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 8
    fig_width: 12
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 
<style>
.main-container {
	max-width: 1200px;
	margin-left: auto;
	margin-right: auto;
}
</style>

```{r set-options, echo=F, cache=F}
options(width = 1000)
```

```{r,warning=F,error=F,message=F,echo=F,results='hold'}
library(RCurl)
script <-
  getURL(
    "https://raw.githubusercontent.com/am-consulting/Rscript/master/internationalTransactionsInSecurities.r",
    ssl.verifypeer = FALSE
  )
eval(parse(text = script))
colnames(origData)[-1] <- namesJ
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
dataTitle <-  paste0(titleJ,' - ',format(Sys.Date(),'%Y年%m月%d日'))
dataSource <- '財務省'
notes <- '複数のワードで検索する際は半角スペースで区切ってください'
notes0 <- "表中、-9999はNAを意味します"
Author <- "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
htmlID <- timeStamp
cat(paste("Title :", dataTitle, "\n"))
cat(paste("Raw Data Source :", dataSource, "\n"))
cat(paste("Author :", Author, "\n"))
cat(paste("作成日 :", Sys.time(), "\n"))
cat(paste("特記 :", notes, "\n"))
cat(paste("特記 :", notes0, "\n"))
cat(paste("ID :", htmlID, "\n"))
windowsFonts(Meiryo = windowsFont("Meiryo"))
options(scipen = 999)
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
DT::datatable(
  origData[,c(1,2,5,8,13,16,19,24)],
  options = list(
    search.regex = F,
    paging = T,
    autoWidth = F,
    info = T,
    lengthChange = T,
    ordering = T,
    searching = T,
    scrollX = F,
    lengthMenu = list(c(10,-1, 1), c(10, 'All', 1)),
    orderClasses = T,
    order = list(list(0, 'desc')),
    columnDefs = list(list(width = '5%', targets = 0),list(width = '20%', targets = 1))
  ),
  rownames = F,
  caption = paste(dataTitle, '. Source:',dataSource),
  class = 'display compact'
)
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F,fig.height=5,fig.width=12}
for(iii in seq(3,ncol(origData),by=2)){
  par(mfrow=c(1,2),mar = c(10, 5, 2, 2),oma=c(0,0,0,0),family='Meiryo')
  for(ccc in seq(iii,min(iii+1,ncol(origData)))){
    plotData <- origData[,c(1,2,ccc),drop=F]
    plotData <- tail(plotData, 15)
    plotData$color <- "blue"
    plotData[plotData[, 3] < 0, ncol(plotData)] <- "red"
    plotbuf <- 
      barplot(
        plotData[, 3],
        names.arg = plotData[,2],
        las = 3,
        main = colnames(plotData)[3],
        col = plotData$color,
        density = 10,
        ylab = "億円",
        cex.main = 1,
        cex.sub = 1,
        cex.lab = 1,
        cex.names = 1,
        cex.axis = 1
      )
    text(
      plotbuf,
      y = plotData[, 3],
      labels = plotData[, 3],
      srt = 90,
      cex = 1,
      adj = c(-0.1, 0.5),
      col = "black"
    )
  }
  cat('<hr>')
}
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
statData <- origData[,c(1,2,5,8,13,16,19,24)]
cat(paste0('<h4>',head(statData[,2],1),' - ',tail(statData[,2],1),'</h4>'))
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
summary(statData[,-c(1,2)])
```
<hr>