---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',format(Sys.time(),'%Y-%m-%d-%H-%M-%S'),'.html')) })


title: "CIA The World FactBook-Correlation"
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 5
    fig_width: 10
    keep_md: no
    md_extensions: -ascii_identifiers  
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: true
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet">

```{r,warning=F,error=F,message=F,results='hold',echo=F}
dataTitle <- paste0("『ザ･ワールド･ファクトブック』(CIA)に基づく各フィールド毎のスピアマン順位相関係数 データ確認日:",Sys.Date())
dataSource <- "Central Intelligence Agency( https://www.cia.gov/index.html )"
notes <- "各フィールド毎のスピアマン順位相関係数(r)を表示しています。"
notes0 <- "相関係数算出に際して2つの変数が独立であるか否かを確認していません。また因果の有無は確認していません。"
notes1 <- "\"DATE OF INFORMATION\"はフィールド、国・地域ごとに異なります。ソースデータを確認してください。"
Author <- "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
cat(paste('Title :', dataTitle, '\n'))
cat(paste('Raw Data Source :', dataSource, '\n'))
cat(paste('Author :', Author, '\n'))
cat(paste('作成日 :', Sys.time(), '\n'))
cat(paste('特記 :',notes,'\n'))
cat(paste('特記 :',notes0,'\n'))
cat(paste('特記 :',notes1,'\n'))
windowsFonts(Meiryo = windowsFont('Meiryo'))
```

```{r,warning=F,error=F,message=F,echo=F,results='hide'}
library(ggplot2)
library(RColorBrewer)
library(scales)
library(dplyr)
library(qpcR)
library(RCurl)
library(DT)
library(knitr)
script <-
  getURL(
    "https://raw.githubusercontent.com/am-consulting/Rscript/master/importCIAFactBook.r",
    ssl.verifypeer = FALSE
  )
eval(parse(text = script))
```

```{r,warning=F,error=F,message=F,echo=F}
lmTablePearson <- data.frame()
lmTableSpearman <- data.frame()
for (obj1 in 2:ncol(allData)) {
  for (obj2 in 2:ncol(allData)) {
    buf <- na.omit(allData[, c(obj1, obj2, 1), drop = F])
    buf0 <- cor.test(x = buf[, 1],
                     y = buf[, 2],
                     method = 'pearson')
    buf1 <- cor.test(x = buf[, 1],
                     y = buf[, 2],
                     method = 'spearman')
    lmTablePearson[obj1 - 1, obj2 - 1] <- round(buf0$estimate,3)
    lmTableSpearman[obj1 - 1, obj2 - 1] <- round(buf1$estimate,3)
  }
}
colnames(lmTablePearson) <-
  colnames(lmTableSpearman) <- colnames(allData)[-1]
rownames(lmTablePearson) <-
  rownames(lmTableSpearman) <- colnames(allData)[-1]
```

```{r,warning=F,error=F,message=F,echo=F}
theme_set(theme_gray(base_family = "Meiryo"))
invClass <- brewer.pal(10, "Paired")
funBarPlot <- function() {
  cat(paste0('<h2>', colnames(buf0)[2], '</h2>'))
  g1 <- ggplot()
  g1 <-
    g1 + geom_bar(
      data = buf0,
      aes(x = buf0[, 1], y = buf0[, 2]),
      stat = "identity",
      position = "identity",
      fill = invClass,
      alpha = 0.2,
      color = "black"
    )
  g1 <- g1 + coord_flip()
  g1 <-
    g1 + geom_text(
      data = buf0,
      aes(
        x = buf0[, 1],
        y = buf0[, 2] / 2,
        label = comma(buf0[, 2])
      ),
      angle = 0,
      vjust = 0.5,
      hjust = 0,
      size = 4
    )
  g1 <- g1 + scale_y_continuous(labels = comma)
  g1 <- g1 + theme(plot.title = element_text(size = 12))
  g1 <- g1 + theme(axis.title.x = element_text(size = 12))
  g1 <- g1 + theme(axis.title.y = element_text(size = 12))
  g1 <-
    g1 + theme(axis.text.x = element_text(
      size = 12,
      angle = 0,
      hjust = 0.5,
      vjust = 0.5
    ))
  g1 <-
    g1 + theme(axis.text.y = element_text(
      size = 12,
      angle = 0,
      vjust = 0.5
    ))
  g1 <- g1 + ylab('')
  g1 <- g1 + xlab('')
  print(g1)
}
```

```{r,warning=F,error=F,message=F,echo=F}
funDataTable <- function(obj, append = '') {
  DT::datatable(
    obj,
    options = list(
      search.regex = T,
      paging = T,
      autoWidth = F,
      info = T,
      lengthChange = T,
      ordering = T,
      searching = T,
      scrollX = T,
      lengthMenu = list(c(5, -1, 1), c(5, 'All', 1)),
      orderClasses = T,
      order = list(list(1, 'desc')),
      columnDefs = list(list(width = '90%', targets = 0))
    ),
    rownames = F,
    caption = paste0(dataTitle, '. ', append, 'に対する相関係数'),
    class = 'display compact'
  )
}
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
cat('<h1>相関係数(r)-スピアマン順位相関</h1>')
#lmTable <- lmTablePearson
lmTable <- lmTableSpearman
lmDT<-list()
appendTitle<-list()
for (iii in 1:ncol(lmTable)) {
  lmDT[[iii]]  <-
    data.frame(
      Item = rownames(lmTable),
      lmTable[, iii, drop = F],
      row.names = NULL,
      check.names = F
    )
  appendTitle[[iii]]<-colnames(lmDT[[iii]])[2]
  colnames(lmDT[[iii]])[2]<-'r'
}  
```

```{r,warning=F,error=F,message=F,echo=F,include=F}
out = NULL
for (iii in 1:length(lmDT)) {
  knit_expanded <-
    paste0(
      "\n```{r results='asis', echo=FALSE}\n\n",
      "cat(paste0('<h2>',appendTitle[[",
      iii,
      "]],'</h2>'))\n\n",
      "funDataTable(obj = lmDT[[",
      iii,
      "]], append = appendTitle[[",
      iii,
      "]])\n\ncat('<hr>')\n\n```"
    )
  out = c(out, knit_expanded)
}
```
`r paste(knit(text = out), collapse = '\n')`