---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y%m%d%H%M%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-equitySecurities.html')) })
title : "株式関連月次統計情報"
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 6
    fig_width: 10
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 
<style>
.main-container {
	max-width: 1000px;
	margin-left: auto;
	margin-right: auto;
}
</style>


```{r set-options, echo=F, cache=F}
options(width = 1000)
```

```{r warning=F, error=F, message=F, echo=F}
# ―,ソ,噂,欺,圭,構,蚕,十,申,貼,能,表,暴,予,禄,兔
library(RCurl)
rFile <- c(
'importPERPBR.r',
'importAverageYield.r',
'importMarketCapitalization.r',
'importNikkeiMonthly.r')
for(iii in 1:length(rFile)){
if(length(grep('nikkei',rFile[iii],ignore.case = T))==0){  
script <- 
  getURL(paste0('https://raw.githubusercontent.com/am-consulting/Rscript/master/',rFile[iii]),ssl.verifypeer = F)
}else{
script <- 
  getURL(paste0('https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/',rFile[iii]),ssl.verifypeer = F)
}
eval(parse(text = script))
}
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
dataTitle <- paste0('市場別時価総額、株式平均利回り、PER･PBRおよび日経平均株価 - ',format(tail(PERPBR[,1],1),'%Y年%m月分'))
dataSource <- '株式会社日本取引所グループ、株式会社日本経済新聞社'
notes <- '複数のワードで検索する際は半角スペースで区切ってください'
notes0 <- '表中、-9999はNAを意味します'
dataTail <- 0 
Author <- 'アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp'
cat(paste('Title       : ',dataTitle,'\n'))
cat(paste('Data Source : ',dataSource,'\n'))
cat(paste('Author      : ',Author,'\n'))
cat(paste('作 成 日    : ',Sys.time(),'\n'))
cat(paste('特    記    : ',notes,'\n'))
cat(paste('特    記    : ',notes0,'\n'))
windowsFonts(Meiryo=windowsFont("Meiryo"))
options(scipen = 999)
lineColor <- c('blue','red')
```

```{r warning=F, error=F, message=F, echo=F}
fun_plotTimeSeries <- 
  function(obj, objX = 1, objY01 = 2, objY02 = 3, type01 = 'o', type02 = 'o', needylim = 2, dateFormat = '%Y-%m', chartTtpe = 2) {
mainTitle <- paste0(colnames(obj)[objY01],'\n×\n',colnames(obj)[objY02])
maxValue <- max(obj[,objY01],obj[,objY02])
minValue <- min(obj[,objY01],obj[,objY02])
par(mar=c(3,5,6,5),family = 'Meiryo')
plot(
  obj[, objX]  , obj[, objY01],
  type = type01, col = lineColor[1],
  xlab = ''    , ylab = '' ,
  xaxt = 'n'   , ylim = if(needylim == 1){c(minValue, maxValue)},
  main = paste(mainTitle,'\n', paste0(format(range(obj[,objX]), dateFormat),collapse = '~'),'\nSource:',dataSource),
  cex.axis = 1 , cex.lab = 1,   cex.main = 1, lwd = 1
  )
lo <- loess(obj[, objY01] ~ as.numeric(obj[,objX]), degree = 2)
lines(obj[,objX] , predict(lo) , col = lineColor[1], lwd = 1, lty = 2)
panel.first = grid(nx = NULL, ny = NULL, lty = 2, equilogs = T)
if(chartTtpe == 1){
lines(obj[,objX], obj[,objY02], col = lineColor[2], lwd = 1, type = type02)
}else{  
par(new=T)
plot(
  obj[, objX]  , obj[, objY02],
  type = type02, col = lineColor[2],
  xlab = ''    , ylab = '' ,
  xaxt = 'n'   , yaxt = 'n'   , 
  cex.axis = 1 , cex.lab = 1,   cex.main = 1, lwd = 1
  )
panel.first = grid(nx = NULL, ny = NULL, lty = 2, equilogs = T)
axis(4, cex.axis = 1, cex.lab = 1)
mtext(colnames(obj)[objY01], side=2, line=3.2, cex=1)
mtext(colnames(obj)[objY02], side=4, line=3.2, cex=1)
}
lo <- loess(obj[, objY02] ~ as.numeric(obj[,objX]), degree = 2)
lines(obj[,objX] , predict(lo) , col = lineColor[2], lwd = 1, lty = 2)
graphics::legend('topleft',col=lineColor,lty=1,legend=c(colnames(obj)[objY01],colnames(obj)[objY02]),cex=1,bty='n',lwd = 2)
axis.Date(side=1, at=obj[,objX],format=dateFormat,padj=1,cex.axis=1.0) 
# rect part
rectDateL <- as.numeric(as.Date('2009-09-16'))
rectDateR <- as.numeric(as.Date('2012-12-26'))
if(as.numeric(obj[1,objX]) < rectDateR){
rectText <- '民主党政権'
rect(xleft = rectDateL, ybottom = par('usr')[3], 
     xright = rectDateR, ytop = par('usr')[4], col = 'dimgray', density = 10, angle = 45)
text(rectDateL, par('usr')[4], labels = paste0('\n\n',rectText), pos = 4)
# rect part
}
  }
```

```{r warning=F, error=F, message=F, echo=F}
fun_transport <- function(obj){
  buf <- t(tail(obj,1))
  buf <- data.frame(row.names(buf), buf, check.names = F, stringsAsFactors = F, row.names = NULL)
  colnames(buf) <- buf[1,]
  buf <- buf[-1,]
  colnames(buf)[1] <- '項目'
  buf[,-1] <- apply(buf[,-1,drop=F], 2, as.numeric)
  tDF <- buf
  return(tDF)
}
```

***

### PER･PBR

```{r warning=F, error=F, message=F, echo=F}
fun_plotTimeSeries(obj = PERPBR)
knitr::kable(fun_transport(obj = PERPBR),row.names = F)
```

***

### 株式平均利回り

```{r warning=F, error=F, message=F, echo=F}
fun_plotTimeSeries(obj = averageYield, objY02 = 4, chartTtpe = 1, needylim = 1)
averageYield0 <- averageYield
averageYield0[,1] <- format(averageYield0[,1],'%Y-%m')
knitr::kable(fun_transport(obj = averageYield0),row.names = F)
```

***

### 株式時価総額(兆円)

```{r warning=F, error=F, message=F, echo=F}
fun_plotTimeSeries(obj = marketCapitalization, objY02 = 8, chartTtpe = 1, needylim = 1)
knitr::kable(fun_transport(obj =marketCapitalization),row.names = F)
```

***

### 日経平均株価

```{r warning=F, error=F, message=F, echo=F}
nikkeiMonthly0 <- head(nikkeiMonthly,-1)
fun_plotTimeSeries(obj = nikkeiMonthly0, objY02 = 3, chartTtpe = 1, needylim = 1)
nikkeiMonthly0[,1] <- format(nikkeiMonthly0[,1],'%Y-%m')
knitr::kable(fun_transport(obj = nikkeiMonthly0),row.names = F)
```

***

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-3077339-5', 'auto');
  ga('send', 'pageview');

</script>