---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y%m%d%H%M%S');htmlName<-'historyOfLinearRegression';rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',htmlName,'.html')) })

title : 'History Of Linear Regression between CPI and Unemployment Rate'
author: 'アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp'
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output: 
  html_document:
    fig_width: 10
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet">
<script src="http://knowledgevault.saecanet.com/components/JavascriptCode.js"></script>
<style>.main-container {max-width : 1000px;}</style>

```{r set-options, echo=F, cache=F}
options(width = 1000,scipen = 999)
```

```{r warning=F, error=F, message=F, echo=F}
windowsFonts(Meiryo = windowsFont("Meiryo"))
```

```{r warning = F, error = F, message = F, echo = F}
fileName <- 
  'functionList.csv'
baseURL <- 
  'https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/'
functionList <- 
  read.csv(
    file = paste0(baseURL,'csv/',fileName),
    header = F,
    as.is = T)
for(iii in 1:nrow(functionList)){
  script <- 
    RCurl::getURL(paste0(baseURL,functionList[iii,1]),ssl.verifypeer = F)
  eval(parse(text = script))
}
```

```{r warning=F, error=F, message=F, echo=F, results='hold'}
dataTitle <- 
  paste0('消費者物価指数と完全失業率との線形回帰ヒストリカルデータ')
dataSource <- '総務省'
```

***

- `r paste0("タイトル : ", dataTitle)`
- `r paste0("データ出所 : ", dataSource)`

***

```{r warning=F,error=F,message=F,echo=F,results='hide'}
importAMCC <- 
  c('laborForceSurveyofJapan.r','consumerPriceIndexofJapan.r')
for(iii in seq(length(importAMCC))){
  script <- 
    RCurl::getURL(
      url =paste0("https://raw.githubusercontent.com/am-consulting/Rscript/master/",importAMCC[iii]),
      ssl.verifypeer = F)
  eval(parse(text = script))
}
colnames(consumerPriceIndexofJapan) <- 
  sapply(colnames(consumerPriceIndexofJapan),Nippon::zen2han)
colnames(laborforcesurvey) <- 
  sapply(colnames(laborforcesurvey),Nippon::zen2han)
objCol <- 
  c(grep('^労働力人口.+男女計.+',colnames(laborforcesurvey)),
    grep('^完全失業者.+男女計.+',colnames(laborforcesurvey)))
laborforcesurvey$`完全失業率(%):男女計:季節調整値` <-
  laborforcesurvey[,objCol[2]]/laborforcesurvey[,objCol[1]]*100
objCol <-
  grep(':総合$',colnames(consumerPriceIndexofJapan))
mergeData <-
  na.omit(merge(laborforcesurvey[,c(1,ncol(laborforcesurvey))], 
                consumerPriceIndexofJapan[,c(1,objCol)],by = "Date"))
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
fun_rollingLM <- function(objDF = mergeData,rangeN = 12*5){
  resultDF <- data.frame()
  for(rrr in 1:(nrow(objDF)-rangeN+1)){
    obj <- objDF[rrr:(rrr+rangeN-1),]
    x <- obj[,2]
    y <- obj[,3]
    resultLM <- lm(y~x)
    resultDF[rrr,1] <- rrr
    resultDF[rrr,2] <- paste0(format(range(obj[,1]),'%Y-%m'),collapse = '~')
    resultDF[rrr,3] <- resultLM$coefficients[2]
    resultDF[rrr,4] <- confint(resultLM)[2]
    resultDF[rrr,5] <- confint(resultLM)[4]
    resultDF[rrr,6] <- as.character(range(obj[,1])[1])
    resultDF[rrr,7] <- as.character(range(obj[,1])[2])
    resultDF[rrr,8] <- round(summary(resultLM)$adj.r.squared,3)
  }
  colnames(resultDF) <- c('ID','Period','Slope','Lo 95','Hi 95','Date01','Date02','Adjusted r squared')
  return(resultDF)
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
fun_plotRolling <- function(obj,mainTitle){
  ylim <- c(floor(min(obj[,3:5])),ceiling(max(obj[,3:5])))
  par(mar=c(5,4,4,1),family='Meiryo',font.main=1,cex.main=1)
  plot(obj$Slope,type='l',xlab='ID',ylab='',ylim=ylim,col='blue',lwd=2,
       main=mainTitle)
  lines(obj$`Lo 95`,lty=2)
  lines(obj$`Hi 95`,lty=2)
  grid(nx = NULL, ny = NULL, col = "lightgray", lty = "dotted")
  abline(h=0,col='red')
  resultMin <- obj[tail(which.min(obj$Slope),1),]
  resultMax <- obj[tail(which.max(obj$Slope),1),]
  minData <- mergeData[resultMin$Date01<=mergeData[,1] & mergeData[,1]<=resultMin$Date02,]
  maxData <- mergeData[resultMax$Date01<=mergeData[,1] & mergeData[,1]<=resultMax$Date02,]
  returnList <-
      list('minData' = minData,
           'maxData' = maxData)
  return(returnList)
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
fun_plotR2 <- function(obj,mainTitle){
  par(mar=c(5,4,4,1),family='Meiryo',font.main=1,cex.main=1)
  plot(obj$`Adjusted r squared`,type='h',xlab='ID',ylab='',col='blue',lwd=1,
       main=mainTitle)
  grid(nx = NULL, ny = NULL, col = "lightgray", lty = "dotted")
  abline(h=0,col='red')
  resultMin <- obj[tail(which.min(obj$`Adjusted r squared`),1),]
  resultMax <- obj[tail(which.max(obj$`Adjusted r squared`),1),]
  minData <- mergeData[resultMin$Date01<=mergeData[,1] & mergeData[,1]<=resultMin$Date02,]
  maxData <- mergeData[resultMax$Date01<=mergeData[,1] & mergeData[,1]<=resultMax$Date02,]
  returnList <-
      list('minData' = minData,
           'maxData' = maxData)
  return(returnList)
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
fun_lmPlot <- function(dataDF){
  x <- dataDF[,2]
  y <- dataDF[,3]
  resultLM <- lm(y~x)
  dateRange <- 
    paste0(format(range(dataDF[,1]),'%Y-%m'),collapse = ' ~ ')
  par(mar=c(5,5,4,1),family='Meiryo',font.main=1,cex.main=1)
  plot(x,y,type='p',pch=20,xlab=colnames(dataDF)[2],ylab=colnames(dataDF)[3],
       main=paste0(dateRange,'\nAdjusted r squared = ',round(summary(resultLM)$adj.r.squared,3)))
  grid(nx = NULL, ny = NULL, col = "lightgray", lty = "dotted")
  abline(resultLM,col='red')
}
```

```{r warning=F,error=F,message=F,echo=F,results='asis'}
rangeN <- 12*5
mainTitle01 <- 
  paste0(paste0(colnames(mergeData)[2:3],collapse = 'と'),'との線形回帰スロープ')
cat('#### ',mainTitle01,'\n\n')
cat('- 期間:',rangeN,'ヶ月毎\n\n')
resultTable <- 
  fun_rollingLM(objDF = mergeData,rangeN = rangeN)
resultTable[,c(3,4,5)] <-
  apply(resultTable[,c(3,4,5)],2,function(x)round(x,3))
fun_dataTable(obj = resultTable[,c(1,2,3,4,5,8)],dateFormat = 0,orderDirection = 'asc')
cat('\n<hr>\n')
cat('#### ',mainTitle01,'\n\n')
resultData <- 
  fun_plotRolling(obj = resultTable,mainTitle = mainTitle01)
lastData <- 
  mergeData[tail(resultTable$Date01,1)<=mergeData[,1],]
cat('\n<hr>\n')
cat('#### 最大マイナススロープ\n')
fun_lmPlot(dataDF = resultData$minData)
cat('\n<hr>\n')
cat('#### 最大プラススロープ\n')
fun_lmPlot(dataDF = resultData$maxData)
cat('\n<hr>\n')
cat('#### 直近\n')
fun_lmPlot(dataDF = lastData)
mainTitle02 <- 
  paste0(paste0(colnames(mergeData)[2:3],collapse = 'と'),'との線形回帰自由度調整済決定係数')
cat('\n<hr>\n')
cat('#### ',mainTitle02,'\n\n')
resultData <- 
  fun_plotR2(obj = resultTable,mainTitle = mainTitle02)
cat('\n<hr>\n')
cat('#### 最大決定係数\n')
fun_lmPlot(dataDF = resultData$maxData)
cat('\n<hr>\n')
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
fun_preparePlot()
pngFile <-
  paste0(htmlName, "1.png")
png(file = pngFile, width = 1000, height = 600)
##################
Slope <- resultTable$Slope
par(mar=c(5,5,4,1),family='Meiryo',font.main=1,cex.main=1)
hist(Slope,col = '#4169e1',main = mainTitle01)
dev.off()
pngFile <-
  paste0(htmlName, "2.png")
png(file = pngFile, width = 1000, height = 600)
##################
Adjusted_R_Squared <- resultTable$`Adjusted r squared`
par(mar=c(5,5,4,1),family='Meiryo',font.main=1,cex.main=1)
hist(Adjusted_R_Squared,col = '#4169e1',main = mainTitle02)
dev.off()
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
obj <- 
  merge(consumerPriceIndexofJapan,
        laborforcesurvey[,-ncol(laborforcesurvey)],by='Date')
fun_outputMD(tags = '消費者物価指数,失業率',
             objDF = fun_transposeDataFrame(obj = obj,dateFormat = '%Y-%m',tailN = 3),
             htmlName = htmlName,
             image1 = 1,image2 = 1,
             title = dataTitle,
             tableTitle = '直近3ヶ月',
             tableName = '消費者物価指数と労働関連指標')
fun_updateURLcsv()
```

<script>MakeNegative();</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-3077339-5', 'auto');
  ga('send', 'pageview');

</script>
