---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',format(Sys.time(),'%Y-%m-%d-%H-%M-%S'),'.html')) })

title : '週間石油在庫統計'
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 6
    fig_width: 10
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet">
<style>
.main-container {
	max-width: 1000px;
	margin-left: auto;
	margin-right: auto;
}
</style>

```{r,warning=F,error=F,message=F,echo=F}
windowsFonts(Meiryo=windowsFont("Meiryo"))
library(gdata)
library(DT)
options(download.file.method='libcurl')
perl <- gdata:::findPerl('perl')
dataURL <-
  c(
    'http://ir.eia.gov/wpsr/psw09.xls' ,
    'http://ir.eia.gov/wpsr/psw01.xls' , 
    'http://ir.eia.gov/wpsr/psw11.xls'  
  )
for (iii in 1:length(dataURL)) { 
  Sys.sleep(1) #avoid to overload    
  switch (iii,
          objsheet <- 7,
          objsheet <- 2,
          objsheet <- 2
          )
  switch (iii,
          objcolumn <- c(3,6),
          objcolumn <- c(5),
          objcolumn <- c(2:3)
          )
  buf <-
    read.xls(
      dataURL[iii],
      perl = perl,
      check.names = F,
      header = F,
      stringsAsFactors = F,
      sheet = objsheet
    )

  buf <- buf[, c(1, objcolumn)]
  colnames(buf) <-  unlist(buf[3, ])
  buf <- buf[-c(1:3), ]
  if (iii == 1) {
    EIAData <- buf
  } else{
    EIAData <- merge(EIAData, buf, by = 'Date', all = T)
  }
  gc();gc()
}
EIAData[, 1] <-
  as.Date(paste(
    substr(EIAData[, 1], 9, 12),
    '-',
    match(substr(EIAData[, 1], 1, 3), month.abb),
    '-',
    substr(EIAData[, 1], 5, 6),
    sep = ''
  ))
EIAData <- EIAData[order(EIAData[, 1]), ]
EIAData <- data.frame(EIAData[,1,drop = F],apply(EIAData[,-1],2,as.numeric),check.names = F)
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
timeSeries<-0 # 1 or 0
needID<-1
needAtag<-0
needAdd<-1
pp<-1
dataTitle<-paste('週間石油在庫統計',EIAData[1,1],'-',EIAData[nrow(EIAData),1])
dataSource<-'U.S. Energy Information Administration (EIA)'
notes<-'複数のワードで検索する際は半角スペースで区切ってください'
notes0<-'表中、-9999はNAを意味します'
dataTail<-0 
Author<-'アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp'
cat(paste('Title :',dataTitle,'\n'))
cat(paste('Raw Data Source :',dataSource,'\n'))
cat(paste('Author :',Author,'\n'))
cat(paste('作成日 :',Sys.time(),'\n'))
cat(paste('特記 :',notes,'\n'))
cat(paste('特記 :',notes0,'\n'))
```

```{r,warning=F,error=F,message=F,echo=F}
username <- Sys.info()['user']
prepathToCSV <-
paste('C:/Users/', username, '/Desktop/pathToCSV/', sep = '')
setwd(prepathToCSV)
tmp <-
read.csv(
  file = paste0(prepathToCSV, 'pathFolder.csv'),
  header = F,
  as.is = T,
  skip = 0,
  na.strings = c('', 'NA')
)
pathToCSV <- paste('C:/Users/', username, tmp[1, 2], sep = '')
setwd(pathToCSV)
write.table(
  x = EIAData,
  file = 'EIAdata.txt',
  sep = '\t',
  row.names = F,
  append = F,
  quote = F,
  fileEncoding = 'UTF-8'
)
```

```{r,warning=F,error=F,message=F,echo=F}
funDataTable <- function(obj) {
  DT::datatable(
    obj,
    options = list(
      search.regex = T,
      paging = T,
      autoWidth = F,
      info = T,
      lengthChange = T,
      ordering = T,
      searching = T,
      scrollX = T,
      lengthMenu = list(c(10,-1, 1), c(10, 'All', 1)),
      orderClasses = T,
      order = list(list(0, 'desc')),
      columnDefs = list(        list(width = '10%', targets = 0))
      ),
    rownames = F,
    caption = paste(colnames(obj)[2],'.',obj[1,1],'-',obj[nrow(obj),1]),
    class = 'display compact'
  ) 
}
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
for(ccc in 2:ncol(EIAData)){
  plotData<-na.omit(EIAData[,c(1,ccc)])
  plot(
    plotData[,1],
    plotData[,2],
    type = 'l',
    family = 'Meiryo',
    col = 'blue',
    xlab = '' ,
    ylab = '' ,
    panel.first = grid(
      nx = NULL,
      ny = NULL,
      lty = 2,
      equilogs = T
    ) ,
    xaxt = 'n',
    main = paste(colnames(plotData)[2],'\n',plotData[1,1],'-',plotData[nrow(plotData),1]),
    cex.axis = 1,
    cex.lab = 1,
    cex.main = 1,
    lwd = 2
    )
  lo <- loess(plotData[,2]~as.numeric(plotData[,1]))
  lines(plotData[,1] , predict(lo) , col='red', lwd=2)
  axis.Date(side=1,at=plotData[,1],format='%Y-%m-%d', padj=1,cex.axis=1.0)
  cat('<hr>')
}
``` 

```{r,warning=F,error=F,message=F,results='asis',echo=F}
funDataTable(obj=tail(EIAData,20))
``` 

```{r,warning=F,error=F,message=F,results='asis',echo=F}
pathOutput <- paste('C:/Users/', username, '/Desktop/R_Data_Write/', sep = '')
setwd(pathOutput)
htmlFile<-'amcc_EIA.html'
cat('',file=htmlFile,append=F)
cat('週間石油在庫統計前週差\n',file=htmlFile,append=T)
for(ccc in 2:ncol(EIAData)){
  mdTable0<-EIAData[,c(1,ccc)]
  mdTable0<-na.omit(mdTable0)
  mdTable<-data.frame(mdTable0[-1,1,drop=F],diff(mdTable0[,2]),check.names = F)
  colnames(mdTable)<-colnames(mdTable0)
  bufTable<-tail(mdTable,12)
  bufTable[,1]<-format(bufTable[,1],'%Y-%m-%d')
  bufTable[,1]<-paste0('|',bufTable[,1],'|')
  bufTable[,2]<-paste0(bufTable[,2],'|')
  mdTable<- c('|-:|','-:|')
  mdTableHead<-c(
    paste0('|',colnames(bufTable)[1],'|'),   
    paste0(colnames(bufTable)[2],'|')   
  )  
  bufTable0<-rbind(
    mdTableHead,   
    mdTable,
    bufTable
  )
  cat('\n***\n',file=htmlFile,append=T)
  write.table(bufTable0,file=htmlFile,append=T,row.names = F,col.names = F ,quote = F)
}
``` 