---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y%m%d%H%M%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',timeStamp,'.html')) })
title : "オペレーション"
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 8
    fig_width: 12
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 
<style>
.main-container {
	max-width: 1000px;
	margin-left: auto;
	margin-right: auto;
}
</style>


```{r set-options, echo=F, cache=F}
#options(width = 1000)
```

```{r,warning=F,error=F,message=F,echo=F,results='hold'}
dataTitle <- paste0('日本銀行オペレーション 国債買入、国庫短期証券買入・売却、社債等買入、CP等買入、指数連動型上場投資信託受益権買入、不動産投資法人投資口買入オペレーション 2016年9月')
dataSource <- '日本銀行'
notes <- '複数のワードで検索する際は半角スペースで区切ってください'
notes0 <- "表中、-9999はNAを意味します"
Author <- "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
htmlID<-timeStamp
cat(paste("Title :", dataTitle, "\n"))
cat(paste("Raw Data Source :", dataSource, "\n"))
cat(paste("Author :", Author, "\n"))
cat(paste("作成日 :", Sys.time(), "\n"))
cat(paste("特記 :", notes, "\n"))
cat(paste("特記 :", notes0, "\n"))
cat(paste("ID :",htmlID,"\n"))
windowsFonts(Meiryo = windowsFont("Meiryo"))
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
tmp0 <-
  read.table(
    "clipboard",
    header = T,
    sep = "\t",
    stringsAsFactor = F,
    na.strings = c("NA", "-", "－", "… ", ".", ""),
    check.names = F
  )
tmp0[,-1] <- apply(tmp0[,-1], 2, function(x) as.numeric(gsub(',','',x)))
tmp <- tmp0[,c(1,5,8)]
dataSet <- tmp[rowSums(is.na(tmp))!=(ncol(tmp)),]
colnames(dataSet)[2] <- paste0(colnames(dataSet)[2],'(億円)')
colnames(dataSet)[3] <- paste0(colnames(dataSet)[3],'(年%)')
attach(dataSet)

df <- data.frame()
for(iii in 1:length(unique(dataSet$`種  類`))){
  df[iii,1] <- unique(dataSet$`種  類`)[iii]
  buf <- subset(dataSet,dataSet$`種  類`==unique(dataSet$`種  類`)[iii])  
  df[iii,2] <- sum(buf$`落札額(億円)`)
}
colnames(df)<-c('種類','落札額(億円)')
dfSort<-df[sort.list(df$`落札額(億円)`,decreasing = T),]
knitr::kable(dfSort,row.names = F)
```

```{r,warning=F,error=F,message=F,results='hold',echo=T}
by(`落札額(億円)`, `種  類`, sum)
```
<hr>
```{r,warning=F,error=F,message=F,results='hold',echo=T}
by(`落札額(億円)`, `種  類`, summary)
```
<hr>
```{r,warning=F,error=F,message=F,results='hold',echo=T}
by(`平均落札利回(年%)`, `種  類`, summary)
```
<hr>