---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y%m%d%H%M%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',timeStamp,'.html')) })

title : 'IMF Primary Commodity Prices'
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 5
    fig_width: 10
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet">
<style>
.main-container {
	max-width: 1000px;
	margin-left: auto;
	margin-right: auto;
}
</style>


```{r set-options, echo=F, cache=F}
options(width = 1000)
```

```{r,warning=F,error=F,message=F,echo=F}
library(choroplethrAdmin1)
library(DT)
library(lubridate)
library(googleVis)
library(pipeR)
library(RCurl)
library(seasonal)
library(dplyr)
library(plotly)
script <-
  getURL(
    "https://raw.githubusercontent.com/am-consulting/Rscript/master/importIMFPrimaryCommodityPrices.r",
    ssl.verifypeer = FALSE
  )
eval(parse(text = script))
windowsFonts(Meiryo = windowsFont("Meiryo"))
options(scipen = 100)
dateFormat <- '%Y年%m月'
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
dataTitle <- 'IMF Primary Commodity Prices - '
subTitle <- format(tail(origData[,1],1),dateFormat)
dataSource <- 'International Monetary Fund'
notes <- '複数のワードで検索する際は半角スペースで区切ってください'
notes0 <- '表中、-9999はNAを意味します'
Author <- 'アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp'
htmlID <- timeStamp
cat(paste0('Title :', dataTitle, subTitle, '\n'))
cat(paste('Raw Data Source :', dataSource, '\n'))
cat(paste('Author :', Author, '\n'))
cat(paste('作成日 :', Sys.time(), '\n'))
cat(paste('特記 :', notes, '\n'))
cat(paste('特記 :', notes0, '\n'))
cat(paste("ID :", htmlID, "\n"))
```

```{r,warning=F,error=F,message=F,echo=F} 
funPlotTimeSeries <- function() {
  plot(
    dataSet[, 1],
    dataSet[, 2],
    type = seriesType,
    col = dataSet$col,
    xlab = '' ,
    ylab = '' ,
    panel.first = grid(nx = NULL, ny = NULL, lty = 2, equilogs = T) ,
    xaxt = 'n',
    main = mainTitle,
    cex.axis = 1,
    cex.lab = 1,
    cex.main = 1,
    lwd = objlwd
  )
  lo <- loess(dataSet[, 2] ~ as.numeric(dataSet[, 1]), degree = 2)
  lines(dataSet[, 1] , predict(lo) , col = 'red', lwd = 2, lty = 2)
  axis.Date(side = 1, at = dataSet[, 1], format = dateFormat, padj = 1, cex.axis = 1.0)  
}
```

```{r,warning=F,error=F,message=F,echo=F,results='asis'} 
par(  mar = c(3, 3, 3, 1),  family = 'Meiryo',  oma = c(0, 0, 0, 0),  mfrow = c(1, 2))
dateFormat <- '%Y-%m'
iii <- 2
for (iii in 2:ncol(origData)) {
  cat(paste0('<h3>',colnames(origData)[iii],'</h3>'))
  for (sss in 1:2) {
    dataSet0 <- na.omit(origData[, c(1, iii)])
    dataSet <- dataSet0
    seriesType <- 'l'
    objlwd <- 1
    if (sss == 2) {
      # 前月同月比
      dataSet <-
        data.frame(
          Date = tail(dataSet[, 1], nrow(dataSet) - 12),
          round(
            diff(
              as.matrix(dataSet[, -1]),
              lag = 12,
              differences = 1
            ) /
              as.matrix(head(dataSet[, -1], nrow(dataSet) - 12)) * 100,
            2
          ),
          check.names = F
        )
      seriesType <- 'h'
      objlwd <- 1
      dataSet$col <- ifelse(dataSet[, 2] < 0, 'red', 'blue')
      append <- '前年同月比(%)'
    } else{
      dataSet$col <- 'blue'
      append <- '原数値'
    }
    periodData <-
      format(c(head(dataSet[, 1], 1), tail(dataSet[, 1], 1)), dateFormat)
    mainTitle <- paste0(periodData[1], '~', periodData[2], '\n', append)
    funPlotTimeSeries()
  }
  mtext(text = '', outer = T, side = 3)
  cat('<hr>')
}
```