---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y%m%d%H%M%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',timeStamp,'.html')) })
title : "少年犯罪"
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 7
    fig_width: 10
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 
<style>
.main-container {
	max-width: 1000px;
	margin-left: auto;
	margin-right: auto;
}
</style>


```{r set-options, echo=F, cache=F}
options(width = 1000)
```

```{r warning=F, error=F, message=F, echo=F, results='hold'}
dataTitle <- '平成27年中における少年の補導及び保護の概況'
dataSource <- '警察庁'
notes <- '複数のワードで検索する際は半角スペースで区切ってください'
notes0 <- "表中、-9999はNAを意味します"
Author <- "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
htmlID <- timeStamp
cat(paste("Title :", dataTitle, "\n"))
cat(paste("Raw Data Source :", dataSource, "\n"))
cat(paste("Author :", Author, "\n"))
cat(paste("作成日 :", Sys.time(), "\n"))
cat(paste("特記 :", notes, "\n"))
cat(paste("特記 :", notes0, "\n"))
cat(paste("ID :", htmlID, "\n"))
windowsFonts(Meiryo = windowsFont("Meiryo"))
options(scipen = 999)
```

```{r warning=F, error=F, message=F, echo=F, results='hide'}
# http://www.stat.go.jp/data/guide/1.htm
# http://www.stat.go.jp/data/shihyou/index.htm
# http://www.stat.go.jp/data/shihyou/naiyou.htm
library(XLConnect)
library(car)
library(ggplot2)
library(gridExtra)
```

```{r warning=F, error=F, message=F, echo=F, results='hide'}
username <- Sys.info()['user']
pathOutput <- paste0("C:/Users/", username, "/Desktop/socialIndicatorsByPrefecture/")
setwd(pathOutput)
twoByte <- c("０","１","２","３","４","５","６","７","８","９")
oneByte <- c("0","1","2","3","4","5","6","7","8","9")
fileName <- paste0('0000313690', 50:61)
for(iii in 1:length(fileName)){
  fName <- fileName[iii]
  fNameXLS <- paste0(fName, '.xls')
  if(!file.exists(paste0(pathOutput, paste0(fName, '.xls')))) {
    download.file(paste0('http://www.e-stat.go.jp/SG1/estat/Xlsdl.do?sinfid=', fName), fNameXLS, mode = "wb")
  }
  buf0 <- readWorksheetFromFile(paste0(pathOutput, fNameXLS), sheet = 1, check.names = F, header = F)
  tmp <- ''
  for(ccc in 1:ncol(buf0)){
    if(!is.na(buf0[5,ccc])){tmp <- paste0(buf0[5,ccc], buf0[6,ccc])}
    buf0[5,ccc] <- paste0(tmp, buf0[11,ccc], '-', buf0[12,ccc])
  }
  buf1 <- buf0[,grep('\\(', buf0[5,]),drop=F]
  colnames(buf1) <- buf1[5,]
  for(sss in 1:length(twoByte)){
    colnames(buf1) <- gsub(pattern=twoByte[sss], replacement=oneByte[sss], x=colnames(buf1))
  }
  buf2 <- data.frame(buf0[,1:2], buf1, check.names = F, stringsAsFactors = F)
  buf2[,2] <- gsub(' ', '', buf2[,2]) 
  buf3 <- buf2[-(1:(which(buf2[,2]=="全国")-1)),,drop = F]
  buf3[,-(1:2)] <- apply(buf3[,-(1:2), drop = F], 2, function(x) as.numeric(gsub(',', '', x)))
  buf4 <- buf3[1:which(buf3[,1]==47),,drop=F]
  colnames(buf4)[1:2] <- c('ID', '都道府県')
  colnames(buf4) <- gsub('・', '･', gsub('］', ']', gsub('［', '[', gsub(' ', '', gsub('　', '', colnames(buf4))))))
  buf4[,1] <- as.numeric(buf4[,1])
  assign(paste0('JapanData', iii), buf4)
  if(iii==1){allData <- buf4}else{allData <- merge(allData, buf4, all = T, ID = ID)}
}
colnames(allData)
idName <- allData[,1:2]
title <- c(
'社会生活統計指標-都道府県の指標-2016-基礎データ-人口世帯_出所-総務省',
'社会生活統計指標-都道府県の指標-2016-基礎データ-自然環境_出所-総務省',
'社会生活統計指標-都道府県の指標-2016-基礎データ-経済基盤_出所-総務省',
'社会生活統計指標-都道府県の指標-2016-基礎データ-行政基盤_出所-総務省',
'社会生活統計指標-都道府県の指標-2016-基礎データ-教育_出所-総務省',
'社会生活統計指標-都道府県の指標-2016-基礎データ-労働_出所-総務省',
'社会生活統計指標-都道府県の指標-2016-基礎データ-文化・スポーツ_出所-総務省',
'社会生活統計指標-都道府県の指標-2016-基礎データ-居住_出所-総務省',
'社会生活統計指標-都道府県の指標-2016-基礎データ-健康・医療_出所-総務省',
'社会生活統計指標-都道府県の指標-2016-基礎データ-福祉・社会保障_出所-総務省',
'社会生活統計指標-都道府県の指標-2016-基礎データ-安全_出所-総務省',
'社会生活統計指標-都道府県の指標-2016-基礎データ-家計_出所-総務省'
)
```

```{r warning=F, error=F, message=F, echo=F, results='hide'}
tmp <-
  read.table(
    'clipboard',
    header = T,
    sep = '\t',
    stringsAsFactor = F,
    na.strings = c('na', '', '-', 'NA'),
    check.names = F
  )
# tmp <- data.frame(ID = seq(1, nrow(tmp)), tmp, check.names = F, stringsAsFactors = F)
tmp0 <- grep('県',tmp[,1])
tmp[-tmp0,1] <- paste0(tmp[-tmp0,1],'県')
tmp[grep('東京'    ,tmp[,1]),1] <- '東京都'
tmp[grep('北海道'  ,tmp[,1]),1] <- '北海道'
tmp[grep('\\b京都' ,tmp[,1]),1] <- '京都府'
tmp[grep('大阪'    ,tmp[,1]),1] <- '大阪府'
colnames(tmp) <- gsub('・', '･', 
                      gsub('］', ']', 
                           gsub('［', '[', 
                                gsub(' ', '', 
                                     gsub('　', '', 
                                          gsub('（', '(', 
                                               gsub('）', ')', 
                                                    gsub('％', '%', 
                                                         gsub('／', '/', 
                                                              gsub('\n','',colnames(tmp)))))))))))
for(sss in 1:length(twoByte)){
  colnames(tmp) <- gsub(pattern=twoByte[sss], replacement=oneByte[sss], x=colnames(tmp))
}
twoByte <- c("Ａ","Ｂ","Ｃ","Ｄ","Ｅ","Ｆ","Ｇ","Ｈ","Ｉ","Ｊ","Ｋ","Ｌ",
             "Ｍ","Ｎ","Ｏ","Ｐ","Ｑ","Ｒ","Ｓ","Ｔ","Ｕ","Ｖ","Ｗ","Ｘ","Ｙ","Ｚ")
oneByte <- LETTERS
for(sss in 1:length(twoByte)){
  colnames(tmp) <- gsub(pattern=twoByte[sss], replacement=oneByte[sss], x=colnames(tmp))
}
tmp <- merge(idName, tmp, by='都道府県', all = F)
tmp <- tmp[,c(2,1,3)]
colnames(tmp)
# 建設総合統計の様に都道府県の並びが都道府県番号順でない場合があるので注意。
# 都道府県番号 http://www.mhlw.go.jp/topics/2007/07/dl/tp0727-1d.pdf
```

```{r warning=F, error=F, message=F, echo=F}
# 都度作成
needMergedata <- 1
if(needMergedata == 1){
  mergeData <- merge(allData[,c(1:2,3),drop=F], tmp, by = c('ID', '都道府県'))
  mergeData$buf0000 <- round(mergeData[,3]/mergeData[,4])
  colnames(mergeData)[5] <- paste0(colnames(mergeData)[3],'/',colnames(mergeData)[4])
  tmp <- mergeData[,c(1:2,5)]
}
# 都度作成
```

```{r warning=F, error=F, message=F, echo=F}
funGroup <- function(dS){
dS$Group01 <- 
  ifelse(as.numeric(dS$ID) <= 7, '北海道･東北地方',
  ifelse(as.numeric(dS$ID) <= 14,'関東地方',
  ifelse(as.numeric(dS$ID) <= 23,'中部地方',
  ifelse(as.numeric(dS$ID) <= 30,'関西地方',
  ifelse(as.numeric(dS$ID) <= 35,'中国地方',
  ifelse(as.numeric(dS$ID) <= 39,'四国地方','九州･沖縄地方'))))))
dS$Group02 <- 
  ifelse(as.numeric(dS$ID) <= 14,'東日本','西日本')
dS$Group03 <- 
  ifelse(as.numeric(dS$ID) <= 14,'東日本',
  ifelse(as.numeric(dS$ID) <= 24,'中日本','西日本'))
dS$Group04 <- 
  ifelse(as.numeric(dS$ID) <= 1, '北海道',
  ifelse(as.numeric(dS$ID) <= 7, '東北地方',
  ifelse(16 <= as.numeric(dS$ID) & as.numeric(dS$ID) <= 18, '北陸地方',
  ifelse(8  <= as.numeric(dS$ID) & as.numeric(dS$ID) <= 15, '関東甲信越地方',
  ifelse(19 <= as.numeric(dS$ID) & as.numeric(dS$ID) <= 20, '関東甲信越地方',
  ifelse(21 <= as.numeric(dS$ID) & as.numeric(dS$ID) <= 24, '東海地方',
  ifelse(as.numeric(dS$ID) <= 30,'近畿地方',
  ifelse(as.numeric(dS$ID) <= 35,'中国地方',
  ifelse(as.numeric(dS$ID) <= 39,'四国地方','九州･沖縄地方')))))))))
colnames(dS)
return(dS)
}
```

```{r warning=F, error=F, message=F, echo=F}
fun_plot01 <- function(obj, objX, objY, group){
g1 <- ggplot(obj, aes(obj[,objX],obj[,objY]))
g1 <- g1 + geom_point(aes(colour = group),size=4) 
g1 <- g1 + theme(legend.position = "top")
g1 <- g1 + theme(legend.title = element_blank())
g1 <- g1 + xlab(colnames(obj)[objX]) + ylab(colnames(obj)[objY])
g1 <- g1 + geom_smooth(method = "lm", se = T)
g2 <- ggplot(obj, aes(obj[,objX],obj[,objY]))
g2 <- g2 + geom_text(label=obj[,2])
g2 <- g2 + xlab(colnames(obj)[objX]) + ylab(colnames(obj)[objY])
g2 <- g2 + geom_smooth(method = "lm", se = T)
grid.arrange(g1, g2, ncol = 1)
}
```

```{r warning=F, error=F, message=F, echo=F}
funDataTable <- function(obj, width01, width02, order01) {
DT::datatable(
  obj,
  options = list(
    search.regex = F,
    paging = T,
    autoWidth = F,
    info = T,
    lengthChange = T,
    ordering = T,
    searching = T,
    scrollX = T,
    lengthMenu = list(c(10, -1, 1), c('10', 'All', '1')),
    orderClasses = T,
    order = list(list(0, order01)),
    columnDefs = list(list(width = width01, targets = 0), list(width = width02, targets = 1))
    ),
  rownames = F,
  caption = paste(dataTitle,'. Source:' ,dataSource),
  class = 'display compact',
  escape = F, # or escape = 'v1'(特定のcolumn) テーブル内でhtmlマークアップする場合に必須
  filter = 'bottom'
)
}
```

```{r warning=F, error=F, message=F, echo=F}
data <- dataName <- list()
funstripChart <- function(sss){
uniqBuf <- dataset[,paste0('Group0',sss)]    
uniqN <- unique(uniqBuf)  
for(iii in 1:length(uniqN)){
  buf <- dataset[which(uniqBuf == uniqN[iii]), c(2,3)]
  data[[iii]] <- buf[,2]
  dataName[[iii]] <- buf[,1]
}
par(mar=c(3,8,3,1),family='Meiryo')
stripchart(
  data,
  # main = paste(dataTitle,'\nSource:' ,dataSource),
  main = colnames(dataset)[3],
  xlab = "",
  ylab = "",
  method = "stack",
  col = seq(1, length(uniqN)),
  pch = 16,
  vertical = F,
  log = '',
  yaxt = 'n'
)
axis(2, at=seq(1, length(uniqN)), labels = uniqN, las=2)
panel.first = grid(nx = NULL, ny = NULL, lty = 2, equilogs = T) 
for(iii in 1:length(uniqN)){
  text(data[[iii]], iii+0.1, labels = dataName[[iii]], srt = 90, adj = 0, cex = 0.9)
}
}
```
<hr>
```{r warning=F, error=F, message=F, echo=F, results='asis'}
dataset <- funGroup(dS = tmp)
dataset <- dataset[order(dataset$ID, decreasing = T),]
funstripChart(sss = 1)
cat('<hr>')
funstripChart(sss = 2)
cat('<hr>')
funstripChart(sss = 3)
cat('<hr>')
funstripChart(sss = 4)
```
<hr>
```{r warning=F, error=F, message=F, echo=F}
funDataTable(obj = dataset, width01 = '3%', width02 = '10%', order01 = 'asc')
```
<hr>
```{r warning=F, error=F, message=F, echo=F}
for(iii in 3:(ncol(dataset)-4)){
  print(summary(dataset[,iii,drop=F]))
  cat(paste0('Max / Min = ', round(max(dataset[,iii])/min(dataset[,iii]), 1)))  
  cat('\n\n')
}  
```

```{r warning=F, error=F, message=F, echo=F, results='asis'}
a <- 68
b <- 3
objY <- 4
compareData <- data.frame(allData[,1:2], allData[,a]/allData[,b], check.names = F, stringsAsFactors = F)
colnames(compareData)[3] <- paste0(colnames(allData)[a],"/",colnames(allData)[b])
```

```{r warning=F, error=F, message=F, echo=F, results='asis'}
needCorrplot <- 1
if(needCorrplot == 1){ 
cat('<hr>
<h4>社会生活統計指標(出所:総務書)との相関<h4><br>
1. 擬似相関の検討は行っていません。<br>
2. 因果関係の検討は行っていません。<br>
3. 社会生活統計指標の掲載年度に注意して下さい。<br><br><br>')
dataSet <- merge(compareData, dataset, by = c('ID', '都道府県'))
objX <- 3
for(sss in objY){
  fun_plot01(obj = dataSet, objX = objX, objY = sss, group = dataSet$Group01)
  cat('<hr>')
}
}
```