---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',format(Sys.time(),'%Y-%m-%d-%H-%M-%S'),'.html')) })

title : '株式売買状況'
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    keep_md: no
    md_extensions: -ascii_identifiers
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet">
<style>
body{font-family:'Hiragino Kaku Gothic Pro','Meiryo UI',Verdana,sans-serif;}
.main-container {
	max-width: 1200px;
	margin-left: auto;
	margin-right: auto;
}
</style>

```{r,warning=F,error=F,message=F,echo=F,results='hold'}
dataTitle <- '投資部門別株式売買状況 二市場一･二部等 2016年8月第1週分'
dataSource <- '株式会社日本取引所グループ'
notes <- '複数のワードで検索する際は半角スペースで区切ってください'
notes0 <- "表中、-9999はNAを意味します"
Author <- "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
cat(paste("Title :", dataTitle, "\n"))
cat(paste("Raw Data Source :", dataSource, "\n"))
cat(paste("Author :", Author, "\n"))
cat(paste("作成日 :", Sys.time(), "\n"))
cat(paste("特記 :", notes, "\n"))
cat(paste("特記 :", notes0, "\n"))
windowsFonts(Meiryo = windowsFont("Meiryo"))
```

```{r,warning=F,error=F,message=F,echo=F}
library(zoo)
#library(lubridate)
#library(scales)
# library(reshape)
library(DT)
```

```{r,warning=F,error=F,message=F,echo=F}
options(digits=22) 
tmp0 <-
  read.table(
    'clipboard',
    header = T,
    sep = '\t',
    stringsAsFactor = F,
    na.strings = c('na', '', '-'),
    check.names = F
  )
tmp <- tmp0
```

```{r,warning=F,error=F,message=F,echo=F,fig.height=4,fig.width=12,results='asis'}
dataSet <- list()
obj <- c(9, 15, 18, 42)
for (iii in 1:length(obj)) {
  dataSet[[iii]] <-
    data.frame(tmp[, 1], tmp[, obj[iii]], tmp[, obj[iii] + 1], round(tmp[, obj[iii] + 1] - tmp[, obj[iii]], 12), check.names = F)
  colnames(dataSet[[iii]]) <-
    c('Week', colnames(tmp)[c(obj[iii], obj[iii] + 1)], '差引き(買-売)')
  par(mfrow = c(1, 3), mar = c(10, 3, 3, 3))
  for (ppp in 2:4) {
    buf <- tail(dataSet[[iii]][, c(1, ppp)],16)
    plot(
      buf[, 2],
      type = ifelse(ppp == 4, 'h', 'o'),
      family = 'Meiryo',
      col = 'blue',
      xlab = '' ,
      ylab = '' ,
      panel.first = grid(
        nx = NULL,
        ny = NULL,
        lty = 2,
        equilogs = T
      ) ,
      xaxt = 'n',
      main = paste0(colnames(buf)[2], '(兆円)'),
      cex.axis = 1.3,
      cex.lab = 1.3,
      cex.main = 2,
      lwd = 1
    )
    lo <- loess(buf[, 2] ~ index(buf))
    lines(
      index(buf) ,
      predict(lo) ,
      col = 'red',
      lwd = 2,
      lty = 2
    )
    axis(
      side = 1,
      at = index(buf),
      labels = buf[, 1],
      las = 2,
      cex.axis = 1.3
    )
  }
cat('<hr>')
}
```

```{r,warning=F,error=F,message=F,echo=F}
funDataTable <- function(obj, append = '') {
  DT::datatable(
    obj,
    options = list(
      search.regex = F,
      paging = F,
      autoWidth = F,
      info = F,
      lengthChange = F,
      ordering = F,
      searching = F,
      scrollX = T,
      orderClasses = T
    ),
    rownames = F,
    caption = paste(dataTitle, '-', dataSource, '-単位:兆円', append),
    class = 'display compact'
  )
}  
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
appendTitle<-''
funDataTable(obj = tail(dataSet[[1]],8), append = appendTitle)
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
appendTitle<-''
funDataTable(obj = tail(dataSet[[2]],8), append = appendTitle)
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
appendTitle<-''
funDataTable(obj = tail(dataSet[[3]],8), append = appendTitle)
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
appendTitle<-''
funDataTable(obj = tail(dataSet[[4]],8), append = appendTitle)
```
<hr>