---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',format(Sys.time(),'%Y-%m-%d-%H-%M-%S'),'.html')) })

title : '景気ウォッチャー調査'
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 10
    fig_width: 10
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet">
<style>
.main-container {
	max-width: 1380px;
	margin-left: auto;
	margin-right: auto;
}
</style>

```{r,warning=F,error=F,message=F,echo=F}
library(DT)
library(lubridate)
library(googleVis)
library(dplyr)
library(rAmCharts)
windowsFonts(Meiryo=windowsFont("Meiryo"))
options(scipen=100)
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
dataTitle<-'景気ウォッチャー調査 全国の分野･業種別DIの推移-景気の先行き判断(方向性) 2016年8月'
dataSource<-'内閣府'
notes<-'複数のワードで検索する際は半角スペースで区切ってください'
notes0<-'表中、-9999はNAを意味します'
dataTail<-0 
Author<-'アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp'
htmlID<-format(Sys.time(),'%Y-%m-%d-%H-%M-%S')
cat(paste('Title :',dataTitle,'\n'))
cat(paste('Raw Data Source :',dataSource,'\n'))
cat(paste('Author :',Author,'\n'))
cat(paste('作成日 :',Sys.time(),'\n'))
cat(paste('特記 :',notes,'\n'))
cat(paste('特記 :',notes0,'\n'))
cat(paste("ID :",htmlID,"\n"))
```

```{r,warning=F,error=F,message=F,echo=F,results='hide'}
tmp <-
  read.table(
  'clipboard',
  header = T,
  sep = '\t',
  stringsAsFactor = F,
  na.strings = c('na', '', '-'),
  check.names = F
)
dataSet <- tmp
dataSet[,-1] <- apply(dataSet[,-1],2,as.numeric)
dataSet[,1] <- as.Date(dataSet[,1])
dateFormat <- '%Y-%m'
if (1 < length(unique(day(dataSet[, 1])))) {
  dateFormat <- '%Y-%m-%d'
}
if (1 == length(unique(month(dataSet[, 1])))) {
  dateFormat <- '%Y'
}
colnames(dataSet)
# 前月比  
dataSet01P<-data.frame(
  Date=dataSet[-1,1],  
  round(diff(as.matrix(dataSet[,-1]),lag = 1,differences = 1)/as.matrix(dataSet[-nrow(dataSet),-1])*100,2),
  check.names = F
)
# 前月差  
dataSet01D<-data.frame(
  Date=dataSet[-1,1],  
  diff(as.matrix(dataSet[,-1]),lag = 1,differences = 1),
  check.names = F
)
# 前月同月比
if(12<nrow(dataSet)){
dataSet12P<-data.frame(
  Date=tail(dataSet[,1],nrow(dataSet)-12),  
  round(diff(as.matrix(dataSet[,-1]),lag = 12,differences = 1)/as.matrix(head(dataSet[,-1],nrow(dataSet)-12))*100,2),
  check.names = F
)
}else{
dataSet12P<-dataSet  
}
colnames(dataSet01P)<-colnames(dataSet01D)<-colnames(dataSet12P)<-colnames(dataSet)
```

```{r,warning=F,error=F,message=F,echo=F}
funTimeSeries<-function(dataTS,lineType,rowN,bigTitle){
cat(paste0('<h3>',bigTitle,'</h3>'))  
par(mfrow=c(ceiling((ncol(dataTS)-1)/rowN),rowN),mar=c(3,3,3,2))
par(mfrow=c(ceiling(plotBorder/rowN),rowN),mar=c(3,3,3,2))
for(ccc in 2:ncol(dataTS)){ 
  tmp0<-na.omit(dataTS[,c(1,ccc)])
  plot(
    tmp0[,1],
    tmp0[,2],
    type=lineType,
    col='blue',
    family='Meiryo' ,
    xlab='' ,
    ylab='' ,
    panel.first=grid(nx=NULL,ny=NULL,lty=2,equilogs=T) ,
    xaxt='n',
    main = paste(colnames(tmp0)[2],'\n',format(tmp0[1,1],dateFormat),'-',format(tmp0[nrow(tmp0),1],dateFormat)),
    cex.axis=1.2,cex.lab=1,cex.main=1.5
  )
  lo <- loess(tmp0[, 2]~as.numeric(tmp0[, 1]))
  lines(tmp0[, 1] , predict(lo) , col='red', lwd=1)  
  axis.Date(side=1,at=tmp0[,1],format=dateFormat,padj=0.0,cex.axis=1.2)
}
}
```

```{r,warning=F,error=F,message=F,echo=F}
funDataTable <- function(obj,dataTitle='',append='') {
  DT::datatable(
    obj,
    options = list(
      search.regex = T,
      paging = T,
      autoWidth = F,
      info = T,
      lengthChange = T,
      ordering = T,
      searching = T,
      scrollX = T,
      lengthMenu = list(c(20,-1, 1), c(20, 'All', 1)),
      orderClasses = T,
      order = list(list(0, 'asc')),
      columnDefs = list(
        list(width = '5%' , targets = 0),
        list(width = '30%', targets = 1)
        )
      ),
    rownames = F,
    caption = paste(dataTitle, append),
    class = 'display compact'
  )
}

fungvisTable <- function(obj) {
  PopTable <- gvisTable(      obj, 
    options = list(width = 2000, height = 'automatic',  page = 'enable' ,  pageSize=30)
  )
  plot(PopTable,tag='chart')
}  
```

```{r,warning=F,error=F,message=F,echo=F} 
funPlotBoxplotAmcharts <- function(obj, bigTitle = '') {
  cat(paste0('<b>', bigTitle, '</b>'))
  amBoxplot(obj[,-1], horiz = T)
}
```

```{r,warning=F,error=F,message=F,results='asis',echo=F} 
dateRange<-paste0(format(first(dataSet[,1]),dateFormat),'~',format(last(dataSet[,1]),dateFormat))
funPlotBoxplotAmcharts(obj = dataSet,bigTitle = paste(dataTitle,dateRange,'. Powered By https://www.amcharts.com/'))
```
<hr>  
```{r,warning=F,error=F,message=F,results='asis',echo=F}
plotData<-list()
plotBorder<-7
plotChunk01<-1
plotChunk02<-1
tableChunk01<-1
tableChunk02<-1
buf_dataSet<-dataSet
chunck01Append<-'原系列'
chunck02Append<-'前月比(%)'
dataSet2<-dataSet01P
tableRange<-5
```

```{r,warning=F,error=F,message=F,results='asis',echo=F,fig.height=10,fig.width=14}
if(plotChunk01==1){
for(ppp in 1:ceiling((ncol(dataSet)-1)/plotBorder)){
  columnS<-(2+plotBorder*(ppp-1))
  columnE<-(min(1+plotBorder*ppp,ncol(dataSet)))
  plotData[[ppp]]<-dataSet[,c(1,columnS:columnE)]
  colnames(plotData[[ppp]])<-colnames(dataSet)[c(1,columnS:columnE)]
  funTimeSeries(dataTS=plotData[[ppp]] ,lineType='l', rowN=2 , bigTitle=paste0(dataTitle,'-',chunck01Append))
}
}  
```

```{r,warning=F,error=F,message=F,results='asis',echo=F,fig.height=10,fig.width=14}
if(plotChunk02==1){
dataSet<-dataSet2  
for(ppp in 1:ceiling((ncol(dataSet)-1)/plotBorder)){
  columnS<-(2+plotBorder*(ppp-1))
  columnE<-(min(1+plotBorder*ppp,ncol(dataSet)))
  plotData[[ppp]]<-dataSet[,c(1,columnS:columnE)]
  colnames(plotData[[ppp]])<-colnames(dataSet)[c(1,columnS:columnE)]
  funTimeSeries(dataTS=plotData[[ppp]] ,lineType='h', rowN=2 , bigTitle=paste0(dataTitle,'-',chunck02Append))
}
dataSet<-buf_dataSet
}  
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
funTableReshape<-function(obj){
buf<-tail(obj,tableRange)
buf[,1]<-format(buf[,1],dateFormat)
buf0<-t(buf)
buf0<-data.frame(row.names(buf0),buf0,check.names = F,row.names = NULL,stringsAsFactors = F)
colnames(buf0)<- unlist(buf0[1,])
buf0<-buf0[-1,]
buf0<-data.frame(ID=seq(1,nrow(buf0)),buf0,check.names = F)
buf0[,-c(1:2)]<-apply(buf0[,-c(1:2),drop=F],2,as.numeric)
colnames(buf0)[2]<-'項目'
if(length(grep("報告省令レート",dataTitle))!=0){
  buf0<-buf0[c(1,2,3,5,6,7,14,35,45,53,62),]
  buf0[,1]<-seq(1,nrow(buf0))
}
dataSetDT<<-buf0
}
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
if(tableChunk01==1){
funTableReshape(obj=dataSet)
appendTitle<- chunck01Append
funDataTable(obj = dataSetDT, append = paste0(dataTitle,'-',appendTitle))
#cat(paste0('<b>',dataTitle,'-',appendTitle,'</b>'))  
#fungvisTable(obj = dataSetDT)
}
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
if(tableChunk02==1){
dataSet<-dataSet2
funTableReshape(obj=dataSet)
dataSet<-buf_dataSet
appendTitle<-chunck02Append
funDataTable(obj = dataSetDT, append = paste0(dataTitle,'-',appendTitle))
#DT:datatableの下にコードがあるとテーブルが表示されない
#cat(paste0('<b>',dataTitle,'-',appendTitle,'</b>'))
#fungvisTable(obj = dataSetDT)
}
```
<hr>
```{r,warning=F,error=F,message=F,results='hold',echo=F}
summaryObj <- c(2, 3, 4, 5, 6, 7, 8)
dateRangeS <- rangeNameS <- list()
dateRangeS[[1]] <- as.Date(c('2009/9/1', '2012/12/1'))
dateRangeS[[2]] <- c(as.Date('2013/1/1'), Sys.Date())
rangeNameS[[1]] <- '民主党政権'
rangeNameS[[2]] <- '第二次安倍政権発足以降'
################################################
for (iii in 1:length(dateRangeS)) {
  buf <-
    subset(dataSet, dateRangeS[[iii]][1] <= dataSet[, 1] &
             dataSet[, 1] <= dateRangeS[[iii]][2])
  buf$Group <-
    paste0(rangeNameS[[iii]], ':', paste(format(buf[1, 1], dateFormat), '~', format(buf[nrow(buf), 1], dateFormat)))
  buf$Months <- seq(1, nrow(buf))
  if (iii == 1) {
    dataSetS0 <- buf
  } else{
    dataSetS0 <- rbind(dataSetS0, buf)
  }
}
dataSetS <- dataSetS0
attach(dataSetS)
by(dataSetS[, summaryObj], Group, summary)
```