---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y%m%d%H%M%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',timeStamp,'.html')) })

title : '建設労働'
author: 'アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp'
output: 
  html_document:
    fig_height: 6
    fig_width: 12
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 
<style>
.main-container {
	max-width: 1000px;
	margin-left: auto;
	margin-right: auto;
}
</style>


```{r set-options, echo=F, cache=F}
options(width = 1000)
windowsFonts(Meiryo = windowsFont("Meiryo"))
options(scipen = 999)
```

```{r,warning=F,error=F,message=F,echo=F}
loadTMP <- 1
dataTail <- 12 * 200 
```

```{r,warning=F,error=F,message=F,echo=F}
library(lubridate)
library(ggplot2)
library(scales)
library(reshape)
library(RCurl)
library(rAmCharts)
library(dplyr)
library(qpcR)
library(Nippon)
script <-
  getURL(
    "https://raw.githubusercontent.com/am-consulting/Rscript/master/Rscript_HighestAuthority.r",
    ssl.verifypeer = FALSE
  )
eval(parse(text = script))
highestAuthority()
```

```{r,warning=F,error=F,message=F,echo=F}
iii <- 1
highestData <- switch (iii,
                       get(titleAbb[1]),
                       get(titleAbb[2]),
                       get(titleAbb[3]),
                       get(titleAbb[4]))

FUN <- function(x) {
  highestData[which(highestData[1] <= x &
                      highestData[2] >= x, arr.ind = F), 3]
}
```

```{r,warning=F,error=F,message=F,echo=F}
if(loadTMP==1){
tmp <-
  read.table(
    "clipboard",
    header = T,
    sep = "\t",
    stringsAsFactor = F,
    na.strings = c("na", "", "-", '* '),
    check.names = F
  )
tmp <- tmp[order(tmp[,1],decreasing = F),]
colnames(tmp) <- sapply(colnames(tmp), function(x) iconv(x, to="utf8", from="cp932"))
colnames(tmp) <- sapply(colnames(tmp),zen2han)
}
```

```{r,warning=F,error=F,message=F,echo=F}
if(loadTMP==2){
library(RCurl)
script <-
  getURL(
    "https://raw.githubusercontent.com/am-consulting/Rscript/master/importMarketCapitalization.r",
    ssl.verifypeer = FALSE
  )
eval(parse(text = script))
tmp <- MarketCapitalization[,1:2]
}
```

```{r,warning=F,error=F,message=F,echo=F}
if(loadTMP==3){
library(RCurl)
script <-
  getURL(
    "https://raw.githubusercontent.com/am-consulting/Rscript/master/importMonthlyTradingVolumeValue.r",
    ssl.verifypeer = FALSE
  )
eval(parse(text = script))
tmp <- MonthlyTradingVolumeValue
}
```

```{r,warning=F,error=F,message=F,echo=F}
if(loadTMP==4){
library(RCurl)
script <-
  getURL(
    "https://raw.githubusercontent.com/am-consulting/Rscript/master/importAverageYield.r",
    ssl.verifypeer = FALSE
  )
eval(parse(text = script))
tmp <- AverageYield
tmp<-tmp[,c(1,4)]
colnames(tmp)[2]<-paste('第一部',colnames(tmp)[2])
}
```

```{r,warning=F,error=F,message=F,echo=F}
dataSet <- na.omit(tmp)
if(dataTail!=0){
dataSet <- tail(dataSet,dataTail)
}
bufColnames<-colnames(dataSet)[2]
dataSet[, 1] <- as.Date(dataSet[, 1])
dataSet <-
  data.frame(dataSet, apply(dataSet[1], 1, FUN), check.names = F)
colnames(dataSet)[ncol(dataSet)] <- indextitle[iii]
dateFormat = "%Y年%m月%d日"
if (length(unique(day(dataSet[, 1]))) == 1) {
  dateFormat = "%Y年%m月"
}
if (length(unique(month(dataSet[, 1]))) == 1) {
  dateFormat = "%Y年"
}
chartTitle <-
  paste(colnames(dataSet)[2],
        format(dataSet[1, 1], dateFormat),
        "-",
        format(dataSet[nrow(dataSet), 1], dateFormat))
borderdate <- max(highestData[1, 1], dataSet[1, 1])
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
dataTitle <-
  paste0("建設労働需給調査 月次 建設技能労働者過不足率(8職種計･全国,季節調整値)-", format(tail(dataSet[, 1], 1), dateFormat))
dataTitle0 <- '歴代政権毎の時系列推移'
dataSource <- "国土交通省"
notes <- "複数のワードで検索する際は半角スペースで区切ってください"
Author <- "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
htmlID <- timeStamp
cat(paste("Title :", dataTitle, dataTitle0, "\n"))
cat(paste("Raw Data Source :", dataSource, "\n"))
cat(paste("Author :", Author, "\n"))
cat(paste("作成日 :", Sys.time(), "\n"))
cat(paste("特記 :", notes, "\n"))
cat(paste("ID :", htmlID, "\n"))
```

```{r,warning=F,error=F,message=F,echo=F}
# 前月比
dataSet01P <-
  data.frame(Date = dataSet[-1, 1],
             round(
               diff(as.matrix(dataSet[, -c(1, ncol(dataSet))]), lag = 1, differences = 1) /
                 as.matrix(dataSet[-nrow(dataSet), -c(1, ncol(dataSet))]) * 100,
               2
             ),
             dataSet[-1, ncol(dataSet)],
             check.names = F)
# 前月差
dataSet01D <- data.frame(Date = dataSet[-1, 1],
                         round(diff(
                           as.matrix(dataSet[, -c(1, ncol(dataSet))]), lag = 1, differences = 1
                         ), 10),
                         dataSet[-1, ncol(dataSet)],
                         check.names = F)
# 前月同月比
dataSet12P <-
  data.frame(
    Date = tail(dataSet[, 1], nrow(dataSet) - 12),
    round(
      diff(as.matrix(dataSet[, -c(1, ncol(dataSet))]), lag = 12, differences = 1) /
        as.matrix(head(dataSet[, -c(1, ncol(dataSet))], nrow(dataSet) - 12)) * 100,
      2
    ),
    tail(dataSet[, ncol(dataSet)], nrow(dataSet) - 12),
    check.names = F
  )
colnames(dataSet01P) <-
  colnames(dataSet01D) <-
  colnames(dataSet12P) <- colnames(dataSet)
colnames(dataSet01P)[-c(1, ncol(dataSet))] <-
  paste0(colnames(dataSet)[-c(1, ncol(dataSet))], '-前月比(%)')
colnames(dataSet01D)[-c(1, ncol(dataSet))] <-
  paste0(colnames(dataSet)[-c(1, ncol(dataSet))], '-前月差')
colnames(dataSet12P)[-c(1, ncol(dataSet))] <-
  paste0(colnames(dataSet)[-c(1, ncol(dataSet))], '-前月同月比(%)')
```

```{r,warning=F,error=F,message=F,echo=F}    
funPlotTimeSeries <- function() {
  dataSet <- na.omit(subset(dataSet, borderdate <= dataSet[, 1]))
  colnames(dataSet)[2] <- "value"
  for (rrrUL in seq(1, nrow(highestData), by = 1)) {
    if (highestData[rrrUL, 1] <= borderdate &
    borderdate <= highestData[rrrUL, 2]) {
    break
    }
  }
  for (rrrLL in seq(rrrUL, nrow(highestData), by = 1)) {
    if (highestData[rrrLL, 1] <= dataSet[nrow(dataSet), 1] & dataSet[nrow(dataSet), 1] <= highestData[rrrLL, 2]) {
      break
    }
  }
  segmentData <- highestData[c(rrrUL:rrrLL),]
  segmentData[1, 1] <- borderdate
  segmentData[nrow(segmentData), 2] <- dataSet[nrow(dataSet), 1]
  x0 <-
    segmentData[, 1][seq(1, length(segmentData[, 1]), by = 2)]
  x1 <-
    segmentData[, 2][seq(1, length(segmentData[, 2]), by = 2)]
  y0 <- min(dataSet[, 2])
  if (length((dataSet$value)[dataSet$value < 0]) != 0 & length((dataSet$value)[0 < dataSet$value]) != 0) {
    level.type <- 2
  } else{
    level.type <- 1
  }
  if (0 < y0 & level.type == 2) {
    y0 <- 0
  }
  y1 <- max(dataSet[, 2])
  shade <- data.frame(x0, x1, y0, y1)
  value.y <- (max(dataSet[, 2]) + min(dataSet[, 2])) / 2
  
  g1 <- ggplot()
  g1 <- g1 + geom_rect(
    data = shade,
    aes(
      xmin = x0,
      xmax = x1,
      ymin = y0,
      ymax = y1
    ),
    fill = 'gray80',
    alpha = 0.5
  )
  g1 <- g1 + geom_segment(
    data = segmentData,
    aes(
      x = segmentData[, 1],
      xend = segmentData[, 2],
      y = value.y,
      yend = value.y,
      colour = segmentData[, 3]
    ),
    size = 8
  )
  if (level.type == 1) {
    g1 <- g1 + geom_line(data = dataSet, aes(x = dataSet[, 1], y = dataSet[, 2]))
  } else{
    g1 <- g1 + geom_bar(
      data = dataSet,
      aes(x = dataSet[, 1], y = dataSet[, 2]),
      stat = "identity",
      position = "identity",
      fill = "blue",
      alpha = 0.5
    )
  }
  g1 <- g1 + geom_smooth(
    data = dataSet,
    aes(x = dataSet[, 1], y = dataSet[, 2]),
    method = loess,
    color = "red"
  )
  g1 <- g1 + ggtitle(chartTitle)
  g1 <- g1 + xlab("")
  g1 <- g1 + ylab("")
  g1 <- g1 + theme(axis.text = element_text(size = 12, face = "plain"))
  g1 <- g1 + theme(axis.title = element_text(size = 12, face = "plain"))
  g1 <- g1 + theme(title = element_text(size = 12, face = "plain"))
  g1 <- g1 + theme(legend.position = "right")
  g1 <- g1 + theme(legend.text = element_text(
  colour = "black",
  size = 12,
  face = "plain"
  ))
  g1 <- g1 + theme(legend.title = element_text(
  colour = "white",
  size = 0,
  face = "plain"
  ))
  g1 <- g1 + scale_x_date(labels = date_format(dateFormat))
  g1 <- g1 + scale_y_continuous(labels = comma)
  print(g1)
  }
```

```{r,warning=F,error=F,message=F,echo=F} 
funPlotBoxplot <- function() {
  par(mar = c(5, 4, 3, 3))
  subset(dataSet, borderdate <= dataSet[, 1])
  boxplotData <- dataSet[, c(2, 3)]
  colnames(boxplotData)[2] <- "Person"
  boxplotData <- melt(boxplotData, id = "Person")
  boxplotData <- boxplotData[, -2]
  boxplotData[, 2] <- as.numeric(boxplotData[, 2])
  colnames(boxplotData)[1] <- "variable"
  g2 <- ggplot(data = boxplotData, aes(x = variable, y = value))
  g2 <- g2 + geom_boxplot(lwd = 1)
  g2 <- g2 + ggtitle(chartTitle)
  g2 <- g2 + theme(axis.text.x = element_text(
  size = 13,
  angle = 90,
  hjust = 1,
  vjust = 0.5,
  face = "plain"
  ))
  g2 <- g2 + theme(axis.text.y = element_text(size = 12, face = "plain"))
  g2 <- g2 + theme(axis.title = element_text(size = 12, face = "plain"))
  g2 <- g2 + theme(title = element_text(size = 12, face = "plain"))
  g2 <- g2 + xlab("")
  g2 <- g2 + ylab("")
  g2 <- g2 + scale_y_continuous(labels = comma)
  print(g2)
  }
```

```{r,warning=F,error=F,message=F,echo=F}
funDataTable <- function() {
  DT::datatable(
    dataSet0,
    options = list(
      search.regex = T,
      paging = T,
      autoWidth = F,
      info = T,
      lengthChange = T,
      ordering = T,
      searching = T,
      scrollX = T,
      lengthMenu = list(c(10, -1, 1), c("10", "All", "1")),
      orderClasses = T,
      order = list(list(0, "desc")),
      search = list(regex = T, caseInsensitive = T)
      ),
    rownames = F,
    caption = captionText,
    class = "display compact",
    escape = F,
    filter = 'bottom'
  )
}
```

```{r,warning=F,error=F,message=F,echo=F} 
funPlotBoxplotAmcharts <- function(obj, bigTitle = '') {
  for (iii in 1:length(unique(obj[, 3]))) {
    tmp0 <- subset(obj, obj[, 3] == unique(obj[, 3])[iii])
    colnames(tmp0)[2] <- as.character(unique(obj[, 3])[iii])
    tmp0 <- tmp0[, 2, drop = F]
    if (iii == 1) {
      bufAmcharts <- tmp0
    } else{
      bufAmcharts <- qpcR:::cbind.na(bufAmcharts, tmp0)
    }
  }
  bufAmcharts <<- bufAmcharts
  cat(paste0('<b>', bigTitle, '</b>'))
  amBoxplot(bufAmcharts, horiz = T)
}
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
dateRange<-paste0(format(first(dataSet[,1]),dateFormat),'~',format(last(dataSet[,1]),dateFormat))
funPlotBoxplotAmcharts(obj = dataSet,bigTitle = paste(dataTitle,dateRange,'. Powered By https://www.amcharts.com/'))
```
<hr>  
```{r,warning=F,error=F,message=F,results='asis',echo=F}
funPlotTimeSeries()
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
#funPlotBoxplot()
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
dataSet0 <- merge(dataSet, dataSet01D)
dataSet0[,1]<-format(dataSet0[,1],dateFormat)
#colnames(dataSet0)[2]<-bufColnames
captionText<-paste(dataTitle, dataSource)
#dataSet0 <- data.frame(ID = seq(1, nrow(dataSet)), dataSet, check.names = F)
#dataSet0[,2]<-format(dataSet0[,2],dateFormat)
funDataTable()
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
cat(paste0('<b>',dateRange,'</b>'))
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
summary(dataSet[,2,drop=F])
```
<hr>
<b>民主党政権時と第二次安倍政権発足以降の比較</b>
```{r,warning=F,error=F,message=F,results='markup',echo=F}
summaryData <- bufAmcharts[,seq(ncol(bufAmcharts)-3,ncol(bufAmcharts))]
summary(summaryData)
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
dataSet0 <- highestData
colnames(dataSet0)<-c('就任日','退任日又は現職',colnames(dataSet0)[3],'在任期間(日)')
captionText<-'在任期間(但し現職含む)'
funDataTable()
```