---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y-%m-%d-%H-%M-%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',timeStamp,'.html')) })
title : "喫煙率"
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 8
    fig_width: 12
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 
<style>
.main-container {
	max-width: 1000px;
	margin-left: auto;
	margin-right: auto;
}
</style>

```{r,warning=F,error=F,message=F,results='hold',echo=F}
omitType <- 1
dataTitle<-'都道府県別の悪性新生物75歳未満年齢調整死亡率と喫煙率 - 男女計 - 2013年'
dataSource<-'国立がん研究センター'
notes<-'複数のワードで検索する際は半角スペースで区切ってください'
notes0<-"表中、-9999はNAを意味します"
Author<-"アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
htmlID<-timeStamp
cat(paste("Title :",dataTitle,"\n"))
cat(paste("Raw Data Source :",dataSource,"\n"))
cat(paste("Author :",Author,"\n"))
cat(paste("作成日 :",Sys.time(),"\n"))
cat(paste("特記 :",notes,"\n"))
cat(paste("特記 :",notes0,"\n"))
cat(paste("ID :",htmlID,"\n"))
windowsFonts(Meiryo=windowsFont("Meiryo"))
options(scipen = 999)
```

```{r,warning=F,error=F,message=F,echo=F}
loadTMP <- 1
```

```{r,warning=F,error=F,message=F,echo=F}
if(loadTMP==1){
tmp <-
  read.table(
    'clipboard',
    header = T,
    sep = '\t',
    stringsAsFactor = F,
    na.strings = c('na', '', '-', 'NA'),
    check.names = F
  )
}
```

```{r,warning=F,error=F,message=F,echo=F}
if(omitType==1) {
  dataSet <- na.omit(tmp)
}else{
  dataSet <- tmp[rowSums(is.na(tmp))!=(ncol(tmp)-1),]
}
```


```{r,warning=F,error=F,message=F,echo=F} 
funScatterPlot <- function() {
  mainTitle<-paste(colnames(dataSet)[obj01],'\n×\n',colnames(dataSet)[obj02])
  par(mar=c(5,5,6,5),family = 'Meiryo')
  plot(
    x,
    y,
    type = 'p',
    col = 'blue',
    xlab = paste0('x:',colnames(dataSet)[obj01]),
    ylab = paste0('y:',colnames(dataSet)[obj02]),
    panel.first = grid(
      nx = NULL,
      ny = NULL,
      lty = 2,
      equilogs = T
    ) ,
    main = paste0(mainTitle,'\nSource:',dataSource),
    cex.axis = 1,
    cex.lab = 1,
    cex.main = 1,
    lwd = 1,
    cex=4,
    pch=1
  )
  abline(lm(y~x),col='red',lwd=2)
  text(x,y,labels = dataSet[,1],cex = 0.9)
}
```

```{r,warning=F,error=F,message=F,echo=F}
funDataTable <- function() {
  DT::datatable(
    dataSet0,
    options = list(
      search.regex = F,
      paging = T,
      autoWidth = F,
      info = T,
      lengthChange = T,
      ordering = T,
      searching = T,
      scrollX = F,
      lengthMenu = list(c(10, -1, 1), c('10', 'All', '1')),
      orderClasses = T,
      order = list(list(orderCol, 'desc')),
      columnDefs = list(
        list(width = '10%', targets = 0)#,
        #        list(width = '25%', targets = 3)
      )
    ),
    rownames = F,
    caption = paste(dataTitle,'. Source:' ,dataSource),
    class = 'display compact'
  )
}
```

```{r,warning=F,error=F,message=F,results='asis',echo=F,fig.height=8,fig.width=10}
obj01 <- 2
obj02 <- 3
x <- dataSet[, obj01]
y <- dataSet[, obj02]
funScatterPlot()
```
<hr>
__注意__

1. 以下の線形回帰、相関分析に関して擬似相関の検討は行っていない。
1. 以下の線形回帰、相関分析に関して因果関係の検討は行っていない。

```{r,warning=F,error=F,message=F,results='hold',echo=F}
cat(paste("x :", colnames(dataSet)[obj01], "\ny :", colnames(dataSet)[obj02], "\n"))
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
summary(lm(y ~ x))
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
cor.test(x, y)
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
orderCol <- 1
dataSet0 <- dataSet
funDataTable()
```