---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y%m%d%H%M%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',timeStamp,'.html')) })

title : '人権侵犯事件'
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 10
    fig_width: 10
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet">
<style>
.main-container {
	max-width: 1100px;
	margin-left: auto;
	margin-right: auto;
}
</style>

```{r set-options, echo=F, cache=F}
options(width = 1000)
```

```{r,warning=F,error=F,message=F,echo=F}
# Reference http://stackoverflow.com/questions/32377291/insert-date-in-filename-while-knitting-document-using-rstudio-knit-button
library(DT)
library(lubridate)
library(googleVis)
library(pipeR)
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
timeSeries <- 0 # 1 or 0
needID <- 1
needAtag <- 0
needAdd <- 0
needDiff <- 0
needTrans <- 0
pp <- 0
dataTitle <- '人権侵犯事件統計 - 種類別人権侵犯事件 - 2015年'
dataSource <- '法務省'
notes <- '複数のワードで検索する際は半角スペースで区切ってください'
notes0 <- '表中、-9999はNAを意味します'
dataTail <- 0 
Author <- 'アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp'
htmlID <- timeStamp
cat(paste('Title :',dataTitle,'\n'))
cat(paste('Raw Data Source :',dataSource,'\n'))
cat(paste('Author :',Author,'\n'))
cat(paste('作成日 :',Sys.time(),'\n'))
cat(paste('特記 :',notes,'\n'))
cat(paste('特記 :',notes0,'\n'))
cat(paste("ID :", htmlID, "\n"))
```

```{r,warning=F,error=F,message=F,echo=F}
tmp <-
  read.table(
  'clipboard',
  header = T,
  sep = '\t',
  stringsAsFactor = F,
  na.strings = c('na', '', '-', ' ---- ', '   -- ','NA'),
  check.names = F
  )
  if(timeSeries==0){
    if(needAdd == 1){tmp <- data.frame(tmp,tmp[,1,drop=F],check.names = F)}
    if(needID!=0){
    dataSet <- data.frame(ID = seq(1, nrow(tmp)), tmp, check.names = F)
    }else{
    dataSet <- tmp
    }
    if(needAtag!=0){
    dataSet[,needAtag]<-paste0('<a href=\"',dataSet[,needAtag],'\" target=\"_blank\">Link</a>')
    }
    dataFormat <- 0
  }else{
    dataSet <- tmp
    dataSet[,1] <- as.Date(dataSet[,1])
    dataFormat <- '%Y-%m'
    if (1 < unique(day(dataSet[, 1]))) {
      dataFormat <- '%Y-%m-%d'
    }
    dataSet[, 1] <- format(dataSet[, 1], dataFormat)
  }

  if (dataFormat != 0 & needDiff == 1) {
    dataSetDT <- dataSet
    if(pp==0){
    dataSetDT0<-data.frame(
      Date=dataSetDT[-1,1],  
      round(diff(as.matrix(dataSetDT[,-1]))/as.matrix(dataSetDT[-nrow(dataSetDT),-1])*100,2),check.names = F)
    }else if(pp==1){
    dataSetDT0<-data.frame(
      Date=dataSetDT[-1,1],  
      round(diff(as.matrix(dataSetDT[,-1])),10),check.names = F)
    }
    dataSetDT <- na.omit(data.frame(dataSetDT,dataSetDT[,1,drop=F],check.names = F))
    dataSetDT0 <- na.omit(data.frame(dataSetDT0,dataSetDT0[,1,drop=F],check.names = F))
  } else{
    dataSetDT <- dataSet
  }
```

```{r,warning=F,error=F,message=F,echo=F}
  funDataTable <- function(obj,append='') {
    DT::datatable(
      obj,
      options = list(
        search.regex = F,
        paging = T,
        autoWidth = F,
        info = T,
        lengthChange = T,
        ordering = T,
        searching = T,
        scrollX = F,
        lengthMenu = list(c(10,-1, 1), c(10, 'All', 1)),
        orderClasses = T,
        order = list(list(0, 'asc')),
        search = list(regex = T, caseInsensitive = T),
        columnDefs = list(
          list(width = '5%', targets = 0)
#           ,
#          list(width = '15%', targets = 1)
          # ,
          # list(width = '8%', targets = ncol(obj)-1)
          )
        ),
      rownames = F,
      caption = paste(dataTitle, append),
      class = 'display compact',
      escape = F, # or escape = 'v1'(特定のcolumn) テーブル内でhtmlマークアップする場合に必須 
      filter = 'bottom'
    )
  }
```

```{r,warning=F,error=F,message=F,echo=F}
  fungvisTable <- function(obj) {
    PopTable <- gvisTable(obj, 
      options = list(width = 1000, height = 'automatic',  page = 'enable' ,  pageSize=25)
    )
    plot(PopTable,tag='chart')
  }  
```

```{r,warning=F,error=F,message=F,echo=F}
  if(needTrans == 1) {
    buf <- tail(dataSetDT, 5)
    buf <- t(buf)
    buf <- data.frame(row.names(buf), buf, check.names = F, row.names = NULL)
    colnames(buf) <- unlist(buf[1, ])
    buf <- buf[-1, ]
    buf[, -1] <- apply(buf[, -1], 2, as.numeric)
    if(needID == 1){
    buf <- data.frame(ID=seq(1,nrow(buf)),buf,check.names = F,stringsAsFactors = F)  
    }
    dataSetDT <- buf
  }
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
appendTitle<-''
#funDataTable(obj = dataSetDT, append = appendTitle)
#cat(paste(dataTitle,appendTitle))
fungvisTable(obj = dataSetDT)
```
<hr>
```{r,warning=F,error=F,message=F,echo=F} 
#apply(dataSetDT[-1,-c(1,2)],2,summary)
```

```{r,warning=F,error=F,message=F,echo=F} 
funPlotBoxplotAmcharts <- function(obj, bigTitle = '') {
  rAmCharts::amBoxplot(obj, horiz = T, names = colnames(obj)) %>>% rAmCharts::amOptions(theme = "none" , main = bigTitle)
}
```
<hr>
```{r,warning=F,error=F,message=F,echo=F} 
#funPlotBoxplotAmcharts(obj = as.numeric(dataSetDT[, 4:6]), bigTitle = paste0(dataTitle, ' - 基本統計量'))
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
if (dataFormat != 0 & needDiff == 1) {
cat('<hr>')
if(pp==0){appendTitle<-'前月比(%)'}else if(pp==1){appendTitle<-'前月差'}
funDataTable(obj = dataSetDT0, append = appendTitle)
}
```