---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y%m%d%H%M%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',timeStamp,'.html')) })
title : "待機児童数"
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 8
    fig_width: 10
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 
<style>
.main-container {
	max-width: 1000px;
	margin-left: auto;
	margin-right: auto;
}
</style>

```{r set-options, echo=F, cache=F}
options(width = 1000)
```

```{r warning=F, error=F, message=F, echo=F}
library(RCurl)
library(DT)
```

```{r warning=F, error=F, message=F, echo=F, results='hold'}
dataTitle <- '待機児童数の時系列推移'
dataSource <- '厚生労働省'
notes <- '複数のワードで検索する際は半角スペースで区切ってください'
notes0 <- "表中、-9999はNAを意味します"
Author <- "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
htmlID <- timeStamp
cat(paste("Title :", dataTitle, "\n"))
cat(paste("Raw Data Source :", dataSource, "\n"))
cat(paste("Author :", Author, "\n"))
cat(paste("作成日 :", Sys.time(), "\n"))
cat(paste("特記 :", notes, "\n"))
cat(paste("特記 :", notes0, "\n"))
cat(paste("ID :", htmlID, "\n"))
windowsFonts(Meiryo = windowsFont("Meiryo"))
options(scipen = 999)
```

<b>(注意)</b><br>

1. 待機児童数の定義には1995年4月1日分から最新分までに変更がありますので留意して下さい。
1. 上記定義変更に関らず1系列の時系列チャートとして表示しています。
1. 上記定義変更の詳細は本ページデータテーブル中のリンクその他の厚生労働省Webサイトで確認して下さい。
1. 2001年04月01日時点(平成13年)の待機児童数について http://www.mhlw.go.jp/houdou/0112/h1227-4.html では21,031と記されています。
1. 時点データを折れ線プロットしていますが、時点間の線形変化を意味していません。

<hr>

```{r warning=F, error=F, message=F, echo=F, results='hold'}
library(RCurl)
library(DT)
targetURL <-
'https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/csv/%E5%BE%85%E6%A9%9F%E5%85%90%E7%AB%A5%E6%95%B0%E3%81%AE%E6%99%82%E7%B3%BB%E5%88%97%E6%8E%A8%E7%A7%BB(%E5%AE%9A%E7%BE%A9%E5%A4%89%E6%9B%B4%E3%81%AB%E6%B3%A8%E6%84%8F)_%E5%87%BA%E6%89%80-%E5%8E%9A%E7%94%9F%E5%8A%B4%E5%83%8D%E7%9C%81.csv'
dataSet <- read.csv(text = getURL(targetURL), check.names = F, stringsAsFactors = F)
dataSet$URL <- paste0('<a href="', dataSet$URL, '" target="_blank">', dataSet$URL, '</a>') 
dataSet$Date <- as.Date(dataSet$Date)
colnames(dataSet) <- c('時点','待機児童数','URL','平成表記','特記事項')
```

```{r warning=F, error=F, message=F, echo=F, results='hold'}
fun_datatable <- function(obj){
DT::datatable(
  obj,
  options = list(
  search.regex = F,
  paging = T,
  autoWidth = F,
  info = T,
  lengthChange = T,
  ordering = T,
  searching = T,
  scrollX = F,
  lengthMenu = list(c(10, -1, 1), c(10, 'All', 1)),
  orderClasses = T,
  order = list(list(0, 'desc')),
  columnDefs = list(list(width = '15%', targets = 0))),
  rownames = F,
  caption = paste0(dataTitle, '. Source:',dataSource),
  class = 'display compact',
  escape = F,
  filter = 'bottom'
)
}  
```

```{r warning=F, error=F, message=F, echo=F, results='hold'}
fun_plotTimeSeries <- function(obj) {
par(mar=c(7,3,3,1),family = 'Meiryo')
plot(
  obj[, 1],
  obj[, 2],
  type = 'o',
  col = 'blue',
  xlab = '' ,
  ylab = '' ,
  xaxt = 'n',
  main = paste0(dataTitle, '. Source : ',dataSource),
  cex.axis = 1.2,
  cex.lab = 1.2,
  cex.main = 1.2,
  lwd = 1
  )
panel.first = grid(nx = NULL, ny = NULL, lty = 2, equilogs = T) 
axis.Date(side = 1, at = obj[,1], padj = 0.5, cex.axis=1.2, format = '%Y-%m-%d', las = 2) 
rectDateL <- as.numeric(as.Date('2009-09-16'))
rectDateR <- as.numeric(as.Date('2012-12-26'))
rectText <- '民主党政権'
rect(
  xleft = rectDateL, ybottom = par('usr')[3], 
  xright = rectDateR, ytop = par('usr')[4], col = 'dimgray', density = 10, angle = 45)
text(rectDateL, par('usr')[4], labels = paste0('\n\n',rectText), pos = 4, cex = 1.2)
text(obj[,1], obj[,2], labels = obj[,2], cex = 1.0, pos = 1)
}
```

```{r warning=F, error=F, message=F, echo=F, results='asis'}
fun_datatable(obj =   dataSet[,1:3])
cat('<hr>')
fun_plotTimeSeries(obj = dataSet[,1:2,drop=F])
```