---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');timeStamp<-format(Sys.time(),'%Y%m%d%H%M%S');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',timeStamp,'.html')) })

title : '学力調査'
author: 'アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp'
output: 
  html_document:
    fig_height: 7
    fig_width: 10
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 
<style>
.main-container {
	max-width: 1000px;
	margin-left: auto;
	margin-right: auto;
}
</style>

```{r set-options, echo=F, cache=F}
options(width = 1000,scipen = 999)
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
dataTitle <- paste0("平成28年度-全国学力･学習状況調査-都道府県別-中学校(公立) × 1人当たり県民所得")
dataSource <- "国立教育政策研究所 、 内閣府"
notes <- "複数のワードで検索する際は半角スペースで区切ってください"
Author <- "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
htmlID <- timeStamp
cat(paste("Title :", dataTitle,"\n"))
cat(paste("Raw Data Source :", dataSource, "\n"))
cat(paste("Author :", Author, "\n"))
cat(paste("作成日 :", Sys.time(), "\n"))
cat(paste("特記 :", notes, "\n"))
cat(paste("ID :", htmlID, "\n"))
windowsFonts(Meiryo = windowsFont("Meiryo"))
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
tmp <-
  read.table(
    "clipboard",
    header = T,
    sep = "\t",
    stringsAsFactor = F,
    na.strings = c("NA", "-", "－", "… ", ".", ""),
    check.names = F
  )
dataSet0 <- tmp
dataSet <- na.omit(tmp)
rankdataSet <-
  apply(dataSet[, -1] * -1, 2, function(x)
    rank(x, ties.method = 'average'))
```
<h4>ピアソン積率相関係数</h4>
```{r,warning=F,error=F,message=F,results='hold',echo=F}
cor(dataSet[, -1], method = 'pearson')
```
<h4>スピアマン順位相関係数</h4>
```{r,warning=F,error=F,message=F,results='hold',echo=F}
cor(dataSet[, -1], method = 'spearman')
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
funPlot <- function() {
  plot(
    dataSet[, obj01],
    dataSet[, obj02],
    type = 'p',
    col = 'blue',
    xlab = colnames(dataSet)[obj01] ,
    ylab = colnames(dataSet)[obj02] ,
    panel.first = grid(
      nx = NULL,
      ny = NULL,
      lty = 2,
      equilogs = T
    ) ,
    main = title,
    cex.axis = 1.2,
    cex.lab = 1.2,
    cex.main = 1.2,
    lwd = 1
  )
  text(dataSet[, obj01], dataSet[, obj02], labels = dataSet[, 1], srt = 45,cex = 1.1)
  abline(lm(dataSet[, obj02] ~ dataSet[, obj01]), col = 'red', lwd = 2)
}
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
pair <- combn(c(6, 2, 3, 4, 5), m = 2, simplify = F)
par(mar = c(5, 5, 1, 1), family = 'Meiryo')
for (iii in 1:length(pair)) {
  obj01 <- pair[[iii]][1]
  obj02 <- pair[[iii]][2]
  title <- ''
  funPlot()
  cat('<hr>')
}
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
DT::datatable(
  dataSet,
  options = list(
    search.regex = F,
    paging = T,
    autoWidth = F,
    info = T,
    lengthChange = T,
    ordering = T,
    searching = T,
    scrollX = F,
    lengthMenu = list(c(20,-1, 1), c(20, 'All', 1)),
    orderClasses = T,
    order = list(list(5, 'desc')),
    columnDefs = list(
      list(width = '15%', targets = 0)
      )
    ),
  rownames = F,
  caption = paste(dataTitle,'. データ出所:',dataSource),
  class = 'display compact'
)
```