---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',format(Sys.time(),'%Y-%m-%d-%H-%M-%S'),'.html')) })


title : "過不足率"
author: "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output: 
  html_document:
    fig_height: 4
    fig_width: 10
    keep_md: no
    md_extensions: -ascii_identifiers 
    code_folding: show
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 
<style>
.main-container {
	max-width: 1000px;
	margin-left: auto;
	margin-right: auto;
}
</style>
```{r,warning=F,error=F,message=F,results='hold',echo=F}
dataTitle <- '建設技能労働者過不足率_8職種計_全国_季節調整値 2016年7月'
dataSource <- '国土交通省'
notes <- '複数のワードで検索する際は半角スペースで区切ってください'
notes0 <- "表中、-9999はNAを意味します"
Author <- "アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
cat(paste("Title :", dataTitle, "\n"))
cat(paste("Raw Data Source :", dataSource, "\n"))
cat(paste("Author :", Author, "\n"))
cat(paste("作成日 :", Sys.time(), "\n"))
cat(paste("特記 :", notes, "\n"))
cat(paste("特記 :", notes0, "\n"))
windowsFonts(Meiryo = windowsFont("Meiryo"))
```

```{r,warning=F,error=F,message=F,results='hold',echo=F}
library(e1071)
library(nortest)
library(coin)
library(lubridate)
library(DT)
```

```{r,warning=F,error=F,message=F,results='hide',echo=F}
dfColnames <- c('Period1', 'Period2')
dateRange01 <- as.Date(c('2009/9/1', '2012/12/1'))
dateRange02 <- as.Date(c('2013/1/1', '2016/7/1'))
```

```{r,warning=F,error=F,message=F,results='hide',echo=F}
tmp <-
  read.table(
    "clipboard",
    header = TRUE,
    sep = "\t",
    stringsAsFactor = F,
    na.strings = c("NA", "-", "－", "… ", ".", ""),
    check.names = FALSE
  )
tmp <- na.omit(tmp)
tmp[, 1] <- as.Date(tmp[, 1])
dateFormat = '%Y-%m-%d'
if (length(unique(day(tmp[, 1]))) == 1) {
  dateFormat = '%Y-%m'
}
if (length(unique(month(tmp[, 1]))) == 1) {
  dateFormat = '%Y'
}
```

```{r,warning=F,error=F,message=F,results='hide',echo=F}
dataset <- list()
dateRange<-list()
dataset[[1]] <-
  subset(tmp, dateRange01[1] <= tmp[, 1] & tmp[, 1] <= dateRange01[2])
dataset[[2]] <-
  subset(tmp, dateRange02[1] <= tmp[, 1] & tmp[, 1] <= dateRange02[2])
dateRange[[1]] <- format(dateRange01,dateFormat)
dateRange[[2]] <- format(dateRange02,dateFormat)
digitsN <- 3
comparisonData <- data.frame(stringsAsFactors = F)
for (ccc in 1:2) {
  x <- dataset[[ccc]][, 2]
comparisonData[1, ccc] <- paste(dateRange[[ccc]] , collapse = '~')
  comparisonData[2, ccc] <- nrow(dataset[[ccc]])
  comparisonData[3, ccc] <- format(mean(x), digits = digitsN)
  comparisonData[4, ccc] <- format(median(x), digits =  digitsN)
  comparisonData[5, ccc] <- paste(range(x), collapse = '~')
  comparisonData[6, ccc] <- format(skewness(x), digits = digitsN)
  comparisonData[7, ccc] <- format(kurtosis(x) , digits = digitsN)
  comparisonData[8, ccc] <- format(ad.test(x)$p.value, digits = digitsN)
  comparisonData[9, ccc] <-
    format(var(x) * (length(x) - 1) / length(x), digits = digitsN) # 標本分散
  comparisonData[10, ccc] <- format(var(x), digits = digitsN)# 不偏分散
  comparisonData[11, ccc] <-
    format(sqrt(var(x) * (length(x) - 1) / length(x)), digits = digitsN)# 標本標準偏差
  comparisonData[12, ccc] <- format(sd(x), digits = digitsN)# 不偏標準偏差
}
comparisonData
row.names(comparisonData) <-
  c('期間',
    'n',
    '平均',
    '中央値',
    '範囲',
    '歪度',
    '尖度',
    '正規性(p値)',
    '標本分散',
    '不偏分散',
    '標本標準偏差',
    '不偏標準偏差')
colnames(comparisonData) <- dfColnames
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
par(
  mfrow = c(1, 2),
  mar = c(3, 3, 3, 5),
  oma = c(1, 1, 3, 1),
  family = 'Meiryo'
)
for (iii in 1:2) {
  chartTitle <-
    paste(dateRange[[iii]] , collapse = '~')
  plot(
    dataset[[iii]][, 1],
    dataset[[iii]][, 2],
    type = 'h',
    col = 'blue',
    xlab = '' ,
    ylab = '' ,
    panel.first = grid(
      nx = NULL,
      ny = NULL,
      lty = 2,
      equilogs = T
    ) ,
    xaxt = 'n',
    main = chartTitle ,
    cex.axis = 1,
    cex.lab = 1,
    cex.main = 1,
    lwd = 1
  )
  lo <- loess(dataset[[iii]][, 2] ~ as.numeric(dataset[[iii]][, 1]))
  lines(dataset[[iii]][, 1] ,
        predict(lo) ,
        col = 'red',
        lwd = 2,
        lty = 2)
  axis.Date(
    side = 1,
    at = dataset[[iii]][, 1],
    format = dateFormat,
    padj = 1,
    cex.axis = 1.0
  )
}
title(main = list(colnames(tmp)[2], cex = 1.2), outer = T)
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
par(
  mfrow = c(1, 2),
  mar = c(3, 3, 3, 5),
  oma = c(1, 1, 3, 1),
  family = 'Meiryo'
)
for (iii in 1:2) {
  chartTitle <-
    paste(dateRange[[iii]] , collapse = '~')
  hist(dataset[[iii]][, 2], col = "lightsteelblue", main = chartTitle)
}
title(main = list(colnames(tmp)[2], cex = 1.2), outer = T)
```
<hr>
```{r,warning=F,error=F,message=F,echo=F}
timeseriesDF<-tail(tmp,12)
timeseriesDF[,1]<-format(timeseriesDF[,1],dateFormat)
append<-''
  DT::datatable(
    timeseriesDF,
    options = list(
      search.regex = F,
      paging = F,
      autoWidth = F,
      info = F,
      lengthChange = F,
      ordering = F,
      searching = F,
      scrollX = F,
      orderClasses = T,
      columnDefs = list(list(width = '20%', targets = 0))
    ),
    rownames = F,
    caption = paste0(colnames(tmp)[2], '. ', append),
    class = 'display compact'
  )
```
<hr>
```{r,warning=F,error=F,message=F,echo=F}
append<-''
  DT::datatable(
    comparisonData,
    options = list(
      search.regex = F,
      paging = F,
      autoWidth = F,
      info = F,
      lengthChange = F,
      ordering = F,
      searching = F,
      scrollX = F,
      orderClasses = T,
      columnDefs = list(list(width = '20%', targets = 0))
    ),
    rownames = T,
    caption = paste0(colnames(tmp)[2], '. ', append),
    class = 'display compact'
  )
```
<hr>
```{r,warning=F,error=F,message=F,results='asis',echo=F}
x <- dataset[[1]][, 2]
y <- dataset[[2]][, 2]
cat(paste0('<h4>', colnames(tmp)[2], '</h4><br>'))
cat(paste0('･',paste0(dateRange[[1]] , collapse = '\\~'), ' : x<br>'))
cat(paste0('･',paste0(dateRange[[2]] , collapse = '\\~'), ' : y'))
```

```{r,warning=T,error=F,message=F,results='hold'}
t.test(x, y, var.equal = T, alternative = 'two.sided')
```

```{r,warning=T,error=F,message=F,results='hold'}
t.test(x, y, var.equal = F, alternative = 'two.sided')
```

```{r,warning=T,error=F,message=F,results='hold'}
TwoTimeSeriesData <- c(x, y)
Period <- factor(c(rep("Period1", length(x)), rep("Period2", length(y))))
wilcox_test(TwoTimeSeriesData ~ Period, distribution = "exact")
```

```{r,warning=T,error=F,message=F,results='hold'}
var.test(x, y, alternative = 'two.sided')
```