---
knit: (function(inputFile, encoding) {username<-Sys.info()['user'];fileName<-'defaultPath.csv';pathToFile <-paste0('C:/Users/', username,'/Desktop/pathToCSV/');setwd(pathToFile);buf0<-read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,fileEncoding = 'utf-8');rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('C:/Users/',username,buf0[2,1],'charts/','am-consulting.co.jp-',format(Sys.time(),'%Y-%m-%d-%H-%M-%S'),'.html')) })

title : '完全失業率と有効求人倍率 2016年06月分'
author: 'アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp'
output: 
  html_document:
    fig_height: 10
    fig_width: 10
    keep_md: no
    md_extensions: -ascii_identifiers 
---
<link href="http://knowledgevault.saecanet.com/components/rmarkdown-html.css" rel="stylesheet"> 

```{r,warning=F,error=F,message=F,results='hold',echo=F}
dataTitle<-'完全失業率×有効求人倍率 2016年6月分'
dataTitle0<-'民主党政権時と第二次安倍政権以降の比較'
dataSource<-"総務省、厚生労働省"
notes<-"複数のワードで検索する際は半角スペースで区切ってください"
Author<-"アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
cat(paste("Title :",dataTitle,dataTitle0,"\n"))
cat(paste("Raw Data Source :",dataSource,"\n"))
cat(paste("Author :",Author,"\n"))
cat(paste("作成日 :",Sys.time(),"\n"))
cat(paste("特記 :",notes,"\n"))
```

```{r,warning=F,error=F,message=F,echo=F}
datafreq<-12 # 4 , 12
library(ggplot2)
library(xtable)
library(grid)
library(lubridate)
#library(ggrepel)
#Error: package ‘ggplot2’ 1.0.1 is loaded, but >= 2.0.0 is required by ‘ggrepel’
```

```{r,warning=F,error=F,message=F,echo=F}
tmp <-
  read.table(
  "clipboard",
  header = TRUE,
  sep = "\t",
  stringsAsFactor = F,
  na.strings = c("NA", "-", "－", "… ", ".", ""),
  check.names = FALSE
  )
  tmp[, 1] <- as.Date(tmp[, 1])
```

```{r,warning=F,error=F,message=F,echo=F}
#windowsFonts(Meiryo=windowsFont("Meiryo"))
SD<-Sys.Date();ST<-Sys.time()
#par(mfrow=c(1,1),family="Meiryo",ps=17,oma=c(3,3,3,2),mar=c(5,5,5,5))
dataset<-subset(tmp,as.Date("2009/9/1")<=tmp[,1])
dataset$Number<-seq(1,nrow(dataset))
dataset$color<-ifelse(dataset[,1]<=as.Date("2012/12/1"),"indianred1","royalblue")
if(datafreq==4){datestart<-c(year(dataset[1,1]),month(dataset[1,1])/3)}else{datestart<-c(year(dataset[1,1]),month(dataset[1,1]))}
# http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf
```

```{r,warning=F,error=F,message=F,echo=F}
minPoint<-min(dataset[,2:3])
maxPoint<-max(dataset[,2:3])
funPlot<-function(){
g<-ggplot()
g<-g+geom_point(data=dataset,aes(x=dataset[,2],y=dataset[,3]),color=dataset$color,size=4)
g<-g+ggtitle(paste(dataTitle,"\nSource:",dataSource,"\n赤:民主党 , 青:自民党",sep=""))
g<-g+xlab(colnames(dataset)[2])+ylab(colnames(dataset)[3])
g<-g+theme(plot.title=element_text(family="Meiryo"))
g<-g+theme(axis.title.x=element_text(family="Meiryo")) 
g<-g+theme(axis.title.y=element_text(family="Meiryo")) 
g<-g+theme(axis.text.x=element_text(angle=0,family="Meiryo")) 
g<-g+theme(axis.text.y=element_text(angle=90,family="Meiryo"))
#g<-g+geom_line(aes(x=c(minPoint,maxPoint),y=c(minPoint,maxPoint)),color="black")
g<-g+geom_text(data=dataset,aes(x=dataset[ ,2],y=dataset[ ,3],label=dataset$Number)              ,vjust=0,hjust=2,family="Meiryo")
g<-g+geom_text(data=dataset,aes(x=dataset[1,2],y=dataset[1,3],label=format(dataset[1,1],"%Y-%m")),vjust=1,hjust=startHjust,family="Meiryo",size= 10)
g<-g+geom_text(data=dataset,aes(x=dataset[nrow(dataset),2],y=dataset[nrow(dataset),3],label=format(dataset[nrow(dataset),1],"%Y-%m")),vjust=0,hjust=endHjust,family="Meiryo",size= 10)
buf<-subset(dataset,dataset[,1]==as.Date("2012/12/1"))
g<-g+geom_text(data=buf,aes(x=buf[1,2],y=buf[1,3],label=format(as.Date("2012/12/1"),"%Y-%m")),vjust=1,hjust=midHjust,family="Meiryo",size= 10)
g<-g+geom_path(data=dataset,aes(x=dataset[,2],y=dataset[,3]),color=dataset$color)
print(g)
}
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
# 1 左 , 0 右
startHjust<-1
endHjust  <-0
midHjust  <-0
funPlot()
```
<hr>
```{r,warning=F,error=F,message=F,echo=F,results='asis'}
cat(paste("
<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js\"></script>
<style>
table{width:100%;border-collapse:collapse;padding:0;border-spacing:1;margin-left: auto;margin-right: auto;}
tr, td, th{white-space: nowrap;}
table.amcc tr:nth-child(odd) {background-color: #F5F5F5;}
table.amcc tr:nth-child(even){background-color: #FFFFFF;}
</style>
<div align=\"center\">
<b>",dataTitle,"</b>
</div>
<b>",colnames(dataset)[4],"</b>
<div style=\"overflow-x:scroll;\">",sep=""))

print(
  xtable(ts(dataset[,4],frequency=datafreq,start=datestart)),
  type="html",include.rownames=T,html.table.attributes="class='amcc'")

cat(paste("
</div>
<div style=\"text-align:center\">
</div>
<hr>
<b>",colnames(dataset)[2],"</b>
<div style=\"overflow-x:scroll;\">",sep=""))

print(
  xtable(ts(dataset[,2],frequency=datafreq,start=datestart)),
  type="html",include.rownames=T,html.table.attributes="class='amcc'")

cat(paste("
</div>
<hr>
<b>",colnames(dataset)[3],"</b>
<div style=\"overflow-x:scroll;\">",sep=""))

print(
  xtable(ts(dataset[,3],frequency=datafreq,start=datestart)),
type="html",include.rownames=T,html.table.attributes="class='amcc'")

cat(paste("
</div>
<script>
$(\"tr\").not(':first').hover(
function () {$(this).css(\"background\",\"#8FBC8F\");}, 
function () {$(this).css(\"background\",\"\");}
);
</script>",sep=""))
```