```{r warning=F,error=F,message=F,echo=F,results='hide'}
library(ggplot2);library(scales);library(ggfortify)
windowsFonts(Meiryo = windowsFont("Meiryo"))
options(scipen = 100)
pngWidth <- 1000
pngHeight <- 600
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
fileName <- 
  'functionList.csv'
baseURL <- 
  'https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/'
functionList <- 
  read.csv(
    file = paste0(baseURL,'csv/',fileName),
    header = F,
    as.is = T)
for(iii in 1:nrow(functionList)){
  script <- 
    RCurl::getURL(paste0(baseURL,functionList[iii,1]),ssl.verifypeer = F)
  eval(parse(text = script))
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
userName <- Sys.info()['user']
fileName <- 'defaultPath.csv'
pathToFile <-
  paste0('C:/Users/',userName,'/Desktop/pathToCSV/')
setwd(pathToFile)
buf0 <-
  read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,
           fileEncoding = 'UTF8')
pathOutput <- paste0('C:/Users/',userName,buf0[2,1],'charts/indicator/')
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
borderM <- 4
dataFile <- "all_month.csv"
earthQuakeData <-
  read.csv(file = paste0("http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/",dataFile),
           header = T,as.is = T,skip = 0,stringsAsFactor = F,na.strings = c(""),check.names = F)
earthQuakeData$GMT <- 
  as.POSIXlt(sub("Z","",sub("T"," ",earthQuakeData$time)),"GMT")
earthQuakeData$JST <- 
  as.POSIXct(sub("Z","",sub("T"," ",earthQuakeData$time)))+3600*9
earthQuakeData$JSTDate <- 
  as.Date(earthQuakeData$JST,tz = "Asia/Tokyo")
# POSIXctをas.Date処理する際、tzを指定しないとGMTとしてマイナス9時間後の日付に変換される
yesterdayData <- 
  earthQuakeData[earthQuakeData$JSTDate==(Sys.Date()-1),c(1,2,3,4,5,6,14,24,25)]
yesterdayDataOver <- 
  yesterdayData[borderM<=yesterdayData$mag,]
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
pngN <- 1
setwd(pathOutput)
pngFile <- paste0('AMCC-science-',pngN,".png")
png(file = pngFile, width = pngWidth, height = pngHeight)
g <- fun_ggplotWorldMap(ratio = 1.15)
g <- g + geom_point(data = yesterdayDataOver,aes(x = longitude, y = latitude),colour = "red",
                    alpha = 30/100,size = 4) 
g <- g + geom_text(data = yesterdayDataOver,aes(x = longitude,y = latitude,
                                                label = paste0(mag,':',magType)),
                   vjust = 0,hjust = 0,family = "Meiryo",size= 6)
g <- g + ggtitle(paste0('Earthquakes occurred on ',
                        unique(yesterdayDataOver$JSTDate),'\nMagnitude over ',borderM,
                        '\nSource:United States Geological Survey'))  
g <- g + theme(plot.title = element_text(hjust = 0.5,family = "Meiryo",size = 20))
g <- g + theme(axis.title.x = element_text(family = "Meiryo",size = 16)) 
g <- g + theme(axis.title.y = element_text(family = "Meiryo",size = 16)) 
g <- g + theme(axis.text.x = element_text(angle = 0,family = "Meiryo",size = 16)) 
g <- g + theme(axis.text.y = element_text(angle = 90,family = "Meiryo",size = 16))
g
dev.off()
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
fun_ggplot_line <- function(plotData,pngN){
  setwd(pathOutput)
  pngFile <- paste0('AMCC-science-TS-',pngN,".png")
  png(file = pngFile, width = pngWidth, height = pngHeight)
  if(length(unique(lubridate::day(plotData$Date)))<=5){
    dateFormat <- '%Y-%m'
  }else{
    dateFormat <- '%Y-%m-%d'
  }
  dateRange <- paste0(format(range(plotData$Date),dateFormat),collapse = '~')
  latestData <- paste0(format(tail(plotData,1)[1,1],dateFormat),':',tail(plotData,1)[1,2])
  g <- ggplot(data = plotData,aes(x = Date,y = plotData[,2]))
  g <- g + geom_line(size = 0.5,col = "black")
  g <- g + geom_smooth(method = lm,lwd = 1,col = "red")
  g <- g + scale_x_date(labels = date_format(dateFormat))
  g <- g + theme(plot.title = element_text(family = "Meiryo",hjust = 0.5,size = 15))
  g <- g + theme(axis.title.x = element_text(family = "Meiryo",size = 15))
  g <- g + theme(axis.title.y = element_text(family = "Meiryo",size = 15))
  g <- g + theme(axis.text.x = element_text(family = "Meiryo",size = 15, angle = 0))
  g <- g + theme(axis.text.y = element_text(family = "Meiryo",size = 15, angle = 90))
  g <- g + xlab("")
  g <- g + ylab(paste(colnames(plotData)[2]))
  g <- g + ggtitle(paste0(colnames(plotData)[2],'\n',dateRange,
                         '\nSource:',dataSource,
                         '\nUnit Root Test p-value:',round(tseries::adf.test(plotData[,2])$p.value,3),
                         '\nLatest:',latestData))
  print(g)
  dev.off()
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
library(ggpubr)
library(ggsci)
fun_ggboxplotByMonth <-
  function(obj,dateCol = 1,objCol = 2,ggtheme = theme_bw(),palette = "UChicago",
           add = "jitter",pngN){
    setwd(pathOutput)
    pngFile <- paste0('AMCC-science-Box-',pngN,".png")
    png(file = pngFile, width = pngWidth, height = pngHeight)
    plotData <- obj[,c(dateCol,objCol)]
    plotData$Month <-
      as.factor(lubridate::month(plotData[,1]))
    colnames(plotData)[2] <- 'Value'
    if(length(unique(lubridate::day(plotData$Date)))<=5){
      dateFormat <- '%Y-%m'
    }else{
      dateFormat <- '%Y-%m-%d'
    }
    dateRange <- paste0(format(range(plotData$Date),dateFormat),collapse = '~')
    p <-
      ggboxplot(plotData,x = "Month",y = 'Value',color = "Month",palette = palette,
                add = add,ggtheme = ggtheme,repel = T)
    p <- p + ylab(colnames(obj)[objCol]) + theme(legend.position = "none")
    p <- p + ggtitle(paste0(colnames(obj)[objCol],'\n',dateRange,'\nSource:',dataSource))
    p <- p + theme(plot.title =   element_text(hjust = 0.5,family = 'Meiryo',face = 'plain',size = 15))
    p <- p + theme(legend.text =  element_text(hjust = 0.5,family = 'Meiryo',face = 'plain',size = 15))
    p <- p + theme(axis.title.x = element_text(hjust = 0.5,family = 'Meiryo',face = 'plain',size = 15))
    p <- p + theme(axis.title.y = element_text(hjust = 0.5,family = 'Meiryo',face = 'plain',size = 15))
    p <- p + theme(axis.text =    element_text(hjust = 0.5,family = 'Meiryo',face = 'plain',size = 15))
    print(p)
    dev.off()
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
fun_ggplot_acf <- function(obj,objCol = 2,lag.max = 12*30,pngN){
  setwd(pathOutput)
  pngFile <- paste0('AMCC-science-ACF-',pngN,".png")
  png(file = pngFile, width = pngWidth, height = pngHeight)
  if(length(unique(lubridate::day(obj$Date)))<=5){
    dateFormat <- '%Y-%m'
  }else{
    dateFormat <- '%Y-%m-%d'
  }
  dateRange <- paste0(format(range(obj$Date),dateFormat),collapse = '~')
  p <- autoplot(acf(x = obj[,objCol],plot = F,lag.max = lag.max))
  p <- p + ggtitle(paste0(colnames(obj)[objCol],'\n',dateRange,'\nSource:',dataSource))
  p <- p + theme(plot.title =   element_text(hjust = 0.5,family = 'Meiryo',face = 'plain',size = 15))
  p <- p + theme(legend.text =  element_text(hjust = 0.5,family = 'Meiryo',face = 'plain',size = 15))
  p <- p + theme(axis.title.x = element_text(hjust = 0.5,family = 'Meiryo',face = 'plain',size = 15))
  p <- p + theme(axis.title.y = element_text(hjust = 0.5,family = 'Meiryo',face = 'plain',size = 15))
  p <- p + theme(axis.text =    element_text(hjust = 0.5,family = 'Meiryo',face = 'plain',size = 15))
  print(p)
  dev.off()
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
# http://nsidc.org/data/g02135.html
datatitleSeaIceIndex <-
  c("Sea Ice Index Data:North",
    "Sea Ice Index Data:South",
    "Sea Ice Index Data:Total(North+South)")
dataUrlSeaIceIndex <- 
  c('ftp://sidads.colorado.edu/DATASETS/NOAA/G02135/north/daily/data/N_seaice_extent_daily_v2.1.csv',
    'ftp://sidads.colorado.edu/DATASETS/NOAA/G02135/south/daily/data/S_seaice_extent_daily_v2.1.csv')
dataSource <- 'National Snow and Ice Data Center'
seaIceIndex <- list()
for(iii in 1:2){
  buf <- 
    read.csv(dataUrlSeaIceIndex[iii],header = T,skip = 0,stringsAsFactor = F, 
             na.strings = c(""),check.names = F)
  colnames(buf) <- gsub('\\s','',paste0(colnames(buf),':',buf[1,]))
  buf <- buf[-1,]
  buf$Date <-
    as.Date(gsub('\\s','',paste0(buf$`Year:YYYY`,'-',buf$`Month:MM`,'-',buf$`Day:DD`)))
  area <-
    toupper(gsub('.+G02135/([^/]+)/.+','\\1',dataUrlSeaIceIndex[iii]))
  seaIceIndex[[iii]] <-
    data.frame(Date=buf$Date,apply(buf[,c(4,5)],2,as.numeric),stringsAsFactors = F,
               row.names = NULL,check.names = F)
  colnames(seaIceIndex[[iii]])[2:3] <- 
    paste0('Sea Ice Index:',area,':',colnames(seaIceIndex[[iii]])[2:3])
  print(tail(seaIceIndex[[iii]]))
}
mergeData <- merge(seaIceIndex[[1]],seaIceIndex[[2]])
objCol <- grep('extent',colnames(mergeData),ignore.case = T)
unit <- unique(gsub('.+:([^:]+)','\\1',colnames(mergeData)[objCol]))
mergeData$`Total(North+South)` <- apply(mergeData[,objCol],1,sum)
iii <- 3
seaIceIndex[[iii]] <- mergeData[,c(1,ncol(mergeData))]
colnames(seaIceIndex[[iii]])[2] <- paste0('Sea Ice Index:',colnames(seaIceIndex[[iii]])[2],':',unit)
print(tail(seaIceIndex[[iii]]))
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
for(iii in 1:3){
  fun_ggplot_line(plotData = seaIceIndex[[iii]],pngN = iii)
  fun_ggboxplotByMonth(obj = seaIceIndex[[iii]],pngN = iii)
  fun_ggplot_acf(obj = seaIceIndex[[iii]],objCol = 2,pngN = iii)
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
dataSource <- 'Royal Observatory of Belgium'
script <-
  RCurl::getURL(
    url = "https://raw.githubusercontent.com/am-consulting/Rscript/master/Rscript_SunspotNumber.r",
    ssl.verifypeer = F)
eval(parse(text = script))
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
for(iii in 1:3){
  switch(iii,
         plotData <- origData_sunspot01[,c(1,3)],
         plotData <- origData_sunspot02[,c(1,4)],
         plotData <- origData_sunspot02[,c(1,5)])
  fun_ggplot_line(plotData = plotData,pngN = iii+3)
  fun_ggboxplotByMonth(obj = plotData,pngN = iii+3)
  fun_ggplot_acf(obj = plotData,objCol = 2,pngN = iii+3)
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
dataSource <- 'Japan Meteorological Agency'
url_CO2 <- c(
  "http://ds.data.jma.go.jp/ghg/kanshi/obs/co2_monthave_ryo.csv",
  "http://ds.data.jma.go.jp/ghg/kanshi/obs/co2_monthave_mnm.csv",
  "http://ds.data.jma.go.jp/ghg/kanshi/obs/co2_monthave_yon.csv")
CO2 <- list()    
for(iii in 1:length(url_CO2)){
  tmp0 <-
    read.csv(file = url_CO2[iii],header = T,skip = 0,stringsAsFactor = F,check.names = F)
  tmp <- tmp0[,-c(4:5)]
  tmp[,3] <- as.numeric(tmp[,3])
  tmp <- tmp[!is.na(tmp[,3]),]
  tmp <- 
    data.frame(Date = as.Date(paste0(tmp[,1],"-",tmp[,2],"-1")),co2 = tmp[,3])
  colnames(tmp)[2] <- Nippon::zen2han(paste0(colnames(tmp0)[3],':ppm'))
  CO2[[iii]] <- tmp
  print(tail(CO2[[iii]]))
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
for(iii in 1:3){
  fun_ggplot_line(plotData = CO2[[iii]],pngN = iii+6)
  fun_ggboxplotByMonth(obj = CO2[[iii]],pngN = iii+6)
  fun_ggplot_acf(obj = CO2[[iii]],objCol = 2,pngN = iii+6)
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
dataSource <- 'Japan Meteorological Agency'
sourceURL_MMT <- 
  c("http://www.data.jma.go.jp/cpdinfo/temp/list/mon_wld.html",
    "http://www.data.jma.go.jp/cpdinfo/temp/list/mon_jpn.html")
dataTitles <- 
  c("Monthly Mean Temperature Anomaly:World\n(Celsius,Base Line:30 years mean from Y1981 to Y2010)",
    "Monthly Mean Temperature Anomaly:Japan\n(Celsius,Base Line:30 years mean from Y1981 to Y2010)")
MMT <- list()
for(iii in 1:length(sourceURL_MMT)){
  buf0 <-
    XML::readHTMLTable(doc = sourceURL_MMT[iii],header = T,trim = T,stringsAsFactors = F,as.data.frame = T,which = 1)
  buf1 <- buf0
  buf1[,-1] <- 
    sapply(buf1[,-1],function(x){gsub('\\+|\\*','',x)})
  buf2 <- 
    data.frame(Year = buf1[,1],sapply(buf1[,-1],as.numeric),check.names = F,stringsAsFactors = F)
  print(tail(buf2))
  start <- 
    as.numeric(gsub("年","",buf2[1,1]))
  tmpValue <- 
    as.numeric(as.vector(t(buf2[,-1])))
  tmpDate <- 
    seq(as.Date(paste0(start,"-1-1")),by = "month",length.out = length(tmpValue))
  buf3 <- 
    data.frame(Date = tmpDate,value = tmpValue,stringsAsFactors = F,check.names = F,row.names = NULL)
  buf4 <- na.omit(buf3)
  colnames(buf4)[2] <- dataTitles[iii]
  MMT[[iii]] <- buf4
  print(tail(MMT[[iii]]))
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
for(iii in 1:2){
  fun_ggplot_line(plotData = MMT[[iii]],pngN = iii+9)
  fun_ggboxplotByMonth(obj = MMT[[iii]],pngN = iii+9)
  fun_ggplot_acf(obj = MMT[[iii]],objCol = 2,pngN = iii+9)
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
dataSource <- 'Japan Meteorological Agency'
library(rvest)
url_SST <- 
  c("http://www.data.jma.go.jp/gmd/cpd/data/elnino/index/nino3abs.html",
    "http://www.data.jma.go.jp/gmd/cpd/data/elnino/index/ninowabs.html",
    "http://www.data.jma.go.jp/gmd/cpd/data/elnino/index/iobwabs.html")
dataTitles <- 
  c("NINO.3 Sea Surface Temperature(Celsius)",
    "NINO.WEST Sea Surface Temperature(Celsius)",
    "IOBW Sea Surface Temperature(Celsius)")
SST <- list()
startRaw <- 2
for (iii in 1:length(url_SST)) {
  source <- read_html(url_SST[iii])
  tmp01 <- 
    source %>% html_nodes(xpath = '//pre') %>% html_text %>% iconv(from = "UTF-8")
  tmp01 <- gsub('^\n','',tmp01)
  buf <- strsplit(tmp01,"\n")
  for(fff in startRaw:length(buf[[1]])){
    tmp02 <- buf[[1]][fff]
    tmp02 <- gsub('^\\s','',tmp02)
    tmp02 <- gsub("  "," ",tmp02)
    tmp02 <- strsplit(tmp02," ")
    tmp03 <- t(tmp02[[1]])
    if(fff == startRaw){
      tmp04 <- as.data.frame(tmp03)
    }else{
      tmp04 <- rbind(tmp04,as.data.frame(tmp03))
    }
  }
  tmp04 <- 
    data.frame(apply(tmp04,2,as.numeric),stringsAsFactors = F,check.names = F)
  tmp05 <-
    data.frame(Date = seq(as.Date(paste0(tmp04[1,1],"-1-1")),by = "month",length = nrow(tmp04)*12),
               value = as.vector(t(tmp04)[-1,]),
               check.names = F,stringsAsFactors = F,row.names = NULL)
  tmp05[tmp05 == 99.9] <- NA
  colnames(tmp05)[2] <- dataTitles[[iii]]
  SST[[iii]] <- na.omit(tmp05)
  print(tail(SST[[iii]]))
}
```

```{r warning=F,error=F,message=F,echo=F,results='hide'}
for(iii in 1:3){
  fun_ggplot_line(plotData = SST[[iii]],pngN = iii+12)
  fun_ggboxplotByMonth(obj = SST[[iii]],pngN = iii+12)
  fun_ggplot_acf(obj = SST[[iii]],objCol = 2,pngN = iii+12)
}
```
