```{r warning=F,error=F,message=F,echo=F,results='hide'}
windowsFonts(Meiryo = windowsFont("Meiryo"))
pngWidth <- 1000
pngHeight <- 600
userName <- Sys.info()['user']
fileName <- 'defaultPath.csv'
pathToFile <-
  paste0('C:/Users/',userName,'/Desktop/pathToCSV/')
setwd(pathToFile)
buf0 <-
  read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,
           fileEncoding = 'UTF8')
pathOutputForecast <- paste0('C:/Users/',userName,buf0[2,1],'charts/indicator/AMCCchartImages/')
```

```{r}
library(Nippon);library(ggplot2);library(scales)
pathOutput <- 
  paste0("C:/Users/",Sys.info()['user'],"/Desktop/R_Data_Write/")
setwd(pathOutput)
targetFile <- 'b2010_kj.zip'
targetURL <- 'http://www.meti.go.jp/statistics/tyo/sanzi/result/csv/'
download.file(paste0(targetURL,targetFile),targetFile, mode = 'wb')
csvFile <- unzip(targetFile)[grep('mj.csv',unzip(targetFile))]
sheetTitle <- vector()
TertiaryIndustryActivity <- list()
for(iii in seq(length(csvFile))){
  buf0 <- read.csv(file = csvFile[iii],header = F,stringsAsFactors = F,fileEncoding = 'shift_jis')
  sheetTitle[iii] <- gsub('.+:(.+)','\\1',zen2han(buf0[1,1]))
  buf1 <- t(buf0[-c(1:2),])
  colnames(buf1) <- sapply(paste0(buf1[2,],'(ウエイト:',gsub('\\s+','',buf1[3,]),')'),zen2han)
  buf2 <- buf1[-c(1:3),]
  Date <- as.Date(paste0(substring(buf2[,1],1,4),'-',substring(buf2[,1],5,6),'-1'))
  TertiaryIndustryActivity[[iii]] <- 
    data.frame(Date,apply(buf2[,-1],2,as.numeric),stringsAsFactors = F,check.names = F,row.names = NULL)
  if(length(grep('原指数',sheetTitle[iii]))!=0){
    addTxt <- ':原指数'
  }else{
    addTxt <- ':季調済指数'
  }
  colnames(TertiaryIndustryActivity[[iii]])[-1] <-
    paste0(colnames(TertiaryIndustryActivity[[iii]])[-1],addTxt)
  colnames(TertiaryIndustryActivity[[iii]]) <-
    gsub('^\\s+','',colnames(TertiaryIndustryActivity[[iii]]))
  print(tail(TertiaryIndustryActivity[[iii]][,1:4]))
}
```

```{r}
for(ccc in 2:ncol(TertiaryIndustryActivity[[1]])){
  buf1 <- na.omit(TertiaryIndustryActivity[[1]][,c(1,ccc)])
  buf2 <- na.omit(TertiaryIndustryActivity[[2]][,c(1,ccc)])
  objA <- merge(buf1,buf2,by = 'Date')
  mainTitle <- unique(gsub('(.+\\)):(.+)','\\1',colnames(objA)[-1]))
  colnames(objA)[-1] <- gsub('(.+\\)):(.+)','\\2',colnames(objA)[-1])
  buf1$Type <- gsub('(.+\\)):(.+)','\\2',colnames(buf1)[2])
  buf2$Type <- gsub('(.+\\)):(.+)','\\2',colnames(buf2)[2])
  colnames(buf1)[2] <- gsub('(.+\\)):(.+)','\\1',colnames(buf1)[2])
  colnames(buf2)[2] <- gsub('(.+\\)):(.+)','\\1',colnames(buf2)[2])
  objB <- rbind(buf1,buf2)
  cols <- c("原指数" = "black","季調済指数" = "red")
  dateRange <- paste0(format(range(objA[,1]),'%Y-%m'),collapse = '~')
  abenomics <- objA[as.Date('2013-1-1')<=objA$Date,]
  minshutou <- objA[as.Date('2009-9-1')<=objA$Date & objA$Date<=as.Date('2012-12-1'),]
  g <- ggplot(data = objA,aes(x = objA[,1]))
  g <- g + geom_line(aes(y = objA[,2],colour = '原指数'))
  g <- g + geom_line(aes(y = objA[,3],colour = '季調済指数'))
  g <- g + geom_point(aes(y = objA[,3],colour = '季調済指数'))
  g <- g + geom_smooth(aes(y = objA[,3]),col = 'orange')
  g <- g + ggtitle(label = paste0(mainTitle,'\n',dateRange,'\nSource:経済産業省'),
                   subtitle = '青色サークル:第二次安倍政権発足以降,赤色サークル:民主党政権時')
  g <- g + scale_colour_manual(name = '',values = cols)
  g <- g + scale_x_date(name = '',date_breaks = '3 month',labels= date_format('%Y-%m'))
  g <- g + scale_y_continuous(name = '',breaks = scales::pretty_breaks(10),sec.axis = dup_axis())
  g <- g + theme(plot.title = element_text(hjust = 0.5,family = "Meiryo",size = 20))
  g <- g + theme(plot.subtitle = element_text(hjust = 0.5,family = "Meiryo",size = 12))
  g <- g + theme(axis.title.x = element_text(family = "Meiryo",size = 16)) 
  g <- g + theme(axis.title.y = element_text(family = "Meiryo",size = 16)) 
  g <- g + theme(axis.text.x = element_text(angle = 90,family = "Meiryo",size = 12,vjust = 0.5)) 
  g <- g + theme(axis.text.y = element_text(angle = 0,family = "Meiryo",size = 16))
  g <- g + theme(legend.text = element_text(angle = 0,family = "Meiryo",size = 16))
  g <- g + theme(legend.position = "top")
  g <- g + geom_encircle(data=abenomics,show.legend = F,
                         aes(x=abenomics$Date, y=abenomics$`季調済指数`),color="blue",size=1,expand=0.01)
  g <- g + geom_encircle(data=minshutou,
                         aes(x=minshutou$Date, y=minshutou$`季調済指数`),color="red",size=1,expand=0.01)
  print(g)
}
```
