```{r}
library(quantmod);library(forecast);library(gridExtra);library(grid)
library(RCurl);library(excel.link)
options(scipen = 999)
windowsFonts(Meiryo = windowsFont("Meiryo"))
fileName <- 'functionList.csv'
functionList <-
  read.csv(
    file = paste0('https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/csv/',
                  fileName),
    header = F,
    as.is = T)
for(iii in 1:nrow(functionList)){
  script <- 
    getURL(paste0("https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/", functionList[iii,1]),
    ssl.verifypeer = F
  )
  eval(parse(text = script))
}
nValue <- c(50,52) # 1 daily 2 weekly
fun_plot <- function(s = 1,e = 16,tailN = 100,pngN = 1){
  pngFile <- paste0('AMCC-',pngN,".png")
  png(file = pngFile, width = 1400, height = 900)
  par(mfrow = c(4,4),oma = c(2,0,5,0),family = 'Meiryo',font.main = 2,mar = c(4,3,8,1),
      cex.main = 1.5,cex.axis = 1.4)
  for(iii in s:e){
    obj0 <- na.omit(dailyChart[[iii]])
    if(min(unique(diff(obj0[,1])))==1){label <- 'Daily'}else{label <- 'Weekly'}
    if(label == 'Daily'){n <- nValue[1]}else{n <- nValue[2]}
    obj <- tail(fun_MovingAverage(obj = obj0,n= n,dateFormat = dateFormat),tailN)
    # chart colour
    diff <- diff(na.omit(obj[,2]))
    PN <- ifelse(0<diff,1,ifelse(diff<0,-1,0))
    x <- cumsum(rev(PN))
    if(x[1]==0){
      change <- 0
      col <- rgb(red = 1,green = 1,blue = 1)
    }else{
      neg <- x[max(which(x==(seq(length(PN))*-1)))]
      pos <- x[max(which(x==seq(length(PN))))]
      change <- max(pos,neg,na.rm = T)
      if(10<change){change <- 10}
      if(0<change){
        col <- rgb(red = 0,green = 0,blue = 1,alpha = 0.1*abs(change))
      }else{
        col <- rgb(red = 1,green = 0,blue = 1,alpha = 0.1*abs(change))
      }
    }
    # chart colour
    # chart backgroundcolour
    ylim <- c(min(obj[,2:3],na.rm = T),max(obj[,2:3],na.rm = T))
    plot(obj[,1],obj[,2],ylim = ylim,xaxt = 'n',yaxt = 'n',xlab = '',ylab = '')
    rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col = col)
    par(new = T)
    # chart backgroundcolour
    # 前日(週)差
    latestDiff <- round(tail(diff(na.omit(obj[,2])),1),8)
    if(0<latestDiff){
      diffTxt <- paste0('+',latestDiff)
    }else if(latestDiff<0){
      diffTxt <- latestDiff
    }else{
      diffTxt <- '±0'
    }    
    # 前日(週)差
    plot(obj[,1],obj[,2],type = 'o',xaxt = 'n',xlab = '',ylab = '',
         pch = 20,cex = 1.4,ylim = ylim,
         main = paste0(colnames(obj)[2],'\n',tail(obj,1)[,1],':',round(tail(obj,1)[,2],4),', ',diffTxt,'\n',
                       paste0(range(obj[,1]),collapse = '~')))
    grid(nx = NULL, ny = NULL, col = "dimgray", lty = "dotted",lwd = 1)
    axis.Date(side = 1,at = obj[,1],format = dateFormat)
    lines(obj[,1],obj[,3],type = 'l',col = 'red',lwd = 2)
    text(x = grconvertX(0.5, from = "npc"),
         y = grconvertY(0.5, from = "npc"),
         labels = label,
         cex = 3,font = 2,col = rgb(1,0,0,0.4),srt = 0)
  }
  mtext(text = paste0('Red Line:Moving Average(Over ',nValue[1],' days or ',nValue[2],' weeks)'),
        side = 1,outer = T,col = 'red',cex = 1.5)
  mtext(text = paste0('Latest ',tailN,
                      ' days(weeks).Source:Oanda,FRED,MOF,CBOE,NIKKEI,IIMA,EIA,JSDA,S&P,Mizuho Bank, Ltd.,EIA,ECRI,NAAIM'),
        side = 3,outer = T,col = 'black',cex = 1.8,line = 1)
  dev.off()
}
dailyChart <- list()
```

```{r}
cnt <- 1
dateFormat <- '%Y%m%d'
fromOANDA <- c('USD/JPY','EUR/USD','CNY/USD','TWD/USD','CHF/USD','USD/KRW','BTC/USD','XAU/USD','XAU/XAG','XAU/XPT','BTC/XAU','ZAR/USD')
for(iii in seq(length(fromOANDA))){
  obj <- getSymbols(Symbols = fromOANDA[iii],auto.assign = F,src = 'oanda')
  colnames(obj) <- gsub('\\.','/',colnames(obj))
  dailyChart[[cnt]] <-
    data.frame(Date = index(obj),obj,stringsAsFactors = F,check.names = F,row.names = NULL)
  print(tail(dailyChart[[cnt]]))
  cnt <- cnt + 1
}
script <-
  RCurl::getURL(
    "https://raw.githubusercontent.com/am-consulting/Rscript/master/Rscript_JGBInterestRate.r",
    ssl.verifypeer = F)
eval(parse(text = script))
obj <-
  na.omit(jgbData[,c(1,grep('10y',colnames(jgbData),ignore.case = T))])
colnames(obj)[2] <- 
  paste0('JGB Interest Rate(%):',colnames(obj)[2])
dailyChart[[cnt]] <- obj
print(tail(dailyChart[[cnt]]))
cnt <- cnt + 1
obj <-
  na.omit(jgbData[,c(1,grep('30y',colnames(jgbData),ignore.case = T))])
colnames(obj)[2] <- 
  paste0('JGB Interest Rate(%):',colnames(obj)[2])
print(tail(obj))
dailyChart[[cnt]] <- obj
cnt <- cnt + 1
fromYahoo <- 
  c('DGS10','10-Year Treasury Constant Maturity Rate',
    'T10Y2Y','10-Year Treasury Constant Maturity\nMinus 2-Year Treasury Constant Maturity',
    'T10YIE','10-Year Breakeven Inflation Rate',
    'T5YIFR','5-Year, 5-Year Forward Inflation Expectation Rate',
    'IC4WSA','4-Week Moving Average of Initial Claims')
for(iii in seq(1,length(fromYahoo),by = 2)){
  obj <- getSymbols(Symbols = fromYahoo[iii],auto.assign = F,src = 'FRED')
  obj <-
    data.frame(Date = index(obj),obj,
               stringsAsFactors = F,check.names = F,row.names = NULL)
  colnames(obj)[2] <- fromYahoo[iii+1]
  dailyChart[[cnt]] <- obj
  print(tail(dailyChart[[cnt]]))
  cnt <- cnt + 1
}
obj <-
  read.csv(
    file = 'http://www.cboe.com/publish/scheduledtask/mktdata/datahouse/vixcurrent.csv',
    header = T,
    as.is = T,
    check.names = F,
    stringsAsFactors = F,
    skip = 1)
obj[,1] <-
  as.Date(gsub('([0-9]+)/([0-9]+)/([0-9]+)','\\3-\\1-\\2',obj[,1]))
obj <-
  obj[,grep('date|close',colnames(obj),ignore.case = T)]
dailyChart[[cnt]] <- obj
print(tail(dailyChart[[cnt]]))
cnt <- cnt + 1
obj <-
  read.csv(
    file = 'http://indexes.nikkei.co.jp/nkave/historical/nikkei_stock_average_daily_en.csv',
    header = T,
    as.is = T,
    check.names = F,
    stringsAsFactors = F)
obj <- 
  na.omit(obj[,c(1,2)])
colnames(obj) <- 
  c('Date',paste0('NIKKEI225:',colnames(obj)[2]))
obj[,1] <- 
  as.Date(obj[,1])
print(tail(obj))
dailyChart[[cnt]] <- obj
buf_cnt01 <- cnt
```

```{r}
importIndex <- 
  c('importPutCallRatios.r','importSkew.r','importTokyoRepoRate.r',
    'importHenryHubNaturalGasSpotPrice.r','importGMVI.r','importREIT.r',
    'importNaturalGasPrice.r','importNYMEXFuturesPrices.r','importLIBORandTED.r',
    'importDepositInterest-Rate-2017.r','importHistoricalFXData.r')
for(jjj in seq(length(importIndex))){
  script <- 
    RCurl::getURL(paste0("https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/", 
                         importIndex[jjj]),
                  ssl.verifypeer = F)
  eval(parse(text = script))
  gc();gc();
}
```

```{r}
cnt <- buf_cnt01
for(put in 1:5){
  cnt <- cnt + 1
  tmp <- putCallRatio[[put]]
  if(put!=5){
    obj <- na.omit(tmp[,c(1,ncol(tmp))])
  }else{
    obj <- na.omit(tmp[,c(1,2)])
  }
  obj[,1] <- 
    as.Date(obj[,1])
  dailyChart[[cnt]] <- obj
  print(tail(dailyChart[[cnt]]))
}
```

```{r}
cnt <- cnt + 1
obj <- 
  na.omit(skewCBOE)
obj[,1] <- 
  as.Date(obj[,1])
dailyChart[[cnt]] <- obj
for(ccccc in 2:ncol(TokyoRepoRate)){
  cnt <- cnt + 1
  obj <- 
    na.omit(TokyoRepoRate[,c(1,ccccc)])
  obj[,1] <- 
    as.Date(obj[,1])
  colnames(obj)[2] <- paste0('Tokyo Repo Rate\n',colnames(obj)[2])
  dailyChart[[cnt]] <- obj
  print(tail(dailyChart[[cnt]]))
}
```

```{r}
cnt <- cnt + 1
obj <- 
  na.omit(HenryHubNaturalGasSpotPrice[[1]])
obj[,1] <- 
  as.Date(obj[,1])
colnames(obj)[2] <- 
  gsub('price\\s','Price\n',colnames(obj)[2],ignore.case = T)
dailyChart[[cnt]] <- obj
print(tail(dailyChart[[cnt]]))
tmp <- NaturalGasPrice[[2]]
tmp[,1] <- as.Date(tmp[,1])
for(cccc in 2:ncol(tmp)){
  cnt <- cnt + 1
  obj <- na.omit(tmp[,c(1,cccc)])
  colnames(obj)[2] <- 
    gsub('\\s\\(Dollars','\n(Dollars',colnames(obj)[2],ignore.case = T)
  dailyChart[[cnt]] <- obj
  print(tail(dailyChart[[cnt]]))
}
```

```{r}
for(nnnn in c(1,3,4)){
  tmp <- NYMEXFuturesPrices[[nnnn]]
  tmp[,1] <- as.Date(tmp[,1])
  for(cccc in 2:ncol(tmp)){
    cnt <- cnt + 1
    obj <- na.omit(tmp[,c(1,cccc)])
    colnames(obj)[2] <- 
      gsub('\\s\\(Dollars','\n(Dollars',colnames(obj)[2],ignore.case = T)
    colnames(obj)[2] <- 
      gsub('Harbor\\s','Harbor\n',colnames(obj)[2],ignore.case = T)
    dailyChart[[cnt]] <- obj
    print(tail(dailyChart[[cnt]]))
  }
}
buf_cnt02 <- cnt
```

```{r}
cnt <- buf_cnt02
for(cccc in 2:ncol(LIBOR)){
  cnt <- cnt + 1
  obj <- na.omit(LIBOR[,c(1,cccc)])
  colnames(obj)[2] <- 
    gsub('\\s\\(LIBOR','\n(LIBOR',colnames(obj)[2],ignore.case = T)
  dailyChart[[cnt]] <- obj
  print(tail(dailyChart[[cnt]]))
}
for(gggg in c(2:5,7)){
  cnt <- cnt + 1
  obj <- 
    na.omit(GMVI1[,c(1,gggg)])
  obj[,1] <- 
    as.Date(obj[,1])
  dailyChart[[cnt]] <- obj
  print(tail(dailyChart[[cnt]]))
}
for(gggg in c(2:9)){
  cnt <- cnt + 1
  obj <- 
    na.omit(GMVI2[,c(1,gggg)])
  colnames(obj)[2] <- gsub(':','\n',colnames(obj)[2])
  obj[,1] <- 
    as.Date(obj[,1])
  dailyChart[[cnt]] <- obj
  print(tail(dailyChart[[cnt]]))
}
```

```{r}
cnt <- cnt + 1
obj <- 
  na.omit(`sp-global-reit-us-dollar`[,c(1,3)])
obj[,1] <- 
  as.Date(obj[,1])
obj[,2] <- 
  as.numeric(obj[,2])
dailyChart[[cnt]] <- obj
print(tail(dailyChart[[cnt]]))
cnt <- cnt + 1
obj <- 
  na.omit(`sp-united-states-reit-us-dollar`[,c(1,3)])
obj[,1] <- 
  as.Date(obj[,1])
obj[,2] <- 
  as.numeric(obj[,2])
dailyChart[[cnt]] <- obj
print(tail(dailyChart[[cnt]]))
cnt <- cnt + 1
obj <- 
  na.omit(`sp-developed-reit-us-dollar`[,c(1,3)])
obj[,1] <- 
  as.Date(obj[,1])
obj[,2] <- 
  as.numeric(obj[,2])
dailyChart[[cnt]] <- obj
print(tail(dailyChart[[cnt]]))
```

```{r}
for(gggg in c(2:3)){
  cnt <- cnt + 1
  obj <- 
    na.omit(DepositInterestRate[,c(1,gggg)])
  colnames(obj)[2] <- gsub(':','\n',colnames(obj)[2])
  obj[,1] <- 
    as.Date(obj[,1])
  print(tail(obj,2))
  dailyChart[[cnt]] <- obj
  print(tail(dailyChart[[cnt]]))
}
buf_cnt03 <- cnt
```

```{r}
# effective FX
# http://www.bis.org/statistics/full_data_sets.htm
# http://www.bis.org/statistics/eer.htm
gc();gc();
cnt <- buf_cnt03
fun_effectiveFX <- function(){
  pathOutput <- paste0("C:/Users/",Sys.info()['user'],"/Desktop/R_Data_Write/")
  setwd(pathOutput)
  urlToData <- 'http://www.bis.org/statistics/'
  zipFile <- 'full_webstats_eer_d_dataflow_csv.zip'
  if(!file.exists(paste0(pathOutput,zipFile))) {
    download.file(paste0(urlToData,zipFile), zipFile, mode = 'wb')
  }
  buf0 <- 
    xl.read.file(filename = unzip(zipFile), header=F, top.left.cell = "A1", 
                 xl.sheet = 1, excel.visible = F)
  buf1 <- buf0
  cc <- which((apply(buf1,2,(function(x)length(grep('reference area',x,ignore.case = T)))))!=0)
  rr <- which((apply(buf1,1,(function(x)length(grep('reference area',x,ignore.case = T)))))!=0)
  buf2 <- buf1[rr:nrow(buf1),cc:ncol(buf1)]
  buf3 <- t(buf2) # matrix
  buf3 <- data.frame(buf3,row.names = NULL,stringsAsFactors = F)
  colnames(buf3) <- paste0(unlist(buf3[1,]),'-',unlist(buf3[2,]))
  buf3 <- buf3[-c(1:2),]
  colnames(buf3)[1] <- 'Date'
  class(buf3[,1])
  buf3[,1] <- as.Date(buf3[,1])
  class(buf3[,1])
  buf3[,-1] <- apply(buf3[,-1],2,as.numeric)
  class(buf3[,ncol(buf3)])
  buf4 <- buf3
  buf4[is.na(buf4)] <- NA
  return(buf4)
}
EERdataSet <- fun_effectiveFX()
objCol <- grep('(\\bgb|\\bus|\\bjp):.+D:N:N:(\\bgb|\\bus|\\bjp)',colnames(EERdataSet),ignore.case = T)
for(cccc in objCol){
  cnt <- cnt + 1
  obj <- 
    na.omit(EERdataSet[,c(1,cccc)])
  obj[,1] <- 
    as.Date(obj[,1])
  colnames(obj)[2] <- paste0('Effective Exchange Rate\n',colnames(obj)[2])
  print(tail(obj,2))
  dailyChart[[cnt]] <- obj
  print(tail(dailyChart[[cnt]]))
}
# effective FX
buf_cnt04 <- cnt
```

```{r}
# historical FX
cnt <- buf_cnt04
objCurrency <- 
  c('Date','米ドル','英ポンド','ユーロ','カナダ','スイス','オーストラリア','ニュージーランド','南アフリカ','中国')
historicalFXData <-
  historicalFXData[,!is.na(tail(historicalFXData,1))]
buf <- 
  historicalFXData[,grep(paste0(objCurrency,collapse = '|'),colnames(historicalFXData))]
for(ccc in 2:ncol(buf)){
  cnt <- cnt + 1
  obj <- na.omit(buf[,c(1,ccc)])
  obj[,1] <- as.Date(obj[,1])
  colnames(obj)[-1] <- paste0('FX QUOTATION(Unit:JPY):',colnames(obj)[-1])
  print(tail(obj,2))
  dailyChart[[cnt]] <- obj
  gc();gc();
}
# historical FX
```

```{r}
fromYahoo <- 
  c('TREAST','U.S.Treasury securities\nheld by the Federal Reserve\nAll Maturities:T$',
    'MBST','Mortgage-backed securities\nheld by the Federal Reserve\nAll Maturities:T$')
for(iii in seq(1,length(fromYahoo),by = 2)){
  cnt <- cnt + 1
  obj <- getSymbols(Symbols = fromYahoo[iii],auto.assign = F,src = 'FRED')
  obj <-
    data.frame(Date = index(obj),obj,
               stringsAsFactors = F,check.names = F,row.names = NULL)
  colnames(obj)[2] <- fromYahoo[iii+1]
  obj[,2] <- obj[,2]*10^-6
  dailyChart[[cnt]] <- obj
  print(tail(dailyChart[[cnt]]))
}
```

```{r}
# weekly leading index
cnt <- cnt + 1
library(excel.link)
pathOutput <- 
  paste0("C:/Users/", Sys.info()['user'], "/Desktop/R_Data_Write/")
setwd(pathOutput)
fileName <- 'ECRI_wliw_free.xls'
fileURL <- 'https://www.businesscycle.com/download/index/WLIW_f'
download.file(fileURL, fileName, mode = "wb")
buf0 <- 
  XLConnect::readWorksheetFromFile(paste0(pathOutput, fileName), sheet = 1, check.names = F, header = F)
bufRow <- 
  grep('date',buf0[,1],ignore.case = T)
buf <- 
  xl.read.file(fileName, header=T, top.left.cell = paste0("A",bufRow),
               xl.sheet = 1, excel.visible = F)
buf[,1] <- as.Date(buf[,1])
buf <- buf[,apply(buf,2,function(x)sum(is.na(x)))!=nrow(buf)]
buf <- buf[!is.na(buf[,1]),]
buf[,-1] <- apply(buf[,-1],2,as.numeric)
obj <- buf[,c(1,2)]
colnames(obj)[2] <- paste0('U.S. Weekly Leading Index:',colnames(obj)[2])
print(tail(obj,2))
dailyChart[[cnt]] <- obj
# weekly leading index
buf_cnt05 <- cnt
```

```{r}
cnt <- buf_cnt05
# EIA
pathOutput <-
  paste0("C:/Users/", Sys.info()['user'], "/Desktop/R_Data_Write/")
setwd(pathOutput)
fileName <- 'psw09.xls'
if(!file.exists(paste0(pathOutput,fileName))){
  download.file(paste0('http://ir.eia.gov/wpsr/',fileName),fileName,mode = "wb")
}
targetSheet <- c(2:22)
dateFormat <- '%Y-%m-%d'
for(sss in 1:length(targetSheet)){
  buf <-
    XLConnect::readWorksheetFromFile(paste0(pathOutput,fileName),sheet = targetSheet[sss],
                          check.names = F,header = F)
  colnames(buf) <- unlist(buf[3,])
  buf <- buf[-c(1:3),]
  if(sss == 1){EIAData <- buf}else{EIAData <- merge(EIAData,buf,by = 'Date',all = T)}
  gc();gc()
}
EIAData[, 1] <- as.Date(EIAData[, 1])
EIAData <- EIAData[order(EIAData[, 1]),]
EIAData <-
  data.frame(EIAData[,1,drop = F],apply(EIAData[,-1],2,as.numeric),check.names = F)
colnameTxt <- c(
  'Weekly U.S. Ending Stocks excluding SPR of Crude Oil  ',
  'Weekly Cushing, OK Ending Stocks excluding SPR of Crude Oil  ',
  'Weekly U.S. Ending Stocks of Total Gasoline  ',
  'Weekly U.S. Ending Stocks of Distillate Fuel Oil  ',
  'Weekly U.S. Ending Stocks of Propane and Propylene  ',
  'Weekly U.S. Refiner Net Input of Crude Oil  ',
  'Weekly U.S. Percent Utilization of Refinery Operable Capacity ',
  'Weekly U.S. Imports of Crude Oil  ',
  'Weekly U.S. Imports of Total Gasoline  ')
for(iii in 1:length(colnameTxt)){
  cnt <- cnt + 1
  ccc <- grep(colnameTxt[iii],colnames(EIAData))
  obj <- EIAData[,c(1,ccc)]
  colnames(obj)[2] <- gsub('\\s{1,2}\\(','\n(',colnames(obj)[2])
  colnames(obj)[2] <- gsub('excluding\\s','excluding\n',colnames(obj)[2])
  colnames(obj)[2] <- gsub('Utilization of\\s','Utilization of\n',colnames(obj)[2])
  print(tail(obj,2))
  dailyChart[[cnt]] <- obj
  gc();gc();
}
# EIA
buf_cnt06 <- cnt
```

```{r}
cnt <- buf_cnt06
cnt <- cnt + 1
buf0 <- 
  getSymbols(Symbols = 'STLFSI',src = 'FRED',auto.assign = F)
obj <-
  data.frame(Date = index(buf0),buf0,stringsAsFactors = F,check.names = F,row.names = NULL)
colnames(obj)[2] <- 'St. Louis Fed Financial Stress Index'
print(tail(obj,2))
dailyChart[[cnt]] <- obj
buf_cnt07 <- cnt
```

```{r}
# Nikkei Index
cnt <- buf_cnt07
importIndex <- 
  c('importNikkeiIndexList.r')
for(jjj in seq(length(importIndex))){
  script <- 
    RCurl::getURL(paste0("https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/", 
                         importIndex[jjj]),
                  ssl.verifypeer = F)
  eval(parse(text = script))
}
for(rrr in seq(nrow(NikkeiDailyIndexList))){
  if(length(grep('\\(Nikkei 225\\)',NikkeiDailyIndexList[rrr,2]))==0){
    cnt <- cnt + 1
    buf0 <- 
      read.csv(file = NikkeiDailyIndexList[rrr,3],header = T,check.names = F,stringsAsFactors = F)
    buf1 <- buf0[,c(1,2)]
    colnames(buf1) <- gsub('\\(','\n(',colnames(buf1))
    if(length(grep('^close$',colnames(buf1)[2],ignore.case = T))!=0){
      colnames(buf1) <- c('Date',paste0(NikkeiDailyIndexList[rrr,2],'\n',colnames(buf1)[2]))
    }
    buf1[,1] <- as.Date(buf1[,1])
    buf1[,2] <- as.numeric(buf1[,2])
    buf1 <- na.omit(buf1)
    print(tail(buf1))
    dailyChart[[cnt]] <- buf1
    gc();gc();
  }
}
# Nikkei Index
buf_cnt08 <- cnt
```

```{r}
# NAAIM Exposure Index
cnt <- buf_cnt08
buf <- 
  read.csv(file = 'http://www.naaim.org/wp-content/plugins/ip-chart/export.php',
           header = T,stringsAsFactors = F,check.names = F)
buf[,1] <-
  as.Date(paste0(gsub('(\\d+)\\/(\\d+)\\/(\\d+)','\\3',buf[,1]),'-',
                 gsub('(\\d+)\\/(\\d+)\\/(\\d+)','\\1',buf[,1]),'-',
                 gsub('(\\d+)\\/(\\d+)\\/(\\d+)','\\2',buf[,1])))
tmp <- buf[order(buf[,1],decreasing = F),]
NAAIM_ExposureIndex <- tmp[-which(10<diff(tmp[,1])),c(1,9)]
cnt <- cnt + 1
dailyChart[[cnt]] <- NAAIM_ExposureIndex
print(tail(NAAIM_ExposureIndex))
# NAAIM Exposure Index
```

```{r}
checkDF <- data.frame()
for(iii in seq(length(dailyChart))){
  checkDF[iii,1] <- iii
  checkDF[iii,2] <- nrow(dailyChart[[iii]])
  checkDF[iii,3] <- colnames(dailyChart[[iii]])[2]
}
checkDF
```

```{r}
userName <- Sys.info()['user']
fileName <- 'defaultPath.csv'
pathToFile <-
  paste0('C:/Users/',userName,'/Desktop/pathToCSV/')
setwd(pathToFile)
buf0 <-
  read.csv(fileName,header = F,skip = 0,stringsAsFactor = F,check.names = F,
           fileEncoding = 'UTF8')
pathOutput <- paste0('C:/Users/',userName,buf0[2,1],'charts/indicator/AMCC-DailyChart/')
setwd(pathOutput)
pngN <- 1;s <- 1;e <- s + 15;fun_plot(pngN = pngN) # 16
pngN <- pngN + 1;s <- e + 1;e <- s + 15;fun_plot(s = s,e = e,pngN = pngN) # 32
pngN <- pngN + 1;s <- e + 1;e <- s + 15;fun_plot(s = s,e = e,pngN = pngN) # 48
pngN <- pngN + 1;s <- e + 1;e <- s + 15;fun_plot(s = s,e = e,pngN = pngN) # 64
pngN <- pngN + 1;s <- e + 1;e <- s + 15;fun_plot(s = s,e = e,pngN = pngN) # 80
pngN <- pngN + 1;s <- e + 1;e <- s + 15;fun_plot(s = s,e = e,pngN = pngN) # 96
pngN <- pngN + 1;s <- e + 1;e <- s + 15;fun_plot(s = s,e = e,pngN = pngN) # 112
pngN <- pngN + 1;s <- e + 1;e <- s + 15;fun_plot(s = s,e = e,pngN = pngN) # 128
pngN <- pngN + 1;s <- e + 1;e <- s + 15;fun_plot(s = s,e = length(dailyChart),pngN = pngN) # 144
chartName <- data.frame()
for(iiii in seq(cnt)){
  chartName[iiii,1] <- ceiling(iiii/16)
  chartName[iiii,2] <- gsub('\n',' ',colnames(dailyChart[[iiii]])[2])
  if(min(unique(diff(dailyChart[[iiii]][,1])))==1){
    chartName[iiii,3] <- 'Daily'
  }else{
    chartName[iiii,3] <- 'Weekly'
  }
}
colnames(chartName) <- c('No.','Indicator','Period')
getwd()
write.csv(x = chartName,file = 'chartName.csv',
          quote = T,row.names = F,append = F,fileEncoding = 'utf8')
#NIKKEI , #10YrJGB , #10YrBond , #USDJPY , #VIX, #EURUSD, #Bitcoin, #Gold, #SKEW, #Put, #Call, #TokyoRepoRate, #Henryhub, #REIT
# 1400 * 900
```
